import React, { useState } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet, ScrollView,
} from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import * as Haptics from 'expo-haptics';

// ── Data ─────────────────────────────────────────────────────────────────────

const ELEMENTS = [
  { id: 'akasha',  name: 'Akasha',  en: 'Space / Ether',        emoji: '✦',   color: '#a78bfa',
    body: 'The container in which everything exists. In the body: synaptic clefts (20 nm gaps between neurons), hollow channels (arteries, bronchi, gut lumen), extracellular matrix, and the electromagnetic field generated by 86 billion neurons firing simultaneously.',
    science: 'Extracellular space = 15L of body fluid. Synaptic vesicle zones are pure Akasha — neurotransmitters cross this gap in 0.5 ms. Interstitial fluid, pleural space, joint cavities, and the blood-brain barrier all map directly to Akasha in modern anatomy.',
    qualities: ['Infinite', 'Light', 'Subtle', 'Omnipresent', 'Sound-carrying'],
  },
  { id: 'vayu',    name: 'Vayu',    en: 'Air / Movement',        emoji: '🌬️', color: '#38bdf8',
    body: 'Every form of movement — nerve impulses at 120 m/s, peristalsis moving food through 9 metres of gut, respiratory rhythm, cardiac conduction, and the flow of thought itself. Air is not merely the gas you breathe — it is the biological principle of all motion.',
    science: 'Action potentials (70 mV impulses) traverse myelinated A-alpha fibres at 70–120 m/s. Tidal volume = 500 ml per breath. The cardiovascular system circulates 5L of blood per minute through 96,000 km of vessels. Na+/K+ ATPase creates the electrical gradient driving every nerve impulse.',
    qualities: ['Mobile', 'Dry', 'Light', 'Cold', 'Rough', 'Dispersing'],
  },
  { id: 'agni_e',  name: 'Agni',    en: 'Fire / Transformation', emoji: '🔥', color: '#fb923c',
    body: 'Every biochemical transformation — mitochondria converting glucose into 32 ATP molecules, the stomach\'s hydrochloric acid (pH 1.5) denaturing proteins, cytochrome P450 enzymes converting toxins into water-soluble metabolites. Fire is metabolic intelligence.',
    science: 'Mitochondrial oxidative phosphorylation: controlled combustion at 37°C generating 36–38 ATP per glucose. Core temperature is maintained at 37°C ± 0.5°C by the hypothalamic thermostat. 60+ CYP enzymes perform the body\'s Phase I & II detoxification cascade.',
    qualities: ['Hot', 'Sharp', 'Light', 'Spreading', 'Transforming', 'Luminous'],
  },
  { id: 'jala',    name: 'Jala',    en: 'Water / Cohesion',      emoji: '💧', color: '#34d399',
    body: 'Every fluid that holds the body together — plasma (92% water), lymph, cerebrospinal fluid, synovial fluid, bile, and the 42 litres of total body water in a 70 kg human. Water is the universal medium in which all chemistry occurs. Enzymes are biologically inert without it.',
    science: 'The body is 60–70% water by weight. Hyaluronic acid in synovial fluid (3.5 mg/ml) lubricates 360 joints. CSF (150 ml, renewed 3x daily) cushions the brain at 10–15 cmH₂O pressure. Bile (600 ml/day, 95% water) emulsifies dietary fats for lipase digestion.',
    qualities: ['Liquid', 'Cold', 'Heavy', 'Soft', 'Oily', 'Cohesive'],
  },
  { id: 'prithvi', name: 'Prithvi', en: 'Earth / Structure',     emoji: '🌍', color: '#fbbf24',
    body: 'Everything solid and structural — 206 bones (hydroxyapatite Ca₁₀(PO₄)₆(OH)₂), 640 muscles (type I collagen + actin/myosin filaments), nails, hair, teeth, and the extracellular matrix scaffolding that holds 37 trillion cells in precise three-dimensional arrangement.',
    science: 'Bone = 65% hydroxyapatite mineral + 35% type I collagen. ECM includes collagens I–IV, fibronectin, and proteoglycans. Sarcomere units (actin thin filament 8 nm + myosin thick filament 15 nm) generate force via cross-bridge cycling — pure molecular Earth principle.',
    qualities: ['Heavy', 'Stable', 'Dense', 'Hard', 'Gross', 'Static'],
  },
];

const DOSHAS = [
  { id: 'vata',  name: 'Vata',  en: 'The Force of Movement',       emoji: '🌬️', color: '#a78bfa',
    elements: 'Air + Space',
    tagline: 'Governs all movement — neural, respiratory, cardiac, and digestive.',
    biology: 'Vata maps to the Autonomic Nervous System — specifically the sympathetic (fight-or-flight) and peripheral nervous systems. Every action potential (70 mV impulse) traveling at 120 m/s through myelinated nerve fibres is pure Vata. The enteric nervous system ("second brain") — 500 million neurons lining the GI tract — is entirely Vata-governed. In Ayurveda, Vata is called the "king of doshas" — because without movement, nothing else can function.',
    peakTime: '2–6 AM  ·  2–6 PM',
    peakScience: 'Pre-dawn Vata: REM sleep peaks, hippocampal theta waves consolidate memory, norepinephrine drops to its 24-hour nadir then rises sharply. Afternoon Vata: lung vital capacity peaks at 3–4 PM (spirometry). Athletic world records are predominantly broken in the 3–6 PM window (Reilly & Atkinson, 2009). Reaction time, VO₂max, and fine motor coordination are all highest here.',
    governs: ['Nerve impulse conduction (70–120 m/s)', 'Respiratory rhythm (pre-Botzinger complex)', 'Cardiac HIS-Purkinje conduction', 'Peristalsis & gut motility', 'Creative thinking & lateral movement'],
    balance: ['Warm, oily, grounding foods (ghee, sesame, root vegetables)', 'Strict daily schedule (regulates CLOCK/BMAL1 gene)', 'Abhyanga: warm sesame oil massage (reduces cortisol 28%)', '4-7-8 pranayama: activates vagal tone in 5 min', 'Sleep by 10 PM — critical for melatonin onset'],
    imbalance: ['Anxiety & racing thoughts (elevated norepinephrine)', 'Insomnia (nocturnal NE preventing GABA sleep onset)', 'Constipation (weak ENS acetylcholine)', 'Joint dryness (hyaluronic acid depletion)', 'ADHD-like restlessness (dopamine D1/D2 imbalance)'],
  },
  { id: 'pitta', name: 'Pitta', en: 'The Force of Transformation', emoji: '🔥', color: '#fb923c',
    elements: 'Fire + Water',
    tagline: 'Governs all transformation — metabolic, enzymatic, visual, and cognitive.',
    biology: 'Pitta maps to the metabolic-endocrine axis — every biochemical transformation in the body. Food → ATP. Cholesterol → hormones. Xenobiotics → water-soluble metabolites. Gastric HCl, cytochrome P450 liver enzymes, insulin signalling, retinal phototransduction, and core temperature regulation are all Pitta. In endocrinology, Pitta is the HPA (Hypothalamic-Pituitary-Adrenal) axis — the master metabolic controller.',
    peakTime: '10 AM–2 PM  ·  10 PM–2 AM',
    peakScience: 'Midday: gastric acid (HCl) hits its lowest pH (highest acidity) at 12–1 PM via intragastric pH studies. Insulin sensitivity is 30% higher at noon vs evening. Core body temperature peaks at 2–3 PM. Night Pitta: CYP3A4 liver enzymes peak during deep sleep — Phase I & II detoxification at maximum. Growth hormone first secretion pulse occurs. Intestinal epithelial cell turnover accelerates.',
    governs: ['Gastric HCl & pepsin secretion (1.5–3L/day)', 'Bile acid synthesis (liver → 600 ml bile/day)', 'Cytochrome P450 detoxification (60+ enzymes)', 'Core temperature regulation (37°C ± 0.5°C)', 'Visual processing & retinal phototransduction'],
    balance: ['Largest meal at solar noon (30% higher insulin sensitivity)', 'Cooling foods: coconut, cucumber, coriander, mint', 'Never eat when angry (cortisol cuts gut blood flow 40%)', 'Evening moonlight walk (reduces cortisol via visual-SCN pathway)', 'Sheetali breath: lowers tympanic temp 0.3°C in 5 min'],
    imbalance: ['Acid reflux & heartburn (excess HCl beyond LES capacity)', 'Cystic acne (PGE2 excess + androgen → sebaceous hyperactivation)', 'Anger & irritability (elevated cortisol + serotonin deficiency)', 'Loose stools (excess bile acid → osmotic diarrhoea)', 'Premature grey hair (melanocyte H₂O₂ catalase depletion)'],
  },
  { id: 'kapha', name: 'Kapha', en: 'The Force of Structure',      emoji: '🌿', color: '#34d399',
    elements: 'Earth + Water',
    tagline: 'Governs all structure — anabolic, immune, connective tissue, and fluid balance.',
    biology: 'Kapha maps to the anabolic-immune axis. Growth hormone (GH), IGF-1, testosterone, estrogen, and oxytocin are all Kapha hormones. The entire lymphatic system — your body\'s second circulatory system with 600+ lymph nodes — is Kapha. In molecular biology, Kapha is anabolism: the mTOR pathway, collagen synthesis, bone mineralisation, and the secretory IgA mucosal immune system. Kapha is the body\'s investment in tomorrow.',
    peakTime: '6–10 AM  ·  6–10 PM',
    peakScience: 'Morning Kapha: testosterone 20–25% above evening baseline at 7–8 AM (Hyde et al.). Cortisol Awakening Response (CAR) co-rises, triggering an anabolic hormone cascade. Lymphocyte count measurably highest in morning blood draws. Strength training in the Kapha window maximises mTOR (muscle protein synthesis) activation by 23% vs afternoon training. Evening Kapha: parasympathetic shift, melatonin rising, GH first pulse begins with NREM sleep onset.',
    governs: ['Lymphatic immune circulation (600+ nodes, 2–4L lymph/day)', 'Collagen synthesis (types I, II, III — 30% of body protein)', 'Muscle protein synthesis (mTOR, 1.6–2.2 g/kg/day)', 'Synovial fluid (HA matrix, 0.5–4 ml/joint)', 'Hippocampal memory consolidation (BDNF, NREM sleep)'],
    balance: ['Vigorous exercise before 10 AM (AMPK activation, GLUT4 translocation)', 'Light, warm, spiced foods (capsaicin/piperine raise BMR 4–5%)', 'Dry brushing before shower (mechanical lymphatic stimulation)', 'Kapalabhati: 120 rapid exhales/min alkalises blood → sympathetic activation', 'Intermittent fasting 16:8 (initiates autophagy at hour 12–14)'],
    imbalance: ['Lethargy & oversleeping (dopamine deficiency, nucleus accumbens underactivation)', 'Weight gain & insulin resistance (mTORC1 imbalance, adiponectin drops)', 'Congestion & mucus (IL-4/IL-13 goblet cell hypersecretion)', 'Depression & heaviness (SERT dysregulation, low BDNF)', 'Type 2 diabetes risk (chronic insulin receptor downregulation)'],
  },
];

const AGNI_TYPES = [
  { name: 'Sama Agni',    en: 'Balanced Digestive Fire', emoji: '🌟', color: '#34d399',
    desc: 'The optimal state. Food digests fully in 3–4 hours — no bloating, no residue, no heaviness. Produces Ojas (vital essence) from every meal. Balanced cortisol and insulin, stable energy, clear mind. This is the goal of all Ayurvedic dietary intervention.' },
  { name: 'Vishama Agni', en: 'Irregular Fire  ·  Vata',  emoji: '💨', color: '#a78bfa',
    desc: 'Variable, unpredictable hunger. Gas, bloating, constipation alternating with loose stools. Governed by excess Vata dysregulating ENS (enteric nervous system) motility. Stress, irregular meals, and cold/raw food amplify this. Solution: warm cooked food at fixed times.' },
  { name: 'Tikshna Agni', en: 'Sharp/Intense Fire  ·  Pitta', emoji: '🔥', color: '#fb923c',
    desc: 'Excess hunger, acid reflux, heartburn, loose stools, skin inflammation. Gastric HCl overproduction — pH drops below 1.2. Excess Pitta drives hypersecretion of bile and digestive enzymes beyond actual food load. Solution: cooling foods, largest meal at noon, no spicy foods.' },
  { name: 'Manda Agni',   en: 'Sluggish Fire  ·  Kapha',  emoji: '🌀', color: '#60a5fa',
    desc: 'Low appetite, heaviness after meals, slow digestion, mucus production, brain fog. Kapha dampening enzyme output and gut motility — slow transit time > 72 hours. Solution: ginger, black pepper, dry spiced foods, intermittent fasting, vigorous morning exercise.' },
];

const RASAS = [
  { id: 'madhura', name: 'Madhura', en: 'Sweet',      emoji: '🍯', color: '#fbbf24',
    dosha: 'Vata ↓   Pitta ↓   Kapha ↑',
    foods: ['Rice', 'Wheat', 'Milk', 'Ghee', 'Dates', 'Sweet potato', 'Most grains'],
    effect: 'Nourishes all 7 tissues (Dhatus), builds Ojas (vital immune essence), calms the nervous system. The most anabolic taste — increases GH signalling and tissue repair. Best for Vata and Pitta types. In excess (processed sugar): Kapha accumulation, insulin resistance, cellular inflammation.',
  },
  { id: 'amla',    name: 'Amla',    en: 'Sour',       emoji: '🍋', color: '#a3e635',
    dosha: 'Vata ↓   Pitta ↑   Kapha ↑',
    foods: ['Lemon', 'Lime', 'Tamarind', 'Yogurt', 'Amla berry', 'Fermented foods'],
    effect: 'Stimulates gastric enzyme secretion and hydrochloric acid production — directly improves Agni. Organic acids (citric, lactic, acetic) accelerate protein denaturation and iron absorption. Best for Vata. Excess: excess HCl → Pitta aggravation, tooth enamel erosion, hyperacidity.',
  },
  { id: 'lavana',  name: 'Lavana',  en: 'Salty',      emoji: '🧂', color: '#60a5fa',
    dosha: 'Vata ↓   Pitta ↑   Kapha ↑',
    foods: ['Himalayan rock salt', 'Sea vegetables (kelp, nori)', 'Celtic sea salt'],
    effect: 'Enhances taste perception via salt-sensitive taste receptor cells (Type III taste cells). Na+/K+ ATPase requires sodium to maintain the −70 mV membrane potential of every nerve cell in your body. Enhances digestion, softens tissues, and aids mineral absorption. Excess: hypertension, fluid retention, Pitta/Kapha aggravation.',
  },
  { id: 'katu',    name: 'Katu',    en: 'Pungent',    emoji: '🌶️', color: '#f87171',
    dosha: 'Vata ↑   Pitta ↑   Kapha ↓',
    foods: ['Ginger', 'Black pepper', 'Chili', 'Mustard seed', 'Garlic', 'Radish'],
    effect: 'Kindles Agni (digestive fire), clears Kapha stagnation, improves circulation. Capsaicin activates TRPV1 receptors — raises resting metabolic rate 4–5% for 3 hours. Piperine (black pepper) increases bioavailability of curcumin by 2000% and other nutrients significantly. Excess: Vata and Pitta aggravation, inflammation, loose stools.',
  },
  { id: 'tikta',   name: 'Tikta',   en: 'Bitter',     emoji: '🌿', color: '#34d399',
    dosha: 'Vata ↑   Pitta ↓   Kapha ↓',
    foods: ['Turmeric', 'Fenugreek', 'Neem leaf', 'Bitter gourd', 'Dark leafy greens', 'Coffee (moderate)'],
    effect: 'The most detoxifying taste. Curcumin (turmeric) blocks NF-kB signalling — suppressing 160+ inflammatory genes. Bitter compounds stimulate bile production (cholagogue effect), purify blood, and activate liver detox pathways. Best for Pitta and Kapha. Excess: depletes all tissues, aggravates Vata, reduces strength.',
  },
  { id: 'kashaya', name: 'Kashaya', en: 'Astringent', emoji: '🍂', color: '#c084fc',
    dosha: 'Vata ↑   Pitta ↓   Kapha ↓',
    foods: ['Lentils', 'Chickpeas', 'Pomegranate', 'Raw banana', 'Turmeric', 'Green tea'],
    effect: 'Drying, firming, clears excess moisture and Ama (toxic residue). Tannins (the chemical behind astringency) precipitate proteins, tighten mucosal membranes, reduce bleeding, and have significant antimicrobial activity. Powerful Pitta and Kapha reducer. Excess: constipation, Vata dysregulation, dryness in colon.',
  },
];

const VIRUDDHA = [
  { combo: 'Milk + Fish', reason: 'Opposing metabolic signatures — combined Pitta aggravation creates Ama (toxic metabolite complexes) that block lymphatic channels (srotas). Causes skin disorders and inflammatory cascades in classical texts and modern integrative medicine.' },
  { combo: 'Honey + Heat (boiled or cooked)', reason: 'Heated honey undergoes Maillard reaction + hydroxymethylfurfural (HMF) formation above 40°C — creating toxic metabolites. Never heat honey. Add only to warm (not hot) water or food.' },
  { combo: 'Milk + Sour fruits (citrus, berries)', reason: 'Acid instantly curdles casein protein (the dominant milk protein). The curdled aggregate becomes indigestible — coating intestinal villi and dramatically reducing nutrient absorption.' },
  { combo: 'Ghee + Honey in equal parts by weight', reason: 'This exact 1:1 ratio creates lipid-sugar complexes that behave as biological glue — documented in Charaka Samhita as the most referenced incompatibility. Use unequal proportions if combining.' },
  { combo: 'Cold water or drinks with hot meals', reason: 'Rapidly reduces intragastric temperature, inhibiting gastric enzyme activity by 30–40% and slowing HCl production. Food ferments rather than digests — producing gas, Ama, and bloating.' },
  { combo: 'Fruit immediately after a cooked meal', reason: 'Fruit digests in 20–30 minutes; cooked food requires 3–4 hours. Trapped fruit ferments in the warm digestive cavity, producing methane, hydrogen sulfide, and short-chain toxic acids (Ama formation).' },
  { combo: 'Yogurt at night or daily in large quantities', reason: 'Aggravates Kapha during the Kapha evening phase. Casein + lactic acid creates overnight mucus buildup. Fermentation acids impair nocturnal liver detoxification (CYP3A4 peak). Exceptions: small amounts of diluted buttermilk (lassi) are beneficial.' },
];

const PRACTICES = [
  { name: 'Brahma Muhurta', en: 'The Creator\'s Hour', emoji: '🌅', color: '#a78bfa',
    time: '3:40 – 5:20 AM',
    science: 'Melatonin is near zero at this hour. The Cortisol Awakening Response (CAR) begins — a 50–100% cortisol spike primes the HPA axis for the day. Parasympathetic dominance still holds before the sympathetic surge. The pineal gland transitions from deep night mode. Neurologically: the most receptive state for intention, meditation, and deep learning.',
    practice: 'Wake, hydrate with warm water (rehydrates kidneys after 7–8 hours of filtration), sit in stillness or practice pranayama for 20–30 minutes. Intention set during this hour bypasses the reactive cognitive filters of the waking brain — it runs deeper and lasts longer.',
  },
  { name: 'Abhyanga', en: 'Daily Oil Self-Massage', emoji: '🫶', color: '#fb923c',
    time: 'Before morning shower',
    science: 'Warm oil applied to skin activates C-fibre mechanoreceptors → triggers vagal tone → reduces serum cortisol by 28% (Ironson et al., University of Miami). Sesame oil penetrates the dermis and muscular fascia within 20 minutes. Stimulates lymphatic drainage, increases skin serotonin synthesis, and measurably shifts the ANS from sympathetic to parasympathetic dominance.',
    practice: 'Vata: warm sesame or almond oil. Pitta: cooling coconut or sunflower oil. Kapha: light sesame with mustard oil, or dry brushing. Circular strokes on joints (stimulates synovial circulation), long downward strokes on limbs. Allow 15–20 min before a warm shower to maximise absorption.',
  },
  { name: 'Agni Regulation', en: 'Tending the Digestive Fire', emoji: '🔥', color: '#fbbf24',
    time: 'Every meal is an opportunity',
    science: 'Agni is the sum total of digestive fire — governed by Jatharagni (gastric fire), 5 elemental fires, and 7 tissue fires. Gastric HCl peaks at solar noon — the body\'s intelligence aligns maximum digestive capacity with the sun\'s peak. Eating against this circadian rhythm causes chronically low HCl and enzyme output, producing Ama.',
    practice: 'Follow the solar meal schedule: light breakfast by 8 AM, largest meal 12–1 PM (peak Pitta, highest enzyme output), light dinner before 7 PM. Kindle Agni before meals with: a slice of fresh ginger + rock salt + lime. Do not drink cold water with meals. 20-minute post-meal walk stimulates portal blood flow 60%.',
  },
  { name: 'Ojas Cultivation', en: 'Building Vital Essence', emoji: '✨', color: '#34d399',
    time: 'Built through every lifestyle choice',
    science: 'Ojas is the refined metabolic end-product of all 7 tissue (Dhatu) cycles — the body\'s deepest reserve of neuro-immune vitality. Modern equivalents: secretory IgA (sIgA — mucosal immunity, 5g/day production), BDNF (brain-derived neurotrophic factor), oxytocin levels, and telomere length. The IL-10/TGF-beta immune homeostasis axis is Ojas in molecular immunology.',
    practice: 'Built by: deep restorative sleep (stages N3/REM), sattvic whole foods, spiritual practice, loving relationships, time in nature. Depleted by: chronic stress (chronically elevated cortisol degrades telomeres), sleep deprivation, excessive stimulation, processed foods, alcohol. Ashwagandha (reduces cortisol 27.9% — Chandrasekhar et al., 2012) and Shatavari are the most evidence-backed Ojas-building herbs.',
  },
];

const GUNAS = [
  { name: 'Sattva', emoji: '🌟', color: '#fbbf24',
    en: 'Clarity  ·  Intelligence  ·  Purity',
    psychology: 'Prefrontal cortex dominance — executive function, empathy, clear moral reasoning, and creative insight. BDNF (brain-derived neurotrophic factor) production is highest in sattvic neurological states. Default mode network activity is reduced; task-positive network is engaged. Characterised by calm wakefulness, contentment, and perceptual clarity.',
    foods: ['Fresh fruits & vegetables', 'Whole grains', 'Ghee (clarified butter)', 'Raw honey', 'Milk & dairy', 'Nuts & seeds', 'Legumes', 'Mild spices'],
    cultivate: ['Daily meditation (changes prefrontal grey matter density)', 'Yoga asana (lowers inflammatory CRP)', 'Truth-speaking and non-harm (reduces amygdala threat-response)', 'Selfless service (activates default compassion network)', 'Sunrise & nature exposure', 'Early rising and Brahma Muhurta practice'],
  },
  { name: 'Rajas', emoji: '⚡', color: '#fb923c',
    en: 'Action  ·  Passion  ·  Desire',
    psychology: 'Amygdala + dopaminergic prefrontal activation — ambition, desire, competitive drive. Norepinephrine and dopamine are the primary neurotransmitters. In the right measure (moderate Rajas), this creates creativity, productivity, motivation, and achievement. In excess: chronic restlessness, craving, attachment, agitation, and emotional reactivity.',
    foods: ['Onion & garlic', 'Coffee & caffeinated tea', 'Very spicy foods', 'Excess salt', 'Stimulating fermented foods', 'Alcohol in moderate amounts', 'Processed foods with artificial flavors'],
    cultivate: ['Channel Rajas into purposeful creative action', 'Evening walk at sunset (reduces dopamine hyperactivation)', 'Reduce caffeine (eliminates adenosine blockade — restores natural energy cycles)', 'Nadi Shodhana (alternate nostril breathing) before sleep', 'Limit news consumption (reduces amygdala habituation to threat)'],
  },
  { name: 'Tamas', emoji: '🌑', color: '#818cf8',
    en: 'Inertia  ·  Darkness  ·  Stability',
    psychology: 'Default mode network dominance, low dopamine, high serotonin sedation in excess. Necessary for sleep (Tamas provides the biological inertia of rest). In excess: depression, willful ignorance, delusion, addictive compulsion, inability to act. Corresponds to SERT (serotonin transporter) dysregulation and reduced BDNF — the neurobiology of chronic depression and burnout.',
    foods: ['Meat (especially red)', 'Alcohol', 'Processed and packaged foods', 'Stale, reheated, microwaved food', 'Deep-fried foods', 'Excess sugar', 'Overeating'],
    cultivate: ['Morning sunlight exposure (5–10 min on eyes and skin — resets SCN clock)', 'Vigorous cardio (increases BDNF 2–3x — the brain\'s most powerful antidepressant)', 'Cold shower (activates sympathetic → clears Tamasic inertia)', 'Reduce screen time in evening (melatonin suppression is a Tamasic-amplifying signal)', 'Physical decluttering (external order signals the brain to reduce cognitive load)'],
  },
];

const DHATUS = [
  { name: 'Rasa',      en: 'Plasma',            emoji: '💧', color: '#38bdf8', science: 'Blood plasma — 91.5% water, carrying nutrients, hormones, and immune factors. The first tissue produced from digested food. Duration of formation: ~5 days.' },
  { name: 'Rakta',     en: 'Blood / Red cells',  emoji: '🩸', color: '#f87171', science: 'Erythrocytes and haemoglobin — oxygen transport via 280 million Hb molecules per RBC. Produced from Rasa. ~7-day formation cycle.' },
  { name: 'Mamsa',     en: 'Muscle Tissue',      emoji: '💪', color: '#fb923c', science: '640 skeletal muscles — actin/myosin cross-bridge cycling. mTOR signalling drives protein synthesis (1.6–2.2 g/kg/day). Formed from Rakta.' },
  { name: 'Meda',      en: 'Adipose / Fat',       emoji: '🏮', color: '#fbbf24', science: 'White and brown adipose tissue — energy storage (triglycerides, 9 kcal/g), thermal insulation, hormone production (adipokines: leptin, adiponectin). Formed from Mamsa.' },
  { name: 'Asthi',     en: 'Bone',               emoji: '🦴', color: '#a3e635', science: '206 bones — 65% hydroxyapatite mineral + 35% type I collagen. Osteoblast/osteoclast remodelling cycle: 10% of skeleton replaced every year. Formed from Meda.' },
  { name: 'Majja',     en: 'Bone Marrow / Nerves',emoji: '🧠', color: '#a78bfa', science: 'Red marrow produces 200 billion RBCs and 10 billion leukocytes per day. Nerve myelin (70% lipid sheath) is Majja. Yellow marrow stores fat. Formed from Asthi.' },
  { name: 'Shukra',    en: 'Reproductive Tissue', emoji: '✨', color: '#c084fc', science: 'Reproductive essence — concentrated vital energy. Corresponds to testosterone (sperm production, anabolic signalling) and estrogen/progesterone in modern endocrinology. The final, most refined Dhatu. Ojas emerges from Shukra.' },
];

// ─────────────────────────────────────────────────────────────────────────────
const TABS = [
  { id: 'roots',  label: 'Roots',  emoji: '🌍' },
  { id: 'doshas', label: 'Doshas', emoji: '⚗️' },
  { id: 'tastes', label: 'Tastes', emoji: '🍃' },
  { id: 'living', label: 'Living', emoji: '☀️' },
  { id: 'mind',   label: 'Mind',   emoji: '🧠' },
] as const;
type TabId = typeof TABS[number]['id'];

function Div({ label }: { label: string }) {
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 20, marginBottom: 14 }}>
      <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF12' }} />
      <Text style={{ fontSize: 8, fontWeight: '900', color: '#FFFFFF40', letterSpacing: 2 }}>{label}</Text>
      <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF12' }} />
    </View>
  );
}

export default function AyurvedaExplorerScreen() {
  const router = useRouter();
  const [tab, setTab]   = useState<TabId>('roots');
  const [exEl, setExEl] = useState<string | null>(null);
  const [exD,  setExD]  = useState<string | null>(null);
  const [exR,  setExR]  = useState<string | null>(null);
  const [exG,  setExG]  = useState<string | null>(null);

  return (
    <View style={S.screen}>
      <LinearGradient colors={['#05050F', '#080814', '#060612']} style={StyleSheet.absoluteFillObject} />

      <SafeAreaView edges={['top']} style={{ backgroundColor: 'transparent' }}>
        <View style={S.hdr}>
          <TouchableOpacity onPress={() => router.back()} style={S.backBtn} activeOpacity={0.7}>
            <Text style={S.backIcon}>←</Text>
          </TouchableOpacity>
          <View style={{ flex: 1 }}>
            <Text style={S.hdrCap}>ANCIENT SCIENCE  ·  5,000-YEAR SYSTEM</Text>
            <Text style={S.hdrTitle}>Ayurvedic Explorer</Text>
          </View>
        </View>
        <View style={{ height: 1, backgroundColor: '#FFFFFF0C' }} />
      </SafeAreaView>

      <ScrollView horizontal showsHorizontalScrollIndicator={false}
        style={{ flexGrow: 0, borderBottomWidth: 1, borderBottomColor: '#FFFFFF0C' }}
        contentContainerStyle={{ paddingHorizontal: 16, paddingVertical: 10, gap: 8 }}>
        {TABS.map(t => {
          const on = tab === t.id;
          return (
            <TouchableOpacity key={t.id}
              onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); setTab(t.id); }}
              style={[S.tab, on && S.tabOn]} activeOpacity={0.8}>
              <Text style={{ fontSize: 14 }}>{t.emoji}</Text>
              <Text style={[S.tabTxt, on && S.tabTxtOn]}>{t.label}</Text>
            </TouchableOpacity>
          );
        })}
      </ScrollView>

      <ScrollView style={{ flex: 1 }} contentContainerStyle={S.scroll} showsVerticalScrollIndicator={false}>

        {tab === 'roots' && <>
          <LinearGradient colors={['#a78bfa18', '#38bdf808', 'transparent']} style={S.hero}>
            <Text style={S.heroEmoji}>🌿</Text>
            <Text style={S.heroTitle}>Ayurveda</Text>
            <Text style={S.heroSub}>Ayus = Life  ·  Veda = Science</Text>
            <View style={S.heroPill}><Text style={S.heroPillTxt}>THE COMPLETE SCIENCE OF LONGEVITY & CONSCIOUS LIVING</Text></View>
            <Text style={S.heroBody}>A 5,000-year complete system of medicine, lifestyle, and philosophy. Not alternative medicine — a systematic science of body, mind, and consciousness whose core principles modern biology is now independently confirming.</Text>
          </LinearGradient>
          <Div label="PANCHAMAHABHUTA  ·  THE 5 GREAT ELEMENTS" />
          <View style={S.note}><Text style={S.noteTxt}>Everything in the universe — including every cell of your body — is composed of five elemental principles. These are functional categories describing the nature of matter and energy at every scale of existence.</Text></View>
          {ELEMENTS.map(el => {
            const open = exEl === el.id;
            return (
              <TouchableOpacity key={el.id} activeOpacity={0.8}
                onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); setExEl(open ? null : el.id); }}
                style={[S.card, { borderColor: el.color + (open ? '55' : '22') }]}>
                {open && <LinearGradient colors={[el.color + '14', 'transparent']} style={StyleSheet.absoluteFillObject} />}
                <View style={S.cHdr}>
                  <View style={[S.cIcon, { backgroundColor: el.color + '18' }]}><Text style={{ fontSize: 22 }}>{el.emoji}</Text></View>
                  <View style={{ flex: 1, gap: 4 }}>
                    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                      <Text style={[S.cTitle, { color: el.color }]}>{el.name}</Text>
                      <Text style={S.cSub}>{el.en}</Text>
                    </View>
                    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 4 }}>
                      {el.qualities.map(q => <View key={q} style={[S.chip, { borderColor: el.color + '35', backgroundColor: el.color + '10' }]}><Text style={[S.chipTxt, { color: el.color + 'CC' }]}>{q}</Text></View>)}
                    </View>
                  </View>
                  <Text style={S.chev}>{open ? '▲' : '▼'}</Text>
                </View>
                {open && <View style={S.cBody}>
                  <Text style={S.bodyTxt}>{el.body}</Text>
                  <View style={[S.sciBox, { borderColor: el.color + '30', backgroundColor: el.color + '0A' }]}>
                    <Text style={[S.sciLbl, { color: el.color }]}>🔬  BIOLOGY  ·  MODERN SCIENCE</Text>
                    <Text style={S.sciTxt}>{el.science}</Text>
                  </View>
                </View>}
              </TouchableOpacity>
            );
          })}
          <View style={[S.note, { marginTop: 6 }]}><Text style={S.noteTxt}>✦  Every food, herb, season, organ, emotion, and treatment is classified by its elemental composition — a functional taxonomy forming the complete diagnostic logic of Ayurveda.</Text></View>
          <View style={{ height: 16 }} />
        </>}

        {tab === 'doshas' && <>
          <LinearGradient colors={['#a78bfa12', 'transparent']} style={S.hero}>
            <Text style={S.heroEmoji}>⚗️</Text>
            <Text style={S.heroTitle}>Tridosha</Text>
            <Text style={S.heroSub}>The Three Bio-Forces</Text>
            <Text style={S.heroBody}>The three doshas are biological intelligences governing every physiological process. Not diseases or personality types — functional categories explaining why different people need different diets, sleep schedules, and medicines. Modern chronobiology now maps precisely onto this 5,000-year framework.</Text>
          </LinearGradient>
          <Div label="THREE BIOLOGICAL FORCES  ·  CHRONOBIOLOGY" />
          {DOSHAS.map(d => {
            const open = exD === d.id;
            return (
              <TouchableOpacity key={d.id} activeOpacity={0.85}
                onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); setExD(open ? null : d.id); }}
                style={[S.card, { borderColor: d.color + (open ? '55' : '28') }]}>
                {open && <LinearGradient colors={[d.color + '18', d.color + '05', 'transparent']} style={StyleSheet.absoluteFillObject} />}
                <View style={S.cHdr}>
                  <View style={[S.cIcon, { backgroundColor: d.color + '20' }]}><Text style={{ fontSize: 24 }}>{d.emoji}</Text></View>
                  <View style={{ flex: 1 }}>
                    <Text style={[S.cTitle, { color: d.color }]}>{d.name}</Text>
                    <Text style={S.cSub}>{d.en}</Text>
                    <Text style={{ fontSize: 10, color: d.color + '80', fontWeight: '700', marginTop: 2 }}>{d.elements}</Text>
                  </View>
                  <View style={[S.peakBadge, { borderColor: d.color + '40', backgroundColor: d.color + '12' }]}>
                    <Text style={[S.peakLabel, { color: d.color }]}>PEAK</Text>
                    <Text style={{ fontSize: 8, color: d.color + '90', fontWeight: '700' }}>{d.peakTime.split('  ·  ')[0]}</Text>
                  </View>
                </View>
                {!open && <Text style={[S.tagline, { color: d.color + 'AA' }]}>{d.tagline}</Text>}
                {open && <View style={S.cBody}>
                  <Text style={S.bodyTxt}>{d.biology}</Text>
                  <View style={[S.sciBox, { borderColor: d.color + '30', backgroundColor: d.color + '0A', marginTop: 12 }]}>
                    <Text style={[S.sciLbl, { color: d.color }]}>⏱  CIRCADIAN PEAK  ·  {d.peakTime}</Text>
                    <Text style={S.sciTxt}>{d.peakScience}</Text>
                  </View>
                  <Text style={[S.microLbl, { color: d.color, marginTop: 14 }]}>⚡  GOVERNS</Text>
                  {d.governs.map((g, i) => (
                    <View key={i} style={[S.listRow, { borderColor: d.color + '20' }]}>
                      <View style={[S.dot, { backgroundColor: d.color }]} /><Text style={S.listTxt}>{g}</Text>
                    </View>
                  ))}
                  <Text style={[S.microLbl, { color: '#34d399', marginTop: 14 }]}>✓  BALANCE PRACTICES</Text>
                  {d.balance.map((b, i) => (
                    <View key={i} style={S.checkRow}>
                      <Text style={{ color: '#34d399', fontSize: 12, fontWeight: '900' }}>✓</Text><Text style={S.listTxt}>{b}</Text>
                    </View>
                  ))}
                  <Text style={[S.microLbl, { color: '#f87171', marginTop: 14 }]}>⚠  SIGNS OF EXCESS</Text>
                  {d.imbalance.map((im, i) => (
                    <View key={i} style={S.checkRow}>
                      <Text style={{ color: '#f87171', fontSize: 12, fontWeight: '900' }}>✕</Text><Text style={S.listTxt}>{im}</Text>
                    </View>
                  ))}
                </View>}
              </TouchableOpacity>
            );
          })}
          <View style={S.footCard}>
            <Text style={S.footTitle}>☀️  Ayurveda = Chronobiology</Text>
            <Text style={S.footBody}>The 3-Dosha system is a 5,000-year circadian biology framework mapping the body's 24-hour hormonal oscillations to three elemental archetypes. The Nobel Prize in Medicine 2017 (Hall, Rosbash, Young) confirmed CLOCK/BMAL1 genes run in every cell — matching Vata/Pitta/Kapha periods with remarkable precision.</Text>
          </View>
          <View style={{ height: 16 }} />
        </>}

        {tab === 'tastes' && <>
          <LinearGradient colors={['#34d39912', 'transparent']} style={S.hero}>
            <Text style={S.heroEmoji}>🍃</Text>
            <Text style={S.heroTitle}>Shad Rasa</Text>
            <Text style={S.heroSub}>The Six Tastes</Text>
            <Text style={S.heroBody}>Ayurveda recognises six distinct tastes — each with specific effects on the doshas, tissues, and nervous system. The ideal meal contains all six. Taste is the body's first communication with food, triggering enzyme, hormone, and neurotransmitter cascades before digestion even begins.</Text>
          </LinearGradient>
          <Div label="SHAD RASA  ·  SIX TASTES  ·  DOSHA INTELLIGENCE" />
          {RASAS.map(r => {
            const open = exR === r.id;
            return (
              <TouchableOpacity key={r.id} activeOpacity={0.8}
                onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); setExR(open ? null : r.id); }}
                style={[S.card, { borderColor: r.color + (open ? '55' : '28') }]}>
                {open && <LinearGradient colors={[r.color + '14', 'transparent']} style={StyleSheet.absoluteFillObject} />}
                <View style={S.cHdr}>
                  <View style={[S.cIcon, { backgroundColor: r.color + '18' }]}><Text style={{ fontSize: 22 }}>{r.emoji}</Text></View>
                  <View style={{ flex: 1, gap: 4 }}>
                    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                      <Text style={[S.cTitle, { color: r.color }]}>{r.name}</Text>
                      <Text style={S.cSub}>{r.en}</Text>
                    </View>
                    <View style={[S.doshaTag, { borderColor: r.color + '35', backgroundColor: r.color + '10' }]}>
                      <Text style={[S.doshaTagTxt, { color: r.color }]}>{r.dosha}</Text>
                    </View>
                  </View>
                  <Text style={S.chev}>{open ? '▲' : '▼'}</Text>
                </View>
                {open && <View style={S.cBody}>
                  <Text style={S.bodyTxt}>{r.effect}</Text>
                  <Text style={[S.microLbl, { color: r.color, marginTop: 10 }]}>KEY FOODS</Text>
                  <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 }}>
                    {r.foods.map(f => <View key={f} style={[S.fChip, { borderColor: r.color + '40', backgroundColor: r.color + '14' }]}><Text style={[S.fChipTxt, { color: r.color }]}>{f}</Text></View>)}
                  </View>
                </View>}
              </TouchableOpacity>
            );
          })}
          <Div label="VIRUDDHA AHARA  ·  INCOMPATIBLE COMBINATIONS" />
          <View style={S.note}><Text style={S.noteTxt}>These combinations create Ama — undigested toxic residue in the channels. Ama is considered the root cause of all disease in classical Ayurveda. These are not superstitions — the molecular mechanisms are now understood.</Text></View>
          {VIRUDDHA.map((v, i) => (
            <View key={i} style={S.vCard}>
              <View style={S.vX}><Text style={{ color: '#ef4444', fontSize: 13, fontWeight: '900' }}>✕</Text></View>
              <View style={{ flex: 1 }}>
                <Text style={S.vCombo}>{v.combo}</Text>
                <Text style={S.vReason}>{v.reason}</Text>
              </View>
            </View>
          ))}
          <View style={{ height: 16 }} />
        </>}

        {tab === 'living' && <>
          <LinearGradient colors={['#fbbf2412', 'transparent']} style={S.hero}>
            <Text style={S.heroEmoji}>☀️</Text>
            <Text style={S.heroTitle}>Dinacharya</Text>
            <Text style={S.heroSub}>The Daily Living Science</Text>
            <Text style={S.heroBody}>A precise 24-hour protocol synchronising human biology with solar and lunar cycles. Modern chronobiology confirms CLOCK/BMAL1 molecular clock genes in every cell run on a 24-hour oscillation requiring specific environmental cues to remain calibrated.</Text>
          </LinearGradient>
          <Div label="CORE PRACTICES  ·  EVIDENCE-BASED PROTOCOLS" />
          {PRACTICES.map((p, i) => (
            <View key={i} style={[S.card, { borderColor: p.color + '35' }]}>
              <LinearGradient colors={[p.color + '12', 'transparent']} style={StyleSheet.absoluteFillObject} />
              <View style={S.cHdr}>
                <View style={[S.cIcon, { backgroundColor: p.color + '20' }]}><Text style={{ fontSize: 22 }}>{p.emoji}</Text></View>
                <View style={{ flex: 1 }}>
                  <Text style={[S.cTitle, { color: p.color }]}>{p.name}</Text>
                  <Text style={S.cSub}>{p.en}</Text>
                  <Text style={{ fontSize: 9, color: p.color + '80', fontWeight: '700', marginTop: 2 }}>⏱  {p.time}</Text>
                </View>
              </View>
              <View style={S.cBody}>
                <View style={[S.sciBox, { borderColor: p.color + '30', backgroundColor: p.color + '0A', marginBottom: 10 }]}>
                  <Text style={[S.sciLbl, { color: p.color }]}>🔬  SCIENCE</Text>
                  <Text style={S.sciTxt}>{p.science}</Text>
                </View>
                <View style={[S.practBox, { borderColor: p.color + '28' }]}>
                  <Text style={[S.sciLbl, { color: p.color }]}>✦  PRACTICE</Text>
                  <Text style={S.sciTxt}>{p.practice}</Text>
                </View>
              </View>
            </View>
          ))}
          <Div label="AGNI  ·  THE FOUR TYPES OF DIGESTIVE FIRE" />
          <View style={S.note}><Text style={S.noteTxt}>Agni — digestive fire — is the central concept of Ayurvedic health. Virtually every disease begins with impaired Agni producing Ama. The goal of all Ayurvedic treatment is to restore and maintain Sama (balanced) Agni.</Text></View>
          {AGNI_TYPES.map((a, i) => (
            <View key={i} style={[S.agniCard, { borderColor: a.color + '35', backgroundColor: a.color + '08' }]}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                <Text style={{ fontSize: 24 }}>{a.emoji}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={[S.agniName, { color: a.color }]}>{a.name}</Text>
                  <Text style={S.agniEn}>{a.en}</Text>
                </View>
              </View>
              <Text style={S.agniDesc}>{a.desc}</Text>
            </View>
          ))}
          <Div label="MEAL TIMING  ·  SOLAR EATING SCHEDULE" />
          {([
            { time: '7–8 AM', label: 'Breakfast', emoji: '🌅', color: '#fbbf24', advice: 'Light and warm. Kapha is active — eat lightly to avoid stagnation. Fruit, warm porridge, or herbal tea. Agni is still warming up — avoid heavy meals in the morning.' },
            { time: '12–1 PM', label: 'Main Meal', emoji: '☀️', color: '#fb923c', advice: 'Your largest, most complex meal. Pitta peak — gastric HCl at lowest pH, insulin sensitivity 30% higher than evening, enzyme output maximised. Cooked grains, dal, vegetables, ghee. Eat until 75% full.' },
            { time: 'Before 7 PM', label: 'Light Dinner', emoji: '🌆', color: '#a78bfa', advice: 'Light and early. Agni is declining. Soups, steamed vegetables, khichdi. Never eat within 2 hours of sleep — a full stomach at bedtime sabotages overnight liver detoxification (CYP3A4 peak).' },
          ] as const).map((t, i) => (
            <View key={i} style={[S.card, { borderColor: t.color + '35' }]}>
              <LinearGradient colors={[t.color + '10', 'transparent']} style={StyleSheet.absoluteFillObject} />
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, paddingBottom: 8 }}>
                <Text style={{ fontSize: 28 }}>{t.emoji}</Text>
                <View><Text style={[S.cTitle, { color: t.color }]}>{t.label}</Text><Text style={S.cSub}>{t.time}</Text></View>
              </View>
              <Text style={[S.bodyTxt, { paddingHorizontal: 14, paddingBottom: 14 }]}>{t.advice}</Text>
            </View>
          ))}
          <View style={{ height: 16 }} />
        </>}

        {tab === 'mind' && <>
          <LinearGradient colors={['#a78bfa12', 'transparent']} style={S.hero}>
            <Text style={S.heroEmoji}>🧠</Text>
            <Text style={S.heroTitle}>Mind & Consciousness</Text>
            <Text style={S.heroSub}>Trigunas  ·  Sapta Dhatu  ·  Ojas</Text>
            <Text style={S.heroBody}>Ayurveda considers mind and body inseparable — the same elemental forces governing your physiology also govern your psychology. The three Gunas are the psychological equivalents of the doshas — the three fundamental qualities of all mental experience.</Text>
          </LinearGradient>
          <Div label="TRIGUNA  ·  THE THREE QUALITIES OF MIND" />
          {GUNAS.map(g => {
            const open = exG === g.name;
            return (
              <TouchableOpacity key={g.name} activeOpacity={0.8}
                onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); setExG(open ? null : g.name); }}
                style={[S.card, { borderColor: g.color + (open ? '55' : '28') }]}>
                {open && <LinearGradient colors={[g.color + '14', 'transparent']} style={StyleSheet.absoluteFillObject} />}
                <View style={S.cHdr}>
                  <View style={[S.cIcon, { backgroundColor: g.color + '20' }]}><Text style={{ fontSize: 24 }}>{g.emoji}</Text></View>
                  <View style={{ flex: 1 }}>
                    <Text style={[S.cTitle, { color: g.color }]}>{g.name}</Text>
                    <Text style={S.cSub}>{g.en}</Text>
                  </View>
                  <Text style={S.chev}>{open ? '▲' : '▼'}</Text>
                </View>
                {open && <View style={S.cBody}>
                  <View style={[S.sciBox, { borderColor: g.color + '30', backgroundColor: g.color + '0A' }]}>
                    <Text style={[S.sciLbl, { color: g.color }]}>🧠  NEUROSCIENCE</Text>
                    <Text style={S.sciTxt}>{g.psychology}</Text>
                  </View>
                  <Text style={[S.microLbl, { color: g.color, marginTop: 12 }]}>FOODS THAT INCREASE</Text>
                  <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 }}>
                    {g.foods.map(f => <View key={f} style={[S.fChip, { borderColor: g.color + '40', backgroundColor: g.color + '14' }]}><Text style={[S.fChipTxt, { color: g.color }]}>{f}</Text></View>)}
                  </View>
                  <Text style={[S.microLbl, { color: g.color, marginTop: 12 }]}>HOW TO CULTIVATE / REDUCE</Text>
                  {g.cultivate.map((c, i) => (
                    <View key={i} style={S.checkRow}>
                      <View style={[S.dot, { backgroundColor: g.color }]} /><Text style={S.listTxt}>{c}</Text>
                    </View>
                  ))}
                </View>}
              </TouchableOpacity>
            );
          })}
          <Div label="SAPTA DHATU  ·  THE SEVEN BODY TISSUES" />
          <View style={S.note}><Text style={S.noteTxt}>Seven tissue systems arranged in metabolic sequence — each Dhatu produced from the previous one via enzymatic transformation. Deficiency at any level cascades downstream. Each Dhatu has its own Agni (tissue fire) and produces refined essence that feeds the next.</Text></View>
          {DHATUS.map((d, i) => (
            <View key={d.name} style={[S.dhatu, { borderColor: d.color + '30' }]}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                <View style={[S.dNum, { backgroundColor: d.color + '20', borderColor: d.color + '40' }]}>
                  <Text style={[S.dNumTxt, { color: d.color }]}>{i + 1}</Text>
                </View>
                <Text style={{ fontSize: 20 }}>{d.emoji}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={[S.dName, { color: d.color }]}>{d.name}</Text>
                  <Text style={S.dEn}>{d.en}</Text>
                </View>
                {i < DHATUS.length - 1 && <Text style={{ color: '#FFFFFF25', fontSize: 10 }}>→ {DHATUS[i + 1].name}</Text>}
              </View>
              <Text style={S.dSci}>{d.science}</Text>
            </View>
          ))}
          <View style={S.footCard}>
            <Text style={S.footTitle}>✨  The Ultimate Goal: Ojas</Text>
            <Text style={S.footBody}>{`Ojas — the refined essence distilled through all seven Dhatu cycles — is Ayurveda's concept of biological sovereignty. When digestion is perfect and lifestyle disciplined, the body produces Ojas: luminous, stable, deeply immune neuro-vital essence.\n\nModern equivalents: secretory IgA (mucosal immunity), BDNF, oxytocin, telomere integrity, and mitochondrial efficiency.\n\nA person with abundant Ojas has radiant skin, calm strong immunity, deep stable sleep, unwavering mental clarity, and emotional equanimity. This is the goal of Ayurvedic living.`}</Text>
          </View>
          <View style={{ height: 16 }} />
        </>}

      </ScrollView>
    </View>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────
const S = StyleSheet.create({
  screen:    { flex: 1, backgroundColor: '#05050F' },
  hdr:       { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingTop: 12, paddingBottom: 12, gap: 12 },
  backBtn:   { width: 38, height: 38, borderRadius: 19, backgroundColor: '#FFFFFF0E', borderWidth: 1, borderColor: '#FFFFFF20', alignItems: 'center', justifyContent: 'center' },
  backIcon:  { fontSize: 20, color: '#FFFFFFEE', fontWeight: '200' },
  hdrCap:    { fontSize: 8, fontWeight: '900', color: '#FFFFFF45', letterSpacing: 2, marginBottom: 2 },
  hdrTitle:  { fontSize: 22, fontWeight: '900', color: '#FFFFFFEE', letterSpacing: -0.5 },

  tab:       { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20, borderWidth: 1, borderColor: '#FFFFFF10', backgroundColor: '#FFFFFF05' },
  tabOn:     { backgroundColor: '#34d39918', borderColor: '#34d39945' },
  tabTxt:    { fontSize: 12, fontWeight: '700', color: '#FFFFFF55' },
  tabTxtOn:  { color: '#34d399', fontWeight: '900' },

  scroll:    { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 40 },

  hero:        { borderRadius: 22, padding: 22, marginBottom: 4, alignItems: 'center', borderWidth: 1, borderColor: '#FFFFFF0A', overflow: 'hidden' },
  heroEmoji:   { fontSize: 44, marginBottom: 8 },
  heroTitle:   { fontSize: 30, fontWeight: '900', color: '#FFFFFFEE', letterSpacing: -0.5, marginBottom: 4 },
  heroSub:     { fontSize: 12, color: '#FFFFFF55', fontWeight: '600', marginBottom: 12, letterSpacing: 0.4 },
  heroPill:    { borderWidth: 1, borderColor: '#FFFFFF18', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 5, marginBottom: 12, backgroundColor: '#FFFFFF06' },
  heroPillTxt: { fontSize: 8, fontWeight: '900', color: '#FFFFFF60', letterSpacing: 1.4 },
  heroBody:    { fontSize: 13, color: '#FFFFFF80', lineHeight: 20, textAlign: 'center' },

  note:    { borderRadius: 14, borderWidth: 1, borderColor: '#FFFFFF10', backgroundColor: '#FFFFFF05', padding: 14, marginBottom: 14 },
  noteTxt: { fontSize: 12, color: '#FFFFFF65', lineHeight: 19 },

  card:   { borderRadius: 18, borderWidth: 1, backgroundColor: '#FFFFFF04', marginBottom: 10, overflow: 'hidden' },
  cHdr:   { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14 },
  cIcon:  { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  cTitle: { fontSize: 17, fontWeight: '900' },
  cSub:   { fontSize: 11, color: '#FFFFFF50', fontWeight: '600' },
  cBody:  { paddingHorizontal: 14, paddingBottom: 14, borderTopWidth: 1, borderTopColor: '#FFFFFF0C' },
  bodyTxt:{ fontSize: 13, color: '#FFFFFFBB', lineHeight: 20, paddingTop: 12 },
  chev:   { fontSize: 11, color: '#FFFFFF40' },

  sciBox:   { borderRadius: 12, borderWidth: 1, padding: 12, marginTop: 4 },
  sciLbl:   { fontSize: 8, fontWeight: '900', letterSpacing: 1.4, marginBottom: 6 },
  sciTxt:   { fontSize: 12, color: '#FFFFFF99', lineHeight: 19 },
  practBox: { borderRadius: 12, borderWidth: 1, borderColor: '#FFFFFF12', padding: 12, backgroundColor: '#FFFFFF04' },

  chip:    { borderRadius: 20, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 2 },
  chipTxt: { fontSize: 9, fontWeight: '700' },

  microLbl: { fontSize: 8, fontWeight: '900', letterSpacing: 1.6, marginBottom: 4 },
  listRow:  { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: '#FFFFFF08' },
  dot:      { width: 5, height: 5, borderRadius: 3, marginTop: 6, flexShrink: 0 },
  listTxt:  { fontSize: 12, color: '#FFFFFFAA', lineHeight: 18, flex: 1 },
  checkRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingVertical: 4 },

  tagline:    { fontSize: 11, paddingHorizontal: 14, paddingBottom: 12, fontStyle: 'italic', lineHeight: 16 },
  peakBadge:  { borderWidth: 1, borderRadius: 10, padding: 6, alignItems: 'center', gap: 2 },
  peakLabel:  { fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  doshaTag:   { borderRadius: 20, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 2, alignSelf: 'flex-start' },
  doshaTagTxt:{ fontSize: 10, fontWeight: '800' },

  fChip:    { borderRadius: 20, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 4 },
  fChipTxt: { fontSize: 11, fontWeight: '700' },

  vCard:   { flexDirection: 'row', gap: 12, backgroundColor: '#ef444408', borderRadius: 14, borderWidth: 1, borderColor: '#ef444428', padding: 14, marginBottom: 8 },
  vX:      { width: 26, height: 26, borderRadius: 13, backgroundColor: '#ef444420', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 2 },
  vCombo:  { fontSize: 14, fontWeight: '800', color: '#FFFFFFEE', marginBottom: 4 },
  vReason: { fontSize: 12, color: '#FFFFFF75', lineHeight: 18 },

  agniCard: { borderRadius: 16, borderWidth: 1, padding: 14, marginBottom: 8 },
  agniName: { fontSize: 15, fontWeight: '900' },
  agniEn:   { fontSize: 11, color: '#FFFFFF50', fontWeight: '600', marginTop: 1 },
  agniDesc: { fontSize: 12, color: '#FFFFFFAA', lineHeight: 19 },

  dhatu:   { borderRadius: 14, borderWidth: 1, backgroundColor: '#FFFFFF04', padding: 12, marginBottom: 8 },
  dNum:    { width: 22, height: 22, borderRadius: 11, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  dNumTxt: { fontSize: 10, fontWeight: '900' },
  dName:   { fontSize: 14, fontWeight: '900' },
  dEn:     { fontSize: 11, color: '#FFFFFF50', fontWeight: '600' },
  dSci:    { fontSize: 11, color: '#FFFFFF75', lineHeight: 17, marginTop: 4 },

  footCard:  { borderRadius: 18, borderWidth: 1, borderColor: '#FFFFFF10', backgroundColor: '#FFFFFF04', padding: 18, marginTop: 16 },
  footTitle: { fontSize: 16, fontWeight: '900', color: '#FFFFFFEE', marginBottom: 10 },
  footBody:  { fontSize: 12, color: '#FFFFFF70', lineHeight: 20 },
});

