import React, { useState } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, StatusBar, SafeAreaView,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';

// ── Full scientific dosha data ─────────────────────────────────────────────
const DOSHAS_FULL = {
  vata: {
    name: 'Vata', sanskrit: 'वात', devanagari: 'वायु + आकाश',
    elements: 'Air + Space', elementEquation: 'AIR  +  SPACE  =  MOVEMENT',
    westernSystem: 'Sympathetic Nervous System · Peripheral Nervous System · Enteric Nervous System',
    color: '#a78bfa', emoji: '🌬️',
    tagline: 'The principle of movement & neural electricity',
    biology: 'Vata maps to the Autonomic Nervous System — specifically the sympathetic (fight-or-flight) branch and the entire peripheral nervous system. Every action potential (70 mV impulse) traveling at 70–120 m/s through myelinated nerve fibres is pure Vata. The enteric nervous system ("gut brain") — 500 million neurons lining the GI tract — is entirely Vata-governed.',
    elementAir: {
      title: 'Air (Vayu) in the Body',
      body: 'Alveolar gas exchange (O₂/CO₂), electrochemical gradients across cell membranes, and electromagnetic fields generated by neural firing. Nerve action potentials are literally electrical air — charge moving through biological space.',
      molecules: 'pO₂ · CO₂ respiratory quotient · Na⁺/K⁺ ATPase gradient · Action potential (−70 mV resting)',
    },
    elementSpace: {
      title: 'Space (Akasha) in the Body',
      body: 'Synaptic clefts (20 nm gaps between neurons where neurotransmitters travel), hollow body channels (arteries, bronchi, gut lumen), extracellular matrix, and the quantum electromagnetic field generated by 86 billion neurons firing simultaneously.',
      molecules: 'Synaptic vesicle release zones · Extracellular matrix (ECM) · Interstitial space (15L of body fluid)',
    },
    neuro: [
      { name: 'Dopamine', role: 'Movement initiation, reward motivation, creative drive, prefrontal focus' },
      { name: 'Norepinephrine', role: 'Sympathetic alertness, attention regulation, fight-or-flight activation' },
      { name: 'Acetylcholine', role: 'Nerve-muscle junction (NMJ), hippocampal memory encoding, REM sleep' },
      { name: 'GABA', role: 'Inhibitory counterbalance — prevents Vata hyperactivation and anxiety' },
    ],
    peakWindows: [
      { time: 'Pre-Dawn  2–6 AM', icon: '🌙', science: 'REM sleep peaks — hippocampal theta waves consolidate memory. Norepinephrine drops to its 24-hour nadir then begins rising. Enteric nervous system (ENS) microbiome circadian clock activates gut repair.' },
      { time: 'Afternoon  2–6 PM', icon: '✍️', science: 'Spirometry confirms peak lung vital capacity at 3–4 PM. Plasma dopamine & norepinephrine measurably elevated. Reaction time is at its fastest. Athletic world records are predominantly broken in this window (Reilly & Atkinson, 2009).' },
    ],
    peakFact: 'Plasma catecholamines (adrenaline + noradrenaline) follow a strict circadian pattern confirmed by chrono-pharmacology. Lung vital capacity peaks at 3–4 PM (spirometry). Reaction time, fine motor coordination and VO₂max are all highest in the afternoon Vata window.',
    functions: [
      { name: 'Nerve conduction velocity', detail: '70–120 m/s in myelinated Aα fibres · 0.5 m/s in unmyelinated C fibres', icon: '⚡' },
      { name: 'Respiratory rhythm', detail: '12–20 breaths/min controlled by pre-Bötzinger complex in brainstem', icon: '🫁' },
      { name: 'Cardiac HIS-Purkinje', detail: 'Electrical conduction system — SA node → AV node → 70 bpm rhythm', icon: '❤️' },
      { name: 'Gut motility (peristalsis)', detail: 'Migrating motor complex — 1–3 cm/s waves in small intestine', icon: '🌀' },
      { name: 'Working memory speed', detail: 'Prefrontal cortex γ-oscillations (40 Hz) — 100 ms neural processing loops', icon: '🧠' },
      { name: 'Motor coordination', detail: 'Cerebellum timing + basal ganglia rhythm — 10 ms precision', icon: '🤸' },
    ],
    doNow: ['Slow pranayama (4-7-8 breathing)', 'Warm sesame oil Abhyanga self-massage', 'Fixed sleep/wake schedule', 'Warm cooked grounding foods', 'Barefoot walk on earth (earthing)', 'Journal or sit in stillness'],
    avoid: ['Cold raw foods (amplify Vata kinetics)', 'Irregular schedule (dysregulates CLOCK gene)', 'Excess caffeine (spikes catecholamines)', 'Multitasking (fragmenting dopamine loops)', 'Screen exposure before sleep (blocks melatonin)'],
    imbalance: [
      { symptom: 'Anxiety & racing thoughts', science: 'Excess sympathetic tone — chronically elevated norepinephrine & CRH (corticotropin-releasing hormone)' },
      { symptom: 'Insomnia', science: 'Nocturnal norepinephrine prevents GABA-mediated sleep onset — HRV (heart rate variability) remains high' },
      { symptom: 'Constipation', science: 'Weakened peristaltic waves — low acetylcholine in enteric nervous system (ENS)' },
      { symptom: 'Joint cracking & dryness', science: 'Reduced synovial fluid (hyaluronic acid depletion) — mechanical joint friction increases' },
      { symptom: 'Restlessness, ADHD-like symptoms', science: 'Dopamine dysregulation — prefrontal cortex D1-receptor underactivation, excess D2 in striatum' },
    ],
    balance: [
      { practice: 'Warm cooked, slightly oily foods', science: 'Boosts intestinal serotonin (5-HT) → vagal signalling → parasympathetic grounding' },
      { practice: 'Fixed sleep/wake schedule', science: 'Regulates cortisol awakening response (CAR) and CLOCK/BMAL1 gene expression' },
      { practice: 'Abhyanga — warm sesame oil massage', science: 'Stimulates vagal tone → reduces cortisol 28% (Ironson et al.) → activates parasympathetic' },
      { practice: '4-7-8 breathing technique', science: 'Activates ventral vagal complex → improves HRV (heart rate variability) — measurable within 5 minutes' },
      { practice: 'Barefoot earthing on soil/grass', science: 'Transfers free electrons from earth → reduces inflammatory CRP markers (Chevalier et al., 2012)' },
    ],
  },

  pitta: {
    name: 'Pitta', sanskrit: 'पित्त', devanagari: 'अग्नि + जल',
    elements: 'Fire + Water', elementEquation: 'FIRE  +  WATER  =  METABOLISM',
    westernSystem: 'HPA Axis · Hepatic Metabolism · Digestive Enzyme System · Thermogenetic System',
    color: '#fb923c', emoji: '🔥',
    tagline: 'The principle of metabolic fire & biochemical transformation',
    biology: 'Pitta maps to the metabolic-endocrine axis — every biochemical transformation: food → ATP, cholesterol → hormones, xenobiotics → water-soluble metabolites. Cytochrome P450 enzymes (liver detox), gastric acid secretion, insulin signalling, and core temperature regulation are all Pitta. In endocrinology, Pitta is the HPA (Hypothalamic-Pituitary-Adrenal) axis.',
    elementAir: {
      title: 'Fire (Agni) in the Body',
      body: 'Oxidative phosphorylation in mitochondria — electrons cascade through Complexes I–IV of the electron transport chain, producing 32 ATP per glucose molecule. This is literally fire at the cellular level: controlled combustion generating heat and energy.',
      molecules: 'ATP synthase (Complex V) · NADH/FADH₂ electron carriers · Reactive oxygen species (ROS) · UCP1 (thermogenin)',
    },
    elementSpace: {
      title: 'Water (Jala) in the Body',
      body: 'All enzymatic reactions occur in aqueous medium — enzymes are functionless without water. Bile is 95% water. Blood plasma is 92% water. Hydrolysis reactions (breaking bonds with water) power digestion. Every Pitta transformation is water-mediated.',
      molecules: 'Intracellular water 67% · Plasma (91.5% H₂O) · Enzymatic hydrolysis · pH buffering (bicarbonate system)',
    },
    neuro: [
      { name: 'Cortisol', role: 'Energy mobilisation, anti-inflammatory, circadian rhythm driver, cognitive sharpness' },
      { name: 'Insulin', role: 'Glucose uptake by cells, anabolic signalling, metabolic gatekeeper' },
      { name: 'Thyroid (T3/T4)', role: 'Sets basal metabolic rate, thermogenesis, protein synthesis rate' },
      { name: 'HCl & Pepsin', role: 'Protein denaturation at pH 1.5–3.5, vitamin B12 activation via intrinsic factor' },
    ],
    peakWindows: [
      { time: 'Midday  10 AM–2 PM', icon: '☀️', science: 'Gastric acid (HCl) hits lowest pH (highest acidity) at 12–1 PM — confirmed by intragastric pH studies. Insulin sensitivity is 30% higher at noon vs evening. Core body temperature peaks at 2–3 PM. Cognitive processing (IQ-task performance) peaks in this window.' },
      { time: 'Night  10 PM–2 AM', icon: '🌙', science: 'Liver Cytochrome P450 3A4 enzymes peak in hepatocytes during deep sleep — Phase I & II detoxification at maximum. Growth hormone first secretion pulse occurs. Intestinal epithelial cell turnover accelerates.' },
    ],
    peakFact: 'Gastric acid peaks at solar noon — intragastric pH studies confirm pH 1.5 at 12–1 PM. Insulin sensitivity 30% higher at midday vs evening. Core temperature peaks at 2–3 PM. Night Pitta: CYP3A4 (the enzyme metabolising 50% of pharmaceuticals) peaks during deep sleep.',
    functions: [
      { name: 'HCl & Pepsin secretion', detail: 'Parietal cells secrete 1.5–3L HCl/day · gastric pH 1.5–3.5', icon: '🧪' },
      { name: 'Bile acid synthesis', detail: 'Liver converts cholesterol → cholic acid · 600 ml bile/day', icon: '💛' },
      { name: 'Cytochrome P450 detox', detail: 'Phase I (oxidation) + Phase II (conjugation) · 60 CYP enzymes', icon: '🔄' },
      { name: 'Core temperature regulation', detail: 'Hypothalamic set-point: 37°C ± 0.5°C · circadian variation 36.5–37.5°C', icon: '🌡️' },
      { name: 'Retinal phototransduction', detail: 'Photoreceptors process 10⁷ photons/sec · rhodopsin regeneration', icon: '👁️' },
      { name: 'Pancreatic enzyme output', detail: 'Lipase + amylase + trypsinogen · 1.5L pancreatic juice/day', icon: '🫁' },
    ],
    doNow: ['Largest meal of the day (noon)', 'Deep focused cognitive work', 'Cooling coconut water', 'Sheetali pranayama (tongue-rolled breath)', 'Strategic planning & problem-solving', 'Avoid heated arguments — cortisol spikes inhibit digestion'],
    avoid: ['Skipping lunch (weakens Agni / digestive enzymes)', 'Spicy acidic foods at peak (excess HCl)', 'Anger during meals (cortisol shunts blood from gut)', 'Direct midday sun (core temp overload)', 'Overworking without recovery — cortisol burnout'],
    imbalance: [
      { symptom: 'Acid reflux & heartburn', science: 'Excess HCl production — lower esophageal sphincter (LES) pressure insufficient to contain it' },
      { symptom: 'Skin inflammation & cystic acne', science: 'Prostaglandin E2 excess + androgen → sebaceous gland hyperactivation + P. acnes proliferation' },
      { symptom: 'Anger & irritability', science: 'Elevated cortisol + serotonin deficiency → amygdala hyperreactivity, prefrontal inhibition weakens' },
      { symptom: 'Loose stools / diarrhoea', science: 'Excess bile acid secretion → osmotic diarrhoea (bile acid malabsorption in terminal ileum)' },
      { symptom: 'Premature grey hair', science: 'Melanocyte oxidative burnout — H₂O₂ accumulation from catalase enzyme deficiency' },
    ],
    balance: [
      { practice: 'Cooling foods: cucumber, coconut, coriander, mint', science: 'Reduces prostaglandin E2, lowers core temperature 0.2–0.4°C, reduces HCl stimulation' },
      { practice: 'Avoid eating when stressed or angry', science: 'Cortisol reduces gastrointestinal blood flow 40% — wasted digestive enzyme output' },
      { practice: 'Evening moonlight or nature walk', science: 'Low lux light (moonlight ≈ 0.1 lux) → reduces evening cortisol via visual pathway to SCN' },
      { practice: 'Coconut oil scalp application', science: 'Lauric acid penetrates hair shaft, reduces scalp inflammation and DHT-driven follicle miniaturisation' },
      { practice: 'Sheetali pranayama (cooling breath)', science: 'Evaporative cooling through wet tongue surface lowers tympanic temperature 0.3°C within 5 min' },
    ],
  },

  kapha: {
    name: 'Kapha', sanskrit: 'कफ', devanagari: 'पृथ्वी + जल',
    elements: 'Earth + Water', elementEquation: 'EARTH  +  WATER  =  STRUCTURE',
    westernSystem: 'Anabolic Hormone Axis · Lymphatic-Immune System · Structural Biology · Connective Tissue',
    color: '#34d399', emoji: '🌿',
    tagline: 'The principle of structure, immunity & anabolic repair',
    biology: 'Kapha maps to the anabolic-immune axis — growth, structural integrity, and immune defence. Growth hormone (GH), IGF-1, testosterone, estrogen, and oxytocin are all Kapha hormones. The entire lymphatic system — your body\'s "second circulatory system" with 600+ lymph nodes — is Kapha. In systems biology, Kapha is anabolism: building, not burning.',
    elementAir: {
      title: 'Earth (Prithvi) in the Body',
      body: 'Structural solid matter: hydroxyapatite crystals in bone (Ca₁₀(PO₄)₆(OH)₂ — 65% of bone weight), type I collagen fibres in connective tissue (30% of total body protein), sarcomere actin/myosin filaments in muscle, and the entire extracellular matrix (ECM) scaffolding.',
      molecules: 'Collagen types I–IV · Hydroxyapatite Ca₁₀(PO₄)₆(OH)₂ · Proteoglycans (heparan sulfate, chondroitin) · Fibronectin',
    },
    elementSpace: {
      title: 'Water (Jala) in the Body',
      body: 'Structural fluids providing cushion and immune transport: synovial fluid (joint lubrication, 0.5–4 ml per joint), cerebrospinal fluid (brain cushion, 150 ml renewed 3x daily), lymph (immune transport, 2–4L/day), pleural fluid, and all mucus membranes.',
      molecules: 'Hyaluronic acid (synovial fluid HA: 3.5 mg/ml) · CSF (150 ml, 3× daily turnover) · Lymph IgA (5g/day)',
    },
    neuro: [
      { name: 'Growth Hormone (GH)', role: 'Protein synthesis, lipolysis, tissue repair — pulses during NREM sleep' },
      { name: 'Testosterone', role: 'Muscle protein synthesis via mTOR, bone density, motivation and drive' },
      { name: 'Serotonin', role: 'Mood stability, sleep architecture initiation, intestinal motility' },
      { name: 'Oxytocin', role: 'Social bonding, trust, anti-inflammatory neuropeptide, wound healing' },
    ],
    peakWindows: [
      { time: 'Morning  6–10 AM', icon: '🌅', science: 'Testosterone peaks 20–25% above evening baseline at 7–8 AM. Cortisol awakening response (CAR) triggers anabolic cascade. Lymphocyte count is measurably highest in morning blood draws — immune readiness peak.' },
      { time: 'Evening  6–10 PM', icon: '🌙', science: 'Parasympathetic dominance shifts to rest-and-digest. Melatonin rises with darkness (triggered by SCN signalling to pineal gland). GH first pulse begins with NREM sleep onset after 10 PM Pitta transition.' },
    ],
    peakFact: 'Morning testosterone is 20–25% higher than evening baseline (circadian peak at 7–8 AM — Hyde et al.). Cortisol awakening response (CAR) co-rises, triggering an anabolic hormone cascade. Lymphocyte count is measurably highest in morning blood draws. Strength training in Kapha window maximises mTOR (muscle protein synthesis pathway) activation by 23% vs afternoon training.',
    functions: [
      { name: 'Synovial fluid production', detail: 'Hyaluronic acid matrix · 0.5–4 ml/joint · replenished by chondrocytes', icon: '🦴' },
      { name: 'Lymphatic immune circulation', detail: '600+ lymph nodes · 2–4 L lymph/day · T-cell & B-cell trafficking', icon: '🛡️' },
      { name: 'Collagen synthesis', detail: 'Type I (tendons/skin) + II (cartilage) + III (blood vessels) · 30% body protein', icon: '🔗' },
      { name: 'Muscle protein synthesis (MPS)', detail: 'mTOR pathway · 1.6–2.2 g/kg/day protein turnover · IGF-1 signalling', icon: '💪' },
      { name: 'Secretory IgA (sIgA)', detail: 'Mucosal immune defence · 5g/day — largest immunoglobulin output', icon: '🛡️' },
      { name: 'Hippocampal memory consolidation', detail: 'BDNF-driven neurogenesis · NREM slow-wave sleep memory transfer', icon: '🧠' },
    ],
    doNow: ['Vigorous exercise before 10 AM (AMPK activation)', 'Kapalabhati pranayama — 120 rapid exhales/min', 'Dry brushing (lymphatic stimulation)', 'Intermittent fasting 16:8 (autophagy activation)', 'Warm spiced drinks: ginger, black pepper (TRPV1)', 'Cold shower — mobilises Kapha stagnation'],
    avoid: ['Sleeping past sunrise (deepens Kapha stagnation)', 'Heavy dairy breakfast (mucus hypersecretion)', 'Long sedentary morning (insulin resistance)', 'Cold, heavy, sweet, oily foods in AM', 'Excess sleep > 8 hours (lethargy deepens)'],
    imbalance: [
      { symptom: 'Lethargy & oversleeping', science: 'Serotonin dominance + dopamine deficiency — reward motivation pathway (nucleus accumbens) underactivated' },
      { symptom: 'Weight gain & insulin resistance', science: 'Chronic adipogenesis over myogenesis — mTORC1 imbalance, adiponectin drops, resistin rises' },
      { symptom: 'Congestion & excess mucus', science: 'Lymphatic stagnation — IL-4 and IL-13 cytokines drive goblet cell hypersecretion' },
      { symptom: 'Depression & emotional heaviness', science: 'Serotonin transporter (SERT) dysregulation — reduced synaptic 5-HT, low BDNF (brain-derived neurotrophic factor)' },
      { symptom: 'Type 2 diabetes risk', science: 'Chronic Kapha = insulin receptor downregulation + adipokine imbalance (high leptin/resistin ratio)' },
    ],
    balance: [
      { practice: 'Vigorous morning exercise', science: 'Activates AMPK (cellular fuel sensor), depletes glycogen, increases GLUT4 translocation to muscle cell membrane' },
      { practice: 'Light dry spicy foods (ginger, pepper)', science: 'Capsaicin/piperine activate TRPV1 receptor → increases resting metabolic rate 4–5% for 3 hours' },
      { practice: 'Dry brushing before shower', science: 'Mechanical stimulation of skin lymphatics → increases lymphocyte circulation, removes metabolic waste' },
      { practice: 'Intermittent fasting (16:8)', science: 'Depletes hepatic glycogen by hour 12–14 → activates TFEB → initiates cellular autophagy (self-cleaning)' },
      { practice: 'Kapalabhati pranayama', science: '120 rapid exhales/min → clears pCO₂ → alkalises blood pH → activates sympathetic nervous system → burns Kapha' },
    ],
  },
} as const;

type DoshaKey = 'vata' | 'pitta' | 'kapha';
const ORDER: DoshaKey[] = ['vata', 'pitta', 'kapha'];

// ── Section divider component ────────────────────────────────────────────────
function SectionHeader({ label, color }: { label: string; color: string }) {
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 24, marginBottom: 12 }}>
      <View style={{ flex: 1, height: 1, backgroundColor: color + '22' }} />
      <Text style={{ fontSize: 8, fontWeight: '900', color: color + 'AA', letterSpacing: 2 }}>{label}</Text>
      <View style={{ flex: 1, height: 1, backgroundColor: color + '22' }} />
    </View>
  );
}

export default function DoshaExplorePage() {
  const router = useRouter();
  const params = useLocalSearchParams<{
    activeDosha?: string; periodLabel?: string;
    periodStart?: string; periodEnd?: string;
  }>();
  const activeDosha = (params.activeDosha ?? null) as DoshaKey | null;
  const [selected, setSelected] = useState<DoshaKey>(activeDosha ?? 'vata');

  const d = DOSHAS_FULL[selected];

  return (
    <View style={S.root}>
      <StatusBar barStyle="light-content" />

      <SafeAreaView style={{ flex: 1 }}>

        {/* ── Fixed Header ── */}
        <View style={S.header}>
          <TouchableOpacity
            onPress={() => router.back()}
            style={S.backBtn}
            hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}>
            <Text style={S.backArrow}>←</Text>
          </TouchableOpacity>
          <View style={{ flex: 1 }}>
            <Text style={S.cap}>AYURVEDIC SCIENCE  ·  CHRONOBIOLOGY</Text>
            <Text style={S.bioCircadianTitle}>BIO CIRCADIAN</Text>
            <Text style={S.bioCircadianSub}>ENVIRONMENT CYCLE</Text>
          </View>
          {activeDosha && (
            <View style={[S.liveBadge, { borderColor: DOSHAS_FULL[activeDosha].color + '55', backgroundColor: DOSHAS_FULL[activeDosha].color + '14' }]}>
              <View style={[S.liveDot, { backgroundColor: DOSHAS_FULL[activeDosha].color }]} />
              <Text style={[S.liveTxt, { color: DOSHAS_FULL[activeDosha].color }]}>LIVE</Text>
            </View>
          )}
        </View>

        {/* ── Active period pill ── */}
        {activeDosha && (
          <View style={[S.nowPill, { borderColor: DOSHAS_FULL[activeDosha].color + '50', backgroundColor: DOSHAS_FULL[activeDosha].color + '12' }]}>
            <View style={[S.nowDot, { backgroundColor: DOSHAS_FULL[activeDosha].color }]} />
            <Text style={[S.nowTxt, { color: DOSHAS_FULL[activeDosha].color }]}>
              {params.periodLabel ?? activeDosha.toUpperCase()}  ·  ACTIVE NOW
              {params.periodStart ? `  ·  ${params.periodStart} → ${params.periodEnd}` : ''}
            </Text>
          </View>
        )}

        {/* ── Dosha selector tabs ── */}
        <View style={S.tabs}>
          {ORDER.map(key => {
            const isActive = selected === key;
            const isNow = activeDosha === key;
            return (
              <TouchableOpacity
                key={key}
                onPress={() => setSelected(key)}
                activeOpacity={0.8}
                style={[S.tab, isActive && { borderBottomColor: DOSHAS_FULL[key].color, borderBottomWidth: 2 }]}>
                <Text style={{ fontSize: 18 }}>{DOSHAS_FULL[key].emoji}</Text>
                <Text style={[S.tabTxt, { color: isActive ? DOSHAS_FULL[key].color : '#FFFFFF40' }]}>
                  {DOSHAS_FULL[key].name}
                </Text>
                <Text style={{ fontSize: 7, color: isActive ? DOSHAS_FULL[key].color + '90' : '#FFFFFF25', fontWeight: '700' }}>
                  {DOSHAS_FULL[key].elements}
                </Text>
                {isNow && <View style={[S.tabDot, { backgroundColor: DOSHAS_FULL[key].color }]} />}
              </TouchableOpacity>
            );
          })}
        </View>

        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 80, paddingTop: 6 }}>

          {/* ══ HERO IDENTITY ══════════════════════════════════════════════ */}
          <LinearGradient
            colors={[d.color + '22', d.color + '08', 'transparent']}
            style={[S.heroCard, { borderColor: d.color + '35' }]}
            start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}>
            <View style={{ alignItems: 'center', paddingVertical: 20 }}>
              <Text style={{ fontSize: 56 }}>{d.emoji}</Text>
              <Text style={[S.heroName, { color: d.color }]}>{d.name}</Text>
              <Text style={S.heroSanskrit}>{d.sanskrit}  ·  {d.devanagari}</Text>
              {/* Element equation — prominent */}
              <View style={[S.equationBox, { borderColor: d.color + '50', backgroundColor: d.color + '14' }]}>
                <Text style={[S.equationTxt, { color: d.color }]}>{d.elementEquation}</Text>
              </View>
              <Text style={[S.heroTagline, { color: d.color + 'CC' }]}>{d.tagline}</Text>
            </View>
          </LinearGradient>

          {/* ══ WESTERN SCIENCE MAPPING ════════════════════════════════════ */}
          <SectionHeader label="MODERN SCIENTIFIC MAPPING" color={d.color} />
          <View style={[S.bioCard, { borderColor: d.color + '28', backgroundColor: d.color + '07' }]}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 }}>
              <Text style={{ fontSize: 16 }}>🔬</Text>
              <Text style={[S.bioCardLabel, { color: d.color }]}>BIOLOGICAL SYSTEM  ·  WESTERN EQUIVALENT</Text>
            </View>
            <View style={[S.systemBox, { borderColor: d.color + '30', backgroundColor: d.color + '0C' }]}>
              <Text style={[S.systemTxt, { color: d.color + 'EE' }]}>{d.westernSystem}</Text>
            </View>
            <Text style={S.bioBody}>{d.biology}</Text>
          </View>

          {/* ══ ELEMENT SCIENCE ════════════════════════════════════════════ */}
          <SectionHeader label="ELEMENT SCIENCE  ·  WHAT EACH ELEMENT IS IN YOUR BODY" color={d.color} />
          <View style={{ gap: 10 }}>
            {/* Element 1 */}
            <View style={[S.elementCard, { borderColor: d.color + '30', backgroundColor: d.color + '08' }]}>
              <Text style={[S.elementTitle, { color: d.color }]}>{d.elementAir.title}</Text>
              <Text style={S.elementBody}>{d.elementAir.body}</Text>
              <View style={[S.moleculeBox, { borderColor: d.color + '25' }]}>
                <Text style={S.moleculeLabel}>MOLECULES / MARKERS</Text>
                <Text style={[S.moleculeTxt, { color: d.color + 'BB' }]}>{d.elementAir.molecules}</Text>
              </View>
            </View>
            {/* Element 2 */}
            <View style={[S.elementCard, { borderColor: d.color + '30', backgroundColor: d.color + '08' }]}>
              <Text style={[S.elementTitle, { color: d.color }]}>{d.elementSpace.title}</Text>
              <Text style={S.elementBody}>{d.elementSpace.body}</Text>
              <View style={[S.moleculeBox, { borderColor: d.color + '25' }]}>
                <Text style={S.moleculeLabel}>MOLECULES / MARKERS</Text>
                <Text style={[S.moleculeTxt, { color: d.color + 'BB' }]}>{d.elementSpace.molecules}</Text>
              </View>
            </View>
          </View>

          {/* ══ KEY BIOCHEMICALS ═══════════════════════════════════════════ */}
          <SectionHeader label="KEY BIOCHEMICALS  ·  HORMONES & NEUROTRANSMITTERS" color={d.color} />
          <View style={{ gap: 8 }}>
            {d.neuro.map((n, i) => (
              <View key={i} style={[S.neuroCard, { borderColor: d.color + '28', backgroundColor: d.color + '07' }]}>
                <View style={[S.neuroBadge, { backgroundColor: d.color + '20', borderColor: d.color + '45' }]}>
                  <Text style={[S.neuroBadgeTxt, { color: d.color }]}>{n.name}</Text>
                </View>
                <Text style={S.neuroRole}>{n.role}</Text>
              </View>
            ))}
          </View>

          {/* ══ BODY FUNCTIONS ═════════════════════════════════════════════ */}
          <SectionHeader label="BODY SYSTEMS GOVERNED" color={d.color} />
          <View style={{ gap: 8 }}>
            {d.functions.map((f, i) => (
              <View key={i} style={[S.funcRow, { borderColor: d.color + '22', backgroundColor: d.color + '06' }]}>
                <Text style={{ fontSize: 18, minWidth: 28 }}>{f.icon}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={[S.funcName, { color: d.color + 'EE' }]}>{f.name}</Text>
                  <Text style={S.funcDetail}>{f.detail}</Text>
                </View>
              </View>
            ))}
          </View>

          {/* ══ CIRCADIAN PEAK WINDOWS ═════════════════════════════════════ */}
          <SectionHeader label="CIRCADIAN PEAK WINDOWS  ·  CHRONOBIOLOGY" color={d.color} />
          <View style={[S.peakFactCard, { borderColor: d.color + '30', backgroundColor: d.color + '08' }]}>
            <Text style={[S.peakFactLabel, { color: d.color }]}>🧬  RESEARCH HIGHLIGHT</Text>
            <Text style={S.peakFactText}>{d.peakFact}</Text>
          </View>
          <View style={{ gap: 10, marginTop: 10 }}>
            {d.peakWindows.map((w, i) => (
              <View key={i} style={[S.windowCard, { borderColor: d.color + '35', backgroundColor: d.color + '0A' }]}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                  <Text style={{ fontSize: 22 }}>{w.icon}</Text>
                  <View style={[S.windowTimePill, { borderColor: d.color + '50', backgroundColor: d.color + '18' }]}>
                    <Text style={[S.windowTimeTxt, { color: d.color }]}>{w.time}</Text>
                  </View>
                </View>
                <Text style={S.windowScience}>{w.science}</Text>
              </View>
            ))}
          </View>

          {/* ══ DO's ═══════════════════════════════════════════════════════ */}
          <SectionHeader label={`✓  DO DURING ${d.name.toUpperCase()} PERIOD`} color={d.color} />
          <View style={{ gap: 8 }}>
            {d.doNow.map((a, i) => (
              <View key={i} style={[S.doCard, { borderColor: d.color + '30', backgroundColor: d.color + '0C' }]}>
                <View style={[S.doCheckCircle, { borderColor: d.color + '60', backgroundColor: d.color + '22' }]}>
                  <Text style={[S.doCheckTxt, { color: d.color }]}>✓</Text>
                </View>
                <Text style={S.doItemTxt}>{a}</Text>
              </View>
            ))}
          </View>

          {/* ══ DON'Ts ═════════════════════════════════════════════════════ */}
          <SectionHeader label={`✕  AVOID DURING ${d.name.toUpperCase()} PERIOD`} color="#f43f5e" />
          <View style={{ gap: 8 }}>
            {d.avoid.map((a, i) => (
              <View key={i} style={S.dontCard}>
                <View style={S.dontXCircle}>
                  <Text style={S.dontXTxt}>✕</Text>
                </View>
                <Text style={S.dontItemTxt}>{a}</Text>
              </View>
            ))}
          </View>

          {/* ══ SIGNS OF IMBALANCE ═════════════════════════════════════════ */}
          <SectionHeader label={`⚠  SIGNS OF EXCESS ${d.name.toUpperCase()}`} color="#f43f5e" />
          <View style={{ gap: 8 }}>
            {d.imbalance.map((item, i) => (
              <View key={i} style={S.imbalanceCard}>
                <Text style={S.imbalanceSymptom}>{item.symptom}</Text>
                <Text style={S.imbalanceScience}>{item.science}</Text>
              </View>
            ))}
          </View>

          {/* ══ REBALANCING PRACTICES ══════════════════════════════════════ */}
          <SectionHeader label={`◎  REBALANCING ${d.name.toUpperCase()}  ·  EVIDENCE-BASED`} color={d.color} />
          <View style={{ gap: 8 }}>
            {d.balance.map((b, i) => (
              <View key={i} style={[S.balanceCard, { borderColor: d.color + '28', backgroundColor: d.color + '07' }]}>
                <Text style={[S.balancePractice, { color: d.color + 'EE' }]}>{b.practice}</Text>
                <View style={[S.balanceSciBox, { borderColor: d.color + '20' }]}>
                  <Text style={S.balanceSciTxt}>{b.science}</Text>
                </View>
              </View>
            ))}
          </View>

          {/* ══ CHRONOBIOLOGY FOOTER ═══════════════════════════════════════ */}
          <View style={S.footerCard}>
            <Text style={[S.footerTitle, { color: d.color }]}>☀️  Ayurveda = Chronobiology</Text>
            <Text style={S.footerBody}>
              The 3-Dosha system is a{' '}
              <Text style={{ color: '#fbbf24CC', fontWeight: '700' }}>5,000-year-old circadian biology framework</Text>
              {' '}— mapping the body's 24-hour hormonal and neurological oscillations to three elemental archetypes.{'\n\n'}
              Modern chronobiology (Pittendrigh, Rosbash, Hall, Young — Nobel Prize 2017) independently confirmed that every cell in the human body runs a molecular CLOCK gene. These biological rhythms match the Vata/Pitta/Kapha periods with remarkable precision.{'\n\n'}
              <Text style={{ color: '#FFFFFF55' }}>Dosha periods shift daily with your local sunrise & sunset — not a fixed clock. This makes the system hyper-personalised to your exact location and season.</Text>
            </Text>
          </View>

        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const S = StyleSheet.create({
  root:    { flex: 1, backgroundColor: '#040308' },

  header:  { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingTop: 14, paddingBottom: 10, gap: 12 },
  backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#00000055', borderWidth: 1, borderColor: '#FFFFFF25', alignItems: 'center', justifyContent: 'center' },
  backArrow: { fontSize: 20, color: '#FFFFFFEE', fontWeight: '200' },
  cap:              { fontSize: 8, fontWeight: '900', color: '#FFFFFF50', letterSpacing: 2, marginBottom: 3 },
  title:            { fontSize: 20, fontWeight: '900', color: '#FFFFFFF0', letterSpacing: -0.5 },
  bioCircadianTitle:{ fontSize: 18, fontWeight: '900', color: '#FFFFFFCC', letterSpacing: 0.6, lineHeight: 22 },
  bioCircadianSub:  { fontSize: 12, fontWeight: '700', color: '#FFFFFF55', letterSpacing: 1.4, lineHeight: 17 },
  liveBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 5 },
  liveDot:   { width: 6, height: 6, borderRadius: 3 },
  liveTxt:   { fontSize: 8, fontWeight: '900', letterSpacing: 1.4 },

  nowPill: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7, marginHorizontal: 16, marginBottom: 10 },
  nowDot:  { width: 7, height: 7, borderRadius: 4 },
  nowTxt:  { fontSize: 10, fontWeight: '800', flex: 1 },

  tabs:    { flexDirection: 'row', marginHorizontal: 16, marginBottom: 10, borderRadius: 18, backgroundColor: '#FFFFFF06', borderWidth: 1, borderColor: '#FFFFFF0C', overflow: 'hidden' },
  tab:     { flex: 1, alignItems: 'center', paddingVertical: 10, gap: 2, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabTxt:  { fontSize: 12, fontWeight: '900' },
  tabDot:  { width: 5, height: 5, borderRadius: 3, position: 'absolute', top: 6, right: 10 },

  heroCard:  { borderRadius: 22, borderWidth: 1, overflow: 'hidden', marginBottom: 4 },
  heroName:  { fontSize: 38, fontWeight: '900', letterSpacing: -1, marginTop: 10 },
  heroSanskrit: { fontSize: 13, color: '#FFFFFF55', fontWeight: '600', marginTop: 4 },
  equationBox: { borderWidth: 1.5, borderRadius: 14, paddingHorizontal: 20, paddingVertical: 9, marginTop: 14, marginBottom: 10 },
  equationTxt: { fontSize: 14, fontWeight: '900', letterSpacing: 1.5 },
  heroTagline: { fontSize: 12, fontWeight: '600', textAlign: 'center', lineHeight: 18, paddingHorizontal: 24 },

  bioCard:  { borderWidth: 1, borderRadius: 18, padding: 16 },
  bioCardLabel: { fontSize: 8, fontWeight: '900', letterSpacing: 1.4 },
  systemBox:  { borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 12 },
  systemTxt:  { fontSize: 11, fontWeight: '700', lineHeight: 18 },
  bioBody:  { fontSize: 12, color: '#FFFFFF65', lineHeight: 19 },

  elementCard: { borderWidth: 1, borderRadius: 16, padding: 14 },
  elementTitle: { fontSize: 13, fontWeight: '900', marginBottom: 8 },
  elementBody: { fontSize: 12, color: '#FFFFFF60', lineHeight: 18, marginBottom: 10 },
  moleculeBox: { borderTopWidth: 1, paddingTop: 10 },
  moleculeLabel: { fontSize: 7, fontWeight: '900', color: '#FFFFFF30', letterSpacing: 1.6, marginBottom: 5 },
  moleculeTxt: { fontSize: 10, fontWeight: '700', lineHeight: 16 },

  neuroCard:  { borderWidth: 1, borderRadius: 14, padding: 12, gap: 6 },
  neuroBadge: { alignSelf: 'flex-start', borderWidth: 1, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 4 },
  neuroBadgeTxt: { fontSize: 11, fontWeight: '900' },
  neuroRole: { fontSize: 12, color: '#FFFFFF60', lineHeight: 17 },

  funcRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 11 },
  funcName: { fontSize: 12, fontWeight: '800', marginBottom: 2 },
  funcDetail: { fontSize: 10, color: '#FFFFFF50', lineHeight: 15 },

  peakFactCard: { borderWidth: 1, borderRadius: 16, padding: 14 },
  peakFactLabel: { fontSize: 9, fontWeight: '900', letterSpacing: 1.4, marginBottom: 8 },
  peakFactText: { fontSize: 12, color: '#FFFFFF65', lineHeight: 18 },

  windowCard: { borderWidth: 1, borderRadius: 16, padding: 14 },
  windowTimePill: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 5 },
  windowTimeTxt: { fontSize: 12, fontWeight: '900' },
  windowScience: { fontSize: 12, color: '#FFFFFF60', lineHeight: 18 },

  doCard: { flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 11 },
  doCheckCircle: { width: 26, height: 26, borderRadius: 13, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  doCheckTxt: { fontSize: 11, fontWeight: '900' },
  doItemTxt: { fontSize: 12, color: '#FFFFFFCC', lineHeight: 18, flex: 1 },

  dontCard: { flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 11, backgroundColor: '#f43f5e07', borderColor: '#f43f5e22' },
  dontXCircle: { width: 26, height: 26, borderRadius: 13, borderWidth: 1.5, borderColor: '#f43f5e55', backgroundColor: '#f43f5e18', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  dontXTxt: { fontSize: 11, fontWeight: '900', color: '#f43f5e' },
  dontItemTxt: { fontSize: 12, color: '#FFFFFF65', lineHeight: 18, flex: 1 },

  imbalanceCard: { borderWidth: 1, borderRadius: 14, padding: 14, borderColor: '#f43f5e20', backgroundColor: '#f43f5e06' },
  imbalanceSymptom: { fontSize: 13, fontWeight: '800', color: '#f43f5eCC', marginBottom: 5 },
  imbalanceScience: { fontSize: 11, color: '#FFFFFF50', lineHeight: 17 },

  balanceCard: { borderWidth: 1, borderRadius: 14, padding: 14, gap: 8 },
  balancePractice: { fontSize: 13, fontWeight: '800', lineHeight: 18 },
  balanceSciBox: { borderTopWidth: 1, paddingTop: 8 },
  balanceSciTxt: { fontSize: 11, color: '#FFFFFF55', lineHeight: 17 },

  footerCard:  { marginTop: 24, marginBottom: 8, padding: 18, borderRadius: 20, backgroundColor: '#FFFFFF04', borderWidth: 1, borderColor: '#FFFFFF0C' },
  footerTitle: { fontSize: 14, fontWeight: '900', marginBottom: 10 },
  footerBody:  { fontSize: 12, color: '#FFFFFF80', lineHeight: 20 },
});
