import React, { useState } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, SafeAreaView, ImageBackground,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import Svg, { Circle as SvgCircle } from 'react-native-svg';
import { useBgContext } from '@/lib/bgContext';

// ── Full scientific dosha data ─────────────────────────────────────────────
const DOSHAS_FULL = {
  vata: {
    name: 'Vata', sanskrit: 'वात', devanagari: 'वायु + आकाश',
    elements: 'Air + Space', elementEquation: 'AIR  +  SPACE  =  MOVEMENT',
    westernSystem: 'Sympathetic Nervous System · Peripheral Nervous System · Enteric Nervous System',
    color: '#a78bfa', emoji: '💨',
    tagline: 'The principle of movement & neural electricity',
    biology: 'Vata maps to the Autonomic Nervous System — specifically the sympathetic (fight-or-flight) branch and the entire peripheral nervous system. Every action potential (70 mV impulse) traveling at 70–120 m/s through myelinated nerve fibres is pure Vata. The enteric nervous system ("gut brain") — 500 million neurons lining the GI tract — is entirely Vata-governed.',
    elementAir: {
      title: 'Air (Vayu) in the Body',
      body: 'Alveolar gas exchange (O₂/CO₂), electrochemical gradients across cell membranes, and electromagnetic fields generated by neural firing. Nerve action potentials are literally electrical air — charge moving through biological space.',
      molecules: 'pO₂ · CO₂ respiratory quotient · Na⁺/K⁺ ATPase gradient · Action potential (−70 mV resting)',
    },
    elementSpace: {
      title: 'Space (Akasha) in the Body',
      body: 'Synaptic clefts (20 nm gaps between neurons where neurotransmitters travel), hollow body channels (arteries, bronchi, gut lumen), extracellular matrix, and the quantum electromagnetic field generated by 86 billion neurons firing simultaneously.',
      molecules: 'Synaptic vesicle release zones · Extracellular matrix (ECM) · Interstitial space (15L of body fluid)',
    },
    neuro: [
      { name: 'Dopamine', role: 'Movement initiation, reward motivation, creative drive, prefrontal focus' },
      { name: 'Norepinephrine', role: 'Sympathetic alertness, attention regulation, fight-or-flight activation' },
      { name: 'Acetylcholine', role: 'Nerve-muscle junction (NMJ), hippocampal memory encoding, REM sleep' },
      { name: 'GABA', role: 'Inhibitory counterbalance — prevents Vata hyperactivation and anxiety' },
    ],
    peakWindows: [
      { time: 'Pre-Dawn  2–6 AM', icon: '🌙', science: 'REM sleep peaks — hippocampal theta waves consolidate memory. Norepinephrine drops to its 24-hour nadir then begins rising. Enteric nervous system (ENS) microbiome circadian clock activates gut repair.' },
      { time: 'Afternoon  2–6 PM', icon: '✍️', science: 'Spirometry confirms peak lung vital capacity at 3–4 PM. Plasma dopamine & norepinephrine measurably elevated. Reaction time is at its fastest. Athletic world records are predominantly broken in this window (Reilly & Atkinson, 2009).' },
    ],
    peakFact: 'Plasma catecholamines (adrenaline + noradrenaline) follow a strict circadian pattern confirmed by chrono-pharmacology. Lung vital capacity peaks at 3–4 PM (spirometry). Reaction time, fine motor coordination and VO₂max are all highest in the afternoon Vata window.',
    functions: [
      { name: 'Nerve conduction velocity', detail: '70–120 m/s in myelinated Aα fibres · 0.5 m/s in unmyelinated C fibres', icon: '⚡' },
      { name: 'Respiratory rhythm', detail: '12–20 breaths/min controlled by pre-Bötzinger complex in brainstem', icon: '🫁' },
      { name: 'Cardiac HIS-Purkinje', detail: 'Electrical conduction system — SA node → AV node → 70 bpm rhythm', icon: '❤️' },
      { name: 'Gut motility (peristalsis)', detail: 'Migrating motor complex — 1–3 cm/s waves in small intestine', icon: '🌀' },
      { name: 'Working memory speed', detail: 'Prefrontal cortex γ-oscillations (40 Hz) — 100 ms neural processing loops', icon: '🧠' },
      { name: 'Motor coordination', detail: 'Cerebellum timing + basal ganglia rhythm — 10 ms precision', icon: '🤸' },
    ],
    doNow: ['Slow pranayama (4-7-8 breathing)', 'Warm sesame oil Abhyanga self-massage', 'Fixed sleep/wake schedule', 'Warm cooked grounding foods', 'Barefoot walk on earth (earthing)', 'Journal or sit in stillness'],
    avoid: ['Cold raw foods (amplify Vata kinetics)', 'Irregular schedule (dysregulates CLOCK gene)', 'Excess caffeine (spikes catecholamines)', 'Multitasking (fragmenting dopamine loops)', 'Screen exposure before sleep (blocks melatonin)'],
    imbalance: [
      { symptom: 'Anxiety & racing thoughts', science: 'Excess sympathetic tone — chronically elevated norepinephrine & CRH (corticotropin-releasing hormone)' },
      { symptom: 'Insomnia', science: 'Nocturnal norepinephrine prevents GABA-mediated sleep onset — HRV (heart rate variability) remains high' },
      { symptom: 'Constipation', science: 'Weakened peristaltic waves — low acetylcholine in enteric nervous system (ENS)' },
      { symptom: 'Joint cracking & dryness', science: 'Reduced synovial fluid (hyaluronic acid depletion) — mechanical joint friction increases' },
      { symptom: 'Restlessness, ADHD-like symptoms', science: 'Dopamine dysregulation — prefrontal cortex D1-receptor underactivation, excess D2 in striatum' },
    ],
    balance: [
      { practice: 'Warm cooked, slightly oily foods', science: 'Boosts intestinal serotonin (5-HT) → vagal signalling → parasympathetic grounding' },
      { practice: 'Fixed sleep/wake schedule', science: 'Regulates cortisol awakening response (CAR) and CLOCK/BMAL1 gene expression' },
      { practice: 'Abhyanga — warm sesame oil massage', science: 'Stimulates vagal tone → reduces cortisol 28% (Ironson et al.) → activates parasympathetic' },
      { practice: '4-7-8 breathing technique', science: 'Activates ventral vagal complex → improves HRV (heart rate variability) — measurable within 5 minutes' },
      { practice: 'Barefoot earthing on soil/grass', science: 'Transfers free electrons from earth → reduces inflammatory CRP markers (Chevalier et al., 2012)' },
    ],
  },

  pitta: {
    name: 'Pitta', sanskrit: 'पित्त', devanagari: 'अग्नि + जल',
    elements: 'Fire + Water', elementEquation: 'FIRE  +  WATER  =  METABOLISM',
    westernSystem: 'HPA Axis · Hepatic Metabolism · Digestive Enzyme System · Thermogenetic System',
    color: '#fb923c', emoji: '🔥',
    tagline: 'The principle of metabolic fire & biochemical transformation',
    biology: 'Pitta maps to the metabolic-endocrine axis — every biochemical transformation: food → ATP, cholesterol → hormones, xenobiotics → water-soluble metabolites. Cytochrome P450 enzymes (liver detox), gastric acid secretion, insulin signalling, and core temperature regulation are all Pitta. In endocrinology, Pitta is the HPA (Hypothalamic-Pituitary-Adrenal) axis.',
    elementAir: {
      title: 'Fire (Agni) in the Body',
      body: 'Oxidative phosphorylation in mitochondria — electrons cascade through Complexes I–IV of the electron transport chain, producing 32 ATP per glucose molecule. This is literally fire at the cellular level: controlled combustion generating heat and energy.',
      molecules: 'ATP synthase (Complex V) · NADH/FADH₂ electron carriers · Reactive oxygen species (ROS) · UCP1 (thermogenin)',
    },
    elementSpace: {
      title: 'Water (Jala) in the Body',
      body: 'All enzymatic reactions occur in aqueous medium — enzymes are functionless without water. Bile is 95% water. Blood plasma is 92% water. Hydrolysis reactions (breaking bonds with water) power digestion. Every Pitta transformation is water-mediated.',
      molecules: 'Intracellular water 67% · Plasma (91.5% H₂O) · Enzymatic hydrolysis · pH buffering (bicarbonate system)',
    },
    neuro: [
      { name: 'Cortisol', role: 'Energy mobilisation, anti-inflammatory, circadian rhythm driver, cognitive sharpness' },
      { name: 'Insulin', role: 'Glucose uptake by cells, anabolic signalling, metabolic gatekeeper' },
      { name: 'Thyroid (T3/T4)', role: 'Sets basal metabolic rate, thermogenesis, protein synthesis rate' },
      { name: 'HCl & Pepsin', role: 'Protein denaturation at pH 1.5–3.5, vitamin B12 activation via intrinsic factor' },
    ],
    peakWindows: [
      { time: 'Midday  10 AM–2 PM', icon: '☀️', science: 'Gastric acid (HCl) hits lowest pH (highest acidity) at 12–1 PM — confirmed by intragastric pH studies. Insulin sensitivity is 30% higher at noon vs evening. Core body temperature peaks at 2–3 PM. Cognitive processing (IQ-task performance) peaks in this window.' },
      { time: 'Night  10 PM–2 AM', icon: '🌙', science: 'Liver Cytochrome P450 3A4 enzymes peak in hepatocytes during deep sleep — Phase I & II detoxification at maximum. Growth hormone first secretion pulse occurs. Intestinal epithelial cell turnover accelerates.' },
    ],
    peakFact: 'Gastric acid peaks at solar noon — intragastric pH studies confirm pH 1.5 at 12–1 PM. Insulin sensitivity 30% higher at midday vs evening. Core temperature peaks at 2–3 PM. Night Pitta: CYP3A4 (the enzyme metabolising 50% of pharmaceuticals) peaks during deep sleep.',
    functions: [
      { name: 'HCl & Pepsin secretion', detail: 'Parietal cells secrete 1.5–3L HCl/day · gastric pH 1.5–3.5', icon: '🧪' },
      { name: 'Bile acid synthesis', detail: 'Liver converts cholesterol → cholic acid · 600 ml bile/day', icon: '💛' },
      { name: 'Cytochrome P450 detox', detail: 'Phase I (oxidation) + Phase II (conjugation) · 60 CYP enzymes', icon: '🔄' },
      { name: 'Core temperature regulation', detail: 'Hypothalamic set-point: 37°C ± 0.5°C · circadian variation 36.5–37.5°C', icon: '🌡️' },
      { name: 'Retinal phototransduction', detail: 'Photoreceptors process 10⁷ photons/sec · rhodopsin regeneration', icon: '👁️' },
      { name: 'Pancreatic enzyme output', detail: 'Lipase + amylase + trypsinogen · 1.5L pancreatic juice/day', icon: '🫁' },
    ],
    doNow: ['Largest meal of the day (noon)', 'Deep focused cognitive work', 'Cooling coconut water', 'Sheetali pranayama (tongue-rolled breath)', 'Strategic planning & problem-solving', 'Avoid heated arguments — cortisol spikes inhibit digestion'],
    avoid: ['Skipping lunch (weakens Agni / digestive enzymes)', 'Spicy acidic foods at peak (excess HCl)', 'Anger during meals (cortisol shunts blood from gut)', 'Direct midday sun (core temp overload)', 'Overworking without recovery — cortisol burnout'],
    imbalance: [
      { symptom: 'Acid reflux & heartburn', science: 'Excess HCl production — lower esophageal sphincter (LES) pressure insufficient to contain it' },
      { symptom: 'Skin inflammation & cystic acne', science: 'Prostaglandin E2 excess + androgen → sebaceous gland hyperactivation + P. acnes proliferation' },
      { symptom: 'Anger & irritability', science: 'Elevated cortisol + serotonin deficiency → amygdala hyperreactivity, prefrontal inhibition weakens' },
      { symptom: 'Loose stools / diarrhoea', science: 'Excess bile acid secretion → osmotic diarrhoea (bile acid malabsorption in terminal ileum)' },
      { symptom: 'Premature grey hair', science: 'Melanocyte oxidative burnout — H₂O₂ accumulation from catalase enzyme deficiency' },
    ],
    balance: [
      { practice: 'Cooling foods: cucumber, coconut, coriander, mint', science: 'Reduces prostaglandin E2, lowers core temperature 0.2–0.4°C, reduces HCl stimulation' },
      { practice: 'Avoid eating when stressed or angry', science: 'Cortisol reduces gastrointestinal blood flow 40% — wasted digestive enzyme output' },
      { practice: 'Evening moonlight or nature walk', science: 'Low lux light (moonlight ≈ 0.1 lux) → reduces evening cortisol via visual pathway to SCN' },
      { practice: 'Coconut oil scalp application', science: 'Lauric acid penetrates hair shaft, reduces scalp inflammation and DHT-driven follicle miniaturisation' },
      { practice: 'Sheetali pranayama (cooling breath)', science: 'Evaporative cooling through wet tongue surface lowers tympanic temperature 0.3°C within 5 min' },
    ],
  },

  kapha: {
    name: 'Kapha', sanskrit: 'कफ', devanagari: 'पृथ्वी + जल',
    elements: 'Earth + Water', elementEquation: 'EARTH  +  WATER  =  STRUCTURE',
    westernSystem: 'Anabolic Hormone Axis · Lymphatic-Immune System · Structural Biology · Connective Tissue',
    color: '#34d399', emoji: '💧',
    tagline: 'The principle of structure, immunity & anabolic repair',
    biology: 'Kapha maps to the anabolic-immune axis — growth, structural integrity, and immune defence. Growth hormone (GH), IGF-1, testosterone, estrogen, and oxytocin are all Kapha hormones. The entire lymphatic system — your body\'s "second circulatory system" with 600+ lymph nodes — is Kapha. In systems biology, Kapha is anabolism: building, not burning.',
    elementAir: {
      title: 'Earth (Prithvi) in the Body',
      body: 'Structural solid matter: hydroxyapatite crystals in bone (Ca₁₀(PO₄)₆(OH)₂ — 65% of bone weight), type I collagen fibres in connective tissue (30% of total body protein), sarcomere actin/myosin filaments in muscle, and the entire extracellular matrix (ECM) scaffolding.',
      molecules: 'Collagen types I–IV · Hydroxyapatite Ca₁₀(PO₄)₆(OH)₂ · Proteoglycans (heparan sulfate, chondroitin) · Fibronectin',
    },
    elementSpace: {
      title: 'Water (Jala) in the Body',
      body: 'Structural fluids providing cushion and immune transport: synovial fluid (joint lubrication, 0.5–4 ml per joint), cerebrospinal fluid (brain cushion, 150 ml renewed 3x daily), lymph (immune transport, 2–4L/day), pleural fluid, and all mucus membranes.',
      molecules: 'Hyaluronic acid (synovial fluid HA: 3.5 mg/ml) · CSF (150 ml, 3× daily turnover) · Lymph IgA (5g/day)',
    },
    neuro: [
      { name: 'Growth Hormone (GH)', role: 'Protein synthesis, lipolysis, tissue repair — pulses during NREM sleep' },
      { name: 'Testosterone', role: 'Muscle protein synthesis via mTOR, bone density, motivation and drive' },
      { name: 'Serotonin', role: 'Mood stability, sleep architecture initiation, intestinal motility' },
      { name: 'Oxytocin', role: 'Social bonding, trust, anti-inflammatory neuropeptide, wound healing' },
    ],
    peakWindows: [
      { time: 'Morning  6–10 AM', icon: '🌅', science: 'Testosterone peaks 20–25% above evening baseline at 7–8 AM. Cortisol awakening response (CAR) triggers anabolic cascade. Lymphocyte count is measurably highest in morning blood draws — immune readiness peak.' },
      { time: 'Evening  6–10 PM', icon: '🌙', science: 'Parasympathetic dominance shifts to rest-and-digest. Melatonin rises with darkness (triggered by SCN signalling to pineal gland). GH first pulse begins with NREM sleep onset after 10 PM Pitta transition.' },
    ],
    peakFact: 'Morning testosterone is 20–25% higher than evening baseline (circadian peak at 7–8 AM — Hyde et al.). Cortisol awakening response (CAR) co-rises, triggering an anabolic hormone cascade. Lymphocyte count is measurably highest in morning blood draws. Strength training in Kapha window maximises mTOR (muscle protein synthesis pathway) activation by 23% vs afternoon training.',
    functions: [
      { name: 'Synovial fluid production', detail: 'Hyaluronic acid matrix · 0.5–4 ml/joint · replenished by chondrocytes', icon: '🦴' },
      { name: 'Lymphatic immune circulation', detail: '600+ lymph nodes · 2–4 L lymph/day · T-cell & B-cell trafficking', icon: '🛡️' },
      { name: 'Collagen synthesis', detail: 'Type I (tendons/skin) + II (cartilage) + III (blood vessels) · 30% body protein', icon: '🔗' },
      { name: 'Muscle protein synthesis (MPS)', detail: 'mTOR pathway · 1.6–2.2 g/kg/day protein turnover · IGF-1 signalling', icon: '💪' },
      { name: 'Secretory IgA (sIgA)', detail: 'Mucosal immune defence · 5g/day — largest immunoglobulin output', icon: '🛡️' },
      { name: 'Hippocampal memory consolidation', detail: 'BDNF-driven neurogenesis · NREM slow-wave sleep memory transfer', icon: '🧠' },
    ],
    doNow: ['Vigorous exercise before 10 AM (AMPK activation)', 'Kapalabhati pranayama — 120 rapid exhales/min', 'Dry brushing (lymphatic stimulation)', 'Intermittent fasting 16:8 (autophagy activation)', 'Warm spiced drinks: ginger, black pepper (TRPV1)', 'Cold shower — mobilises Kapha stagnation'],
    avoid: ['Sleeping past sunrise (deepens Kapha stagnation)', 'Heavy dairy breakfast (mucus hypersecretion)', 'Long sedentary morning (insulin resistance)', 'Cold, heavy, sweet, oily foods in AM', 'Excess sleep > 8 hours (lethargy deepens)'],
    imbalance: [
      { symptom: 'Lethargy & oversleeping', science: 'Serotonin dominance + dopamine deficiency — reward motivation pathway (nucleus accumbens) underactivated' },
      { symptom: 'Weight gain & insulin resistance', science: 'Chronic adipogenesis over myogenesis — mTORC1 imbalance, adiponectin drops, resistin rises' },
      { symptom: 'Congestion & excess mucus', science: 'Lymphatic stagnation — IL-4 and IL-13 cytokines drive goblet cell hypersecretion' },
      { symptom: 'Depression & emotional heaviness', science: 'Serotonin transporter (SERT) dysregulation — reduced synaptic 5-HT, low BDNF (brain-derived neurotrophic factor)' },
      { symptom: 'Type 2 diabetes risk', science: 'Chronic Kapha = insulin receptor downregulation + adipokine imbalance (high leptin/resistin ratio)' },
    ],
    balance: [
      { practice: 'Vigorous morning exercise', science: 'Activates AMPK (cellular fuel sensor), depletes glycogen, increases GLUT4 translocation to muscle cell membrane' },
      { practice: 'Light dry spicy foods (ginger, pepper)', science: 'Capsaicin/piperine activate TRPV1 receptor → increases resting metabolic rate 4–5% for 3 hours' },
      { practice: 'Dry brushing before shower', science: 'Mechanical stimulation of skin lymphatics → increases lymphocyte circulation, removes metabolic waste' },
      { practice: 'Intermittent fasting (16:8)', science: 'Depletes hepatic glycogen by hour 12–14 → activates TFEB → initiates cellular autophagy (self-cleaning)' },
      { practice: 'Kapalabhati pranayama', science: '120 rapid exhales/min → clears pCO₂ → alkalises blood pH → activates sympathetic nervous system → burns Kapha' },
    ],
  },
} as const;

// ══ WHAT IS AYURVEDA ═══════════════════════════════════════════════════════════
const AYURVEDA = {
  etymology: '"Ayur" = Life  ·  "Veda" = Knowledge / Science',
  tagline: 'The 5,000-Year Science of Life',
  meaning: 'Ayurveda literally means "The Science of Life." It is the world\'s oldest holistic healing system — a complete science of living that integrates diet, sleep, breath, movement, and consciousness with the laws of nature and cosmic cycles.',
  core: 'Ayurveda understands the body as a microcosm of the universe — composed of the same five elements (Pancha Mahabhuta): Earth, Water, Fire, Air, and Space. These combine into three biological forces called Doshas that govern every physical and mental process in the body.',
  uniqueness: 'Unlike modern medicine which focuses on disease treatment, Ayurveda is fundamentally preventive — it maps your unique constitution (Prakriti) and aligns daily rhythm (Dinacharya), food (Ahara), and behaviour with the laws of nature.',
  origin: 'First systematized in the Charaka Samhita (~1000 BCE) and Sushruta Samhita (~600 BCE), Ayurveda predates Greek medicine and is considered the mother of all healing traditions. Modern chronobiology (Nobel Prize 2017) independently confirms its circadian framework.',
};

// ══ SHAD RASA — THE SIX TASTES ════════════════════════════════════════════════
const SHAD_RASA = [
  {
    name: 'Madhura', english: 'Sweet', emoji: '🍯', color: '#fbbf24',
    elements: 'Earth + Water',
    effect: 'Nourishing, building, grounding, anabolic',
    dosha: 'Balances Vata & Pitta  ·  Aggravates Kapha',
    examples: 'Rice, wheat, milk, ghee, dates, sweet potato, honey',
    science: 'Triggers insulin release and tryptophan uptake → serotonin synthesis. Anabolic hormones (GH, IGF-1) increase. Opioid receptors activated → calming. Excess → insulin resistance, obesity, diabetes risk.',
  },
  {
    name: 'Amla', english: 'Sour', emoji: '🍋', color: '#a3e635',
    elements: 'Earth + Fire',
    effect: 'Stimulating, digestive, heating, cleansing',
    dosha: 'Balances Vata  ·  Aggravates Pitta & Kapha',
    examples: 'Lemon, yogurt, tamarind, vinegar, fermented foods, amla berry',
    science: 'Acidic compounds stimulate HCl secretion and salivary amylase. Organic acids (citric, malic) chelate minerals for absorption. Probiotics in fermented sour foods → gut microbiome diversity.',
  },
  {
    name: 'Lavana', english: 'Salty', emoji: '🧂', color: '#38bdf8',
    elements: 'Water + Fire',
    effect: 'Hydrating, softening, mildly stimulating',
    dosha: 'Balances Vata  ·  Aggravates Pitta & Kapha',
    examples: 'Sea salt, rock salt, seaweed, soy sauce, pickles, mineral-rich foods',
    science: 'Sodium-potassium ATPase pump regulates all cellular action potentials — essential for nerve function. Chloride ions necessary for HCl production. Excess → hypertension, water retention, endothelial inflammation.',
  },
  {
    name: 'Katu', english: 'Pungent', emoji: '🌶️', color: '#f87171',
    elements: 'Fire + Air',
    effect: 'Heating, stimulating, drying, metabolism-boosting',
    dosha: 'Balances Kapha  ·  Aggravates Vata & Pitta',
    examples: 'Ginger, black pepper, chilli, garlic, onion, mustard, asafoetida',
    science: 'Capsaicin activates TRPV1 receptor → thermogenesis. Allicin (garlic) → vasodilation via NO pathway. Gingerols → COX-2 inhibition (anti-inflammatory). Piperine → 2000% increase in curcumin bioavailability.',
  },
  {
    name: 'Tikta', english: 'Bitter', emoji: '🌿', color: '#34d399',
    elements: 'Air + Space',
    effect: 'Detoxifying, anti-inflammatory, cooling, fat-reducing',
    dosha: 'Balances Pitta & Kapha  ·  Aggravates Vata',
    examples: 'Turmeric, neem, bitter melon, fenugreek, dark greens, coffee',
    science: 'Bitter compounds activate TAS2R receptors → stimulate bile flow (choleretic) → liver detox. Curcumin inhibits NF-κB → anti-inflammatory. Berberine activates AMPK → metabolic enzyme action similar to metformin.',
  },
  {
    name: 'Kashaya', english: 'Astringent', emoji: '🍃', color: '#94a3b8',
    elements: 'Air + Earth',
    effect: 'Drying, firming, haemostatic, tissue-toning',
    dosha: 'Balances Pitta & Kapha  ·  Aggravates Vata',
    examples: 'Pomegranate, unripe banana, lentils, beans, green tea, turmeric',
    science: 'Tannins and polyphenols cross-link proteins → tissue tightening, reduced secretions. Quercetin → mast cell stabilisation → anti-allergic. Gallic acid → inhibits MMP matrix metalloproteinases → wound healing.',
  },
];

// ══ PRAKRITI — CONSTITUTIONAL TYPES ═══════════════════════════════════════════
const PRAKRITI_TYPES = [
  {
    type: 'Vata Prakriti', emoji: '🌬️', color: '#a78bfa',
    body: 'Thin frame, light bones, dry skin, cool extremities, variable appetite',
    mind: 'Creative, quick, enthusiastic — can be anxious and scattered',
    strength: 'Fast metabolism, creative thinking, agile movement, rapid learning',
    challenge: 'Irregular digestion, cold sensitivity, anxiety-prone, poor sleep',
    diet: 'Warm, cooked, oily — sweet, sour, salty tastes. Sesame oil, ghee, root vegetables, soups.',
    routine: 'Fixed wake/sleep schedule is essential. Daily warm oil Abhyanga. Avoid irregular travel.',
  },
  {
    type: 'Pitta Prakriti', emoji: '🔥', color: '#fb923c',
    body: 'Medium muscular frame, warm body temperature, sharp features, strong digestion',
    mind: 'Intelligent, focused, decisive, competitive — can be irritable and controlling',
    strength: 'Sharp intellect, strong digestion, natural leadership, precision and focus',
    challenge: 'Inflammation, skin issues, anger, perfectionism, heat sensitivity',
    diet: 'Cooling, sweet, bitter, astringent. Coconut, cucumber, coriander, mint, pomegranate.',
    routine: 'Avoid midday sun. Evening moonlight walks. Limit alcohol and spicy food. Meditate daily.',
  },
  {
    type: 'Kapha Prakriti', emoji: '🌿', color: '#34d399',
    body: 'Larger solid frame, cool moist skin, slow metabolism, strong endurance',
    mind: 'Calm, loving, patient, stable — can be resistant to change and lethargic',
    strength: 'Endurance, emotional stability, strong immunity, excellent long-term memory',
    challenge: 'Weight gain, congestion, depression, oversleeping, emotional attachment',
    diet: 'Light, warm, dry, spicy, bitter, astringent. Avoid dairy, cold and heavy foods.',
    routine: 'Wake before 6 AM. Daily vigorous exercise is non-negotiable. Kapalabhati pranayama.',
  },
  {
    type: 'Vata-Pitta', emoji: '⚡', color: '#f9a8d4',
    body: 'Lean to medium frame, combination of Vata lightness and Pitta sharpness',
    mind: 'Creative AND analytical — driven, energetic, prone to anxiety and irritability',
    strength: 'Versatile, high-energy, creative with execution ability',
    challenge: 'Managing both wind and fire — irregular digestion AND inflammation',
    diet: 'Warm, moderately oily foods. Balance sweet/cooling (Pitta) with grounding (Vata).',
    routine: 'Regular schedule (Vata) + cooling practices (Pitta). Avoid extremes of temperature.',
  },
  {
    type: 'Pitta-Kapha', emoji: '🌊', color: '#60a5fa',
    body: 'Medium to large muscular frame, strong stamina, robust constitution',
    mind: 'Determined, steady, goal-oriented — can be stubborn and possessive',
    strength: 'Excellent physical endurance, strong digestion, stable emotional core',
    challenge: 'Inflammatory disorders AND congestion/weight gain simultaneously',
    diet: 'Light, bitter, astringent, cooling. Reduce both sweet (Kapha) and spicy (Pitta).',
    routine: 'Exercise vigorously but avoid overheating. Favour morning workouts.',
  },
  {
    type: 'Sama Prakriti', emoji: '☯️', color: '#a78bfa',
    body: 'Balanced frame — rare and considered ideal in Ayurveda',
    mind: 'Well-rounded — creative, intelligent, and stable simultaneously',
    strength: 'Excellent adaptability, resilience, balanced digestion and immunity',
    challenge: 'Maintaining balance — any extreme throws off the equilibrium',
    diet: 'Seasonal eating: warming in winter, cooling in summer, light in monsoon.',
    routine: 'Seasonal Dinacharya adjustments. Moderate of all practices.',
  },
];

type DoshaKey = 'vata' | 'pitta' | 'kapha';
const ORDER: DoshaKey[] = ['vata', 'pitta', 'kapha'];

// ── Helpers ──────────────────────────────────────────────────────────────────
const SUNRISE_REF: Record<string, string> = {
  'Pre-Dawn  2–6 AM':   '4 – 0 hours before sunrise',
  'Afternoon  2–6 PM':  '8 – 12 hours after sunrise',
  'Midday  10 AM–2 PM': '4 – 8 hours after sunrise',
  'Night  10 PM–2 AM':  '16 – 20 hours after sunrise',
  'Morning  6–10 AM':   'At sunrise · 0 – 4 hours after',
  'Evening  6–10 PM':   '12 – 16 hours after sunrise',
};

function getSunriseRef(start: string, end: string): string {
  const parse = (t: string): number => {
    const m = t.match(/(\d+):(\d+)\s*(AM|PM)/i);
    if (!m) return 6;
    let h = parseInt(m[1]);
    if (m[3].toUpperCase() === 'PM' && h !== 12) h += 12;
    if (m[3].toUpperCase() === 'AM' && h === 12) h = 0;
    return h;
  };
  const SR = 6;
  const ds = parse(start) - SR;
  const de = parse(end) - SR;
  const f = (d: number) =>
    d < 0 ? `${Math.abs(d)}h before sunrise` : d === 0 ? 'at sunrise' : `${d}h after sunrise`;
  return `${f(ds)} · ends ${f(de)}`;
}

function Divider({ label, color }: { label: string; color: string }) {
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginHorizontal: 16, marginTop: 28, marginBottom: 14 }}>
      <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
      <Text style={{ fontSize: 8, fontWeight: '900', color: color + '95', letterSpacing: 1.8, textAlign: 'center', flexShrink: 1 }}>{label}</Text>
      <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
    </View>
  );
}

function SciCard({ title, body, color, subtitle }: { title: string; body: string; color: string; subtitle?: string }) {
  return (
    <View style={[S.sciCard, { borderColor: color + '25' }]}>
      <Text style={[S.sciCardTitle, { color }]}>{title}</Text>
      {subtitle ? (
        <Text style={{ fontSize: 9, color: color + '75', fontWeight: '800', letterSpacing: 1.4, marginTop: 2, marginBottom: 7, textTransform: 'uppercase' }}>{subtitle}</Text>
      ) : null}
      <Text style={S.sciCardBody}>{body}</Text>
    </View>
  );
}


export default function DoshaExplorePage() {
  const router = useRouter();
  const { bgUri } = useBgContext();
  const params = useLocalSearchParams<{ activeDosha?: string; periodLabel?: string; periodStart?: string; periodEnd?: string; sciEmoji?: string; sciTitle?: string; sciDesc?: string; minutesRemaining?: string; durMinutes?: string; activities?: string; avoidances?: string; }>();
  const adk = (params.activeDosha ?? 'vata') as DoshaKey;
  const [sel, setSel] = useState<DoshaKey>(adk);
  const [rasaOpen, setRasaOpen] = useState<string | null>(null);
  const [prakOpen, setPrakOpen] = useState<string | null>(null);
  const d = DOSHAS_FULL[sel];
  const ap = DOSHAS_FULL[adk];
  const C = ap.color;

  const pd = params.sciDesc ? {
    sciEmoji: params.sciEmoji ?? '💪',
    sciTitle: params.sciTitle ?? '',
    sciDesc:  params.sciDesc ?? '',
    minutesRemaining: parseInt(params.minutesRemaining ?? '0'),
    durMinutes: Math.max(1, parseInt(params.durMinutes ?? '1')),
    activities: (() => { try { return JSON.parse(params.activities ?? '[]') as string[]; } catch { return [] as string[]; } })(),
    avoidances: (() => { try { return JSON.parse(params.avoidances ?? '[]') as string[]; } catch { return [] as string[]; } })(),
  } : null;
  const pdProg  = pd ? Math.min(1, Math.max(0, (pd.durMinutes - pd.minutesRemaining) / pd.durMinutes)) : 0.5;
  const remStr  = pd ? (pd.minutesRemaining >= 60 ? `${Math.floor(pd.minutesRemaining / 60)}h ${pd.minutesRemaining % 60}m` : `${pd.minutesRemaining}m`) : '';
  const RR = 38; const RC = 2 * Math.PI * RR;
  const getActEmoji = (t: string) => { const s = t.toLowerCase(); if (s.includes('yoga') || s.includes('meditat')) return '🧘'; if (s.includes('pranay') || s.includes('kapalbhati') || s.includes('breath')) return '🫁'; if (s.includes('exercise') || s.includes('workout') || s.includes('vigorous') || s.includes('train')) return '💪'; if (s.includes('cogni') || s.includes('focus') || s.includes('strategic') || s.includes('plan') || s.includes('brain')) return '🧠'; if (s.includes('largest meal') || s.includes('lunch') || s.includes('main meal')) return '🍛'; if (s.includes('fast') || s.includes('intermit')) return '⏱️'; if (s.includes('dry brush')) return '🪥'; if (s.includes('walk')) return '🚶'; if (s.includes('sunlight') || s.includes('sun')) return '☀️'; if (s.includes('prayer') || s.includes('mantra')) return '🙏'; if (s.includes('journal')) return '📓'; if (s.includes('stretch')) return '🤸'; if (s.includes('abhyanga') || s.includes('oil massage') || s.includes('sesame')) return '💆'; if (s.includes('coconut') || s.includes('cooling')) return '🥥'; if (s.includes('ginger') || s.includes('spiced')) return '🌶️'; if (s.includes('cold shower')) return '🚿'; if (s.includes('barefoot') || s.includes('earthing')) return '🌿'; if (s.includes('sleep') || s.includes('rest')) return '🌙'; return '✨'; };
  const getAvoidEmoji = (t: string) => { const s = t.toLowerCase(); if (s.includes('oversleep') || (s.includes('sleep') && s.includes('past'))) return '😴'; if (s.includes('screen') || s.includes('phone')) return '📵'; if (s.includes('caffeine') || s.includes('coffee')) return '☕'; if (s.includes('dairy') || s.includes('sweet') || s.includes('sugar')) return '🍬'; if (s.includes('spicy') || s.includes('acidic') || s.includes('acid')) return '🌶️'; if (s.includes('anger') || s.includes('stress') || s.includes('heated')) return '😤'; if (s.includes('cold') || s.includes('raw food')) return '❄️'; if (s.includes('sedent') || s.includes('sitting') || s.includes('long sedent')) return '🪑'; if (s.includes('skip') || s.includes('irregular')) return '🌀'; if (s.includes('excess sleep') || s.includes('> 8')) return '🛌'; return '⚠️'; };

  return (
    <ImageBackground
      source={bgUri ? { uri: bgUri } : undefined}
      style={S.screen}
      imageStyle={{ opacity: 1 }}
    >
      <SafeAreaView style={{ flex: 1 }}>
        {/* HEADER */}
        <View style={S.hdr}>
          <TouchableOpacity hitSlop={{ top: 20, bottom: 20, left: 20, right: 20 }} onPress={() => router.back()} style={S.back} activeOpacity={0.7}>
            <Text style={S.backTxt}>←</Text>
          </TouchableOpacity>
          <View style={{ flex: 1 }}>
            <Text style={S.hdrCap}>AYURVEDIC SCIENCE  ·  CHRONOBIOLOGY</Text>
            <Text style={S.hdrTitle}>Ayurved Science</Text>
          </View>
          <View style={[S.liveBadge, { borderColor: C + '55', backgroundColor: C + '14' }]}>
            <View style={[S.liveDot, { backgroundColor: C }]} />
            <Text style={[S.liveTxt, { color: C }]}>LIVE</Text>
          </View>
        </View>
        <View style={{ height: 1, backgroundColor: '#FFFFFF08', marginHorizontal: 18 }} />

        <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={S.scroll}>

          {/* ══ LIVE NOW HERO ════════════════════════════════════════════════ */}
          <View style={{ borderRadius: 26, overflow: 'hidden', borderWidth: 1, borderColor: C + '35', marginBottom: 6 }}>
            <LinearGradient colors={[C + '2A', C + '0E', 'transparent']} start={{ x: 0, y: 0 }} end={{ x: 0.9, y: 1 }} style={{ padding: 20 }}>
              <View style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 1, backgroundColor: 'rgba(255,255,255,0.28)' }} />
              {/* Badge + time range */}
              <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C + '1C', borderRadius: 20, paddingHorizontal: 11, paddingVertical: 5, borderWidth: 1, borderColor: C + '50' }}>
                  <View style={{ width: 6, height: 6, borderRadius: 3, backgroundColor: C }} />
                  <Text style={{ fontSize: 8, fontWeight: '900', color: C, letterSpacing: 1.8 }}>ACTIVE RIGHT NOW</Text>
                </View>
                {params.periodStart ? <Text style={{ fontSize: 10, color: C + 'AA', fontWeight: '700' }}>{params.periodStart} – {params.periodEnd}</Text> : null}
              </View>
              {/* Ring + details */}
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 18, marginBottom: 16 }}>
                <View style={{ width: 92, height: 92, alignItems: 'center', justifyContent: 'center' }}>
                  <Svg width={92} height={92} viewBox="0 0 92 92">
                    <SvgCircle cx={46} cy={46} r={RR} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth={7} />
                    <SvgCircle cx={46} cy={46} r={RR} fill="none" stroke={C} strokeWidth={7} strokeLinecap="round"
                      strokeDasharray={String(RC)} strokeDashoffset={String(RC * (1 - pdProg))}
                      transform="rotate(-90, 46, 46)" opacity={0.9} />
                  </Svg>
                  <View style={{ position: 'absolute', alignItems: 'center', justifyContent: 'center' }}>
                    <Text style={{ fontSize: 34 }}>{ap.emoji}</Text>
                  </View>
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={{ fontSize: 9, fontWeight: '900', color: C + '80', letterSpacing: 1.4, marginBottom: 5 }}>{ap.elementEquation}</Text>
                  <Text style={{ fontSize: 21, fontWeight: '900', color: '#FFFFFF', lineHeight: 27 }}>{ap.name} Period</Text>
                  <Text style={{ fontSize: 11, color: '#FFFFFF60', marginTop: 3, lineHeight: 16 }}>{ap.tagline}</Text>
                  {pd ? (<>
                    <Text style={{ fontSize: 27, fontWeight: '900', color: C, letterSpacing: -0.5, marginTop: 8 }}>{remStr}</Text>
                    <Text style={{ fontSize: 9, fontWeight: '700', color: '#FFFFFF35', letterSpacing: 0.8 }}>remaining</Text>
                  </>) : null}
                </View>
              </View>
              {/* Progress bar */}
              {pd ? (
                <View style={{ marginBottom: 14 }}>
                  <View style={{ height: 4, backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 2, overflow: 'hidden', marginBottom: 5 }}>
                    <View style={{ height: 4, width: `${Math.round(pdProg * 100)}%` as any, backgroundColor: C, borderRadius: 2, opacity: 0.85 }} />
                  </View>
                  <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                    <Text style={{ fontSize: 9, color: '#FFFFFF30', fontWeight: '600' }}>{Math.round(pdProg * 100)}% through this phase</Text>
                    {params.periodStart ? <Text style={{ fontSize: 9, color: '#FFFFFF30', fontWeight: '600' }}>☀️ {getSunriseRef(params.periodStart, params.periodEnd ?? '')}</Text> : null}
                  </View>
                </View>
              ) : null}
              {/* Western system tag */}
              <View style={{ backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 12, padding: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.09)' }}>
                <Text style={{ fontSize: 9, color: C + '90', fontWeight: '800', letterSpacing: 0.8, lineHeight: 15 }}>⚕  {ap.westernSystem}</Text>
              </View>
            </LinearGradient>
          </View>

          {/* ══ WHAT'S HAPPENING IN YOUR BODY ══════════════════════════════ */}
          {pd ? (
            <View style={{ marginTop: 18, marginBottom: 4 }}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 }}>
                <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
                <Text style={{ fontSize: 8, fontWeight: '900', color: C + '95', letterSpacing: 1.8 }}>⚡  WHAT'S HAPPENING IN YOUR BODY</Text>
                <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
              </View>
              <View style={{ borderRadius: 22, borderWidth: 1, borderColor: C + '30', overflow: 'hidden' }}>
                <LinearGradient colors={[C + '1E', C + '08', 'transparent']} start={{ x: 0, y: 0 }} end={{ x: 0, y: 1 }} style={{ padding: 18 }}>
                  <View style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 1, backgroundColor: 'rgba(255,255,255,0.22)' }} />
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 14 }}>
                    <View style={{ width: 54, height: 54, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: C + '1C', borderWidth: 1, borderColor: C + '45' }}>
                      <Text style={{ fontSize: 28 }}>{pd.sciEmoji}</Text>
                    </View>
                    <View style={{ flex: 1 }}>
                      <Text style={{ fontSize: 7, fontWeight: '900', color: '#38bdf880', letterSpacing: 1.6, marginBottom: 3 }}>🔬  MODERN BIOLOGY</Text>
                      <Text style={{ fontSize: 15, fontWeight: '900', color: C, lineHeight: 22 }}>{pd.sciTitle}</Text>
                    </View>
                  </View>
                  <Text style={{ fontSize: 13, color: '#FFFFFFB0', lineHeight: 22 }}>{pd.sciDesc}</Text>
                  <View style={{ marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.08)' }}>
                    <Text style={{ fontSize: 7, fontWeight: '900', color: '#a78bfa80', letterSpacing: 1.6, marginBottom: 8 }}>🕉  AYURVEDIC UNDERSTANDING</Text>
                    <Text style={{ fontSize: 12, color: '#FFFFFF62', lineHeight: 19, fontStyle: 'italic' }}>
                      {ap.biology.length > 260 ? ap.biology.slice(0, 260) + '…' : ap.biology}
                    </Text>
                  </View>
                </LinearGradient>
              </View>
            </View>
          ) : null}

          {/* ══ DO NOW ═══════════════════════════════════════════════════════ */}
          {pd && pd.activities.length > 0 ? (
            <View style={{ marginTop: 18 }}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 }}>
                <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
                <Text style={{ fontSize: 8, fontWeight: '900', color: C + '95', letterSpacing: 1.8 }}>✦  DO NOW  ·  PHASE-ALIGNED</Text>
                <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
              </View>
              {pd.activities.map((act, i) => (
                <View key={i} style={{ flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 12, borderColor: C + '35', backgroundColor: C + '0C', marginBottom: 9, overflow: 'hidden' }}>
                  <LinearGradient colors={[C + '1A', 'transparent']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={StyleSheet.absoluteFillObject} />
                  <View style={{ width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: C + '1E', borderWidth: 1, borderColor: C + '45' }}>
                    <Text style={{ fontSize: 20 }}>{getActEmoji(act)}</Text>
                  </View>
                  <Text style={{ fontSize: 13, fontWeight: '800', color: '#FFFFFFDD', lineHeight: 18, flex: 1 }}>{act}</Text>
                  <View style={{ width: 24, height: 24, borderRadius: 12, backgroundColor: C + '20', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C + '55' }}>
                    <Text style={{ fontSize: 11, color: C, fontWeight: '900' }}>✓</Text>
                  </View>
                </View>
              ))}
            </View>
          ) : null}

          {/* ══ AVOID NOW ════════════════════════════════════════════════════ */}
          {pd && pd.avoidances.length > 0 ? (
            <View style={{ marginTop: 8, marginBottom: 10 }}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 }}>
                <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
                <Text style={{ fontSize: 8, fontWeight: '900', color: '#f43f5e95', letterSpacing: 1.8 }}>⚠  AVOID NOW  ·  PROTECT YOUR PHASE</Text>
                <View style={{ flex: 1, height: 1, backgroundColor: '#FFFFFF10' }} />
              </View>
              {pd.avoidances.map((av, i) => (
                <View key={i} style={{ flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 12, borderColor: '#f43f5e30', backgroundColor: '#f43f5e09', marginBottom: 9, overflow: 'hidden' }}>
                  <LinearGradient colors={['#f43f5e16', 'transparent']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={StyleSheet.absoluteFillObject} />
                  <View style={{ width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f43f5e18', borderWidth: 1, borderColor: '#f43f5e40' }}>
                    <Text style={{ fontSize: 20 }}>{getAvoidEmoji(av)}</Text>
                  </View>
                  <Text style={{ fontSize: 13, fontWeight: '800', color: '#FFFFFFDD', lineHeight: 18, flex: 1 }}>{av}</Text>
                  <View style={{ width: 24, height: 24, borderRadius: 12, backgroundColor: '#f43f5e18', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#f43f5e40' }}>
                    <Text style={{ fontSize: 11, color: '#f43f5e', fontWeight: '900' }}>✕</Text>
                  </View>
                </View>
              ))}
            </View>
          ) : null}

          {/* ══ WHAT IS AYURVEDA ══════════════════════════════════════════════ */}
          <Divider label="WHAT IS AYURVEDA  ·  THE SCIENCE OF LIFE" color="#a78bfa" />
          <View style={[S.card, { borderColor: '#a78bfa22' }]}>
            <LinearGradient colors={['#a78bfa0B', 'transparent']} style={StyleSheet.absoluteFillObject} />
            <Text style={[S.tag, { color: '#a78bfa90' }]}>🕉️  ETYMOLOGY</Text>
            <Text style={[S.cardH, { color: '#a78bfa', marginTop: 6 }]}>{AYURVEDA.etymology}</Text>
            <Text style={[S.cardSub, { marginTop: 4 }]}>{AYURVEDA.tagline}</Text>
          </View>
          {([
            { title: 'Meaning & Scope', body: AYURVEDA.meaning, color: '#a78bfa' },
            { title: 'Five Elements & Three Doshas', body: AYURVEDA.core, color: '#60a5fa' },
            { title: 'Preventive vs. Curative Medicine', body: AYURVEDA.uniqueness, color: '#34d399' },
            { title: 'Historical Origin & Modern Validation', body: AYURVEDA.origin, color: '#fbbf24' },
          ] as const).map((b, i) => <SciCard key={i} title={b.title} body={b.body} color={b.color} />)}

          {/* ══ 24-HOUR DOSHA CLOCK ════════════════════════════════════════ */}
          <Divider label="DOSHA CLOCK  ·  24-HOUR CIRCADIAN CYCLE" color="#fbbf24" />
          <View style={[S.card, { borderColor: '#fbbf2418' }]}>
            <Text style={[S.tag, { color: '#fbbf2490', marginBottom: 12 }]}>☀️  SOLAR CIRCADIAN RHYTHM</Text>
            <View style={{ flexDirection: 'row', height: 14, gap: 2 }}>
              {([
                { c: '#a78bfa', f: 1.8 }, { c: '#34d399', f: 1.7 }, { c: '#fb923c', f: 1.7 },
                { c: '#a78bfa', f: 1.8 }, { c: '#34d399', f: 1.7 }, { c: '#fbbf24', f: 1.7 },
              ] as const).map((s, i, a) => (
                <View key={i} style={{ flex: s.f, backgroundColor: s.c, borderTopLeftRadius: i === 0 ? 7 : 0, borderBottomLeftRadius: i === 0 ? 7 : 0, borderTopRightRadius: i === a.length - 1 ? 7 : 0, borderBottomRightRadius: i === a.length - 1 ? 7 : 0 }} />
              ))}
            </View>
            <View style={{ flexDirection: 'row', marginTop: 6 }}>
              {([
                { c: '#a78bfa', f: 1.8, l: 'Vata', t: '2–6a' }, { c: '#34d399', f: 1.7, l: 'Kapha', t: '6–10a' },
                { c: '#fb923c', f: 1.7, l: 'Pitta', t: '10–2p' }, { c: '#a78bfa', f: 1.8, l: 'Vata', t: '2–6p' },
                { c: '#34d399', f: 1.7, l: 'Kapha', t: '6–10p' }, { c: '#fbbf24', f: 1.7, l: 'Pitta', t: '10–2a' },
              ] as const).map((s, i) => (
                <View key={i} style={{ flex: s.f, alignItems: 'center' }}>
                  <Text style={{ fontSize: 7, color: s.c, fontWeight: '900' }}>{s.l}</Text>
                  <Text style={{ fontSize: 5.5, color: '#FFFFFF35' }}>{s.t}</Text>
                </View>
              ))}
            </View>
            <Text style={[S.infoTxt, { marginTop: 14, color: '#FFFFFF58' }]}>The Dosha clock shifts daily with your local sunrise & sunset. It runs on solar time, not fixed clock time — hyper-personalised to your exact location and season.</Text>
          </View>

          {/* ══ THREE DOSHAS ══════════════════════════════════════════════════ */}
          <Divider label="THE THREE DOSHAS  ·  TRIDOSHA SCIENCE" color="#FFFFFF" />
          <View style={S.tabs}>
            {ORDER.map(k => {
              const ia = sel === k, inow = adk === k;
              return (
                <TouchableOpacity key={k} onPress={() => setSel(k)} activeOpacity={0.8} style={[S.tab, ia && { borderBottomColor: DOSHAS_FULL[k].color, borderBottomWidth: 2 }]}>
                  <Text style={{ fontSize: 18 }}>{DOSHAS_FULL[k].emoji}</Text>
                  <Text style={[S.tabTxt, { color: ia ? DOSHAS_FULL[k].color : '#FFFFFF35' }]}>{DOSHAS_FULL[k].name}</Text>
                  {inow && <View style={[S.tabDot, { backgroundColor: DOSHAS_FULL[k].color }]} />}
                </TouchableOpacity>
              );
            })}
          </View>

          <SciCard title={'🔬  ' + d.name + '  —  Biological Mapping'} subtitle={d.westernSystem} body={d.biology} color={d.color} />

          <View style={[S.card, { borderColor: d.color + '22' }]}>
            <Text style={[S.tag, { color: d.color + '80' }]}>⚗  KEY BIOCHEMICALS  ·  HORMONES & NEUROTRANSMITTERS</Text>
            {d.neuro.map((n, i) => (
              <View key={i} style={{ marginTop: 10, borderWidth: 1, borderColor: d.color + '22', borderRadius: 14, padding: 13, backgroundColor: d.color + '07' }}>
                <Text style={{ fontSize: 13, fontWeight: '800', color: d.color + 'EE' }}>{n.name}</Text>
                <Text style={{ fontSize: 12, color: '#FFFFFF62', lineHeight: 19, marginTop: 4 }}>{n.role}</Text>
              </View>
            ))}
          </View>

          <View style={[S.card, { borderColor: d.color + '22' }]}>
            <Text style={[S.tag, { color: d.color + '80' }]}>⏰  CIRCADIAN PEAK WINDOWS  ·  CHRONOBIOLOGY</Text>
            {d.peakWindows.map((w, i) => (
              <View key={i} style={{ marginTop: 16 }}>
                <View style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 8 }}>
                  <Text style={{ fontSize: 22 }}>{w.icon}</Text>
                  <View style={{ flex: 1 }}>
                    <View style={[S.chip, { borderColor: d.color + '50', backgroundColor: d.color + '18', alignSelf: 'flex-start' }]}>
                      <Text style={{ fontSize: 12, fontWeight: '900', color: d.color }}>{w.time}</Text>
                    </View>
                    {SUNRISE_REF[w.time] ? (
                      <Text style={{ fontSize: 10, color: d.color + '75', fontWeight: '700', marginTop: 5, letterSpacing: 0.3 }}>☀️  {SUNRISE_REF[w.time]}</Text>
                    ) : null}
                  </View>
                </View>
                <Text style={{ fontSize: 12, color: '#FFFFFF65', lineHeight: 20 }}>{w.science}</Text>
              </View>
            ))}
          </View>

          <View style={[S.card, { borderColor: d.color + '20' }]}>
            <Text style={[S.tag, { color: d.color + '80' }]}>⚡  BODY SYSTEMS GOVERNED</Text>
            {d.functions.map((f, i) => (
              <View key={i} style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginTop: 13 }}>
                <Text style={{ fontSize: 20, minWidth: 28 }}>{f.icon}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={{ fontSize: 13, fontWeight: '800', color: d.color + 'EE' }}>{f.name}</Text>
                  <Text style={{ fontSize: 11, color: '#FFFFFF52', lineHeight: 17, marginTop: 3 }}>{f.detail}</Text>
                </View>
              </View>
            ))}
          </View>

          <View style={{ flexDirection: 'row', gap: 10 }}>
            <View style={[S.halfCard, { borderColor: d.color + '28', flex: 1 }]}>
              <Text style={[S.tag, { color: d.color + '80', marginBottom: 10 }]}>✓  DO NOW</Text>
              {d.doNow.map((a, i) => (
                <View key={i} style={{ flexDirection: 'row', gap: 7, marginBottom: 9 }}>
                  <Text style={{ color: d.color, fontWeight: '900', fontSize: 12, marginTop: 1 }}>✓</Text>
                  <Text style={{ fontSize: 11, color: '#FFFFFFCC', lineHeight: 17, flex: 1 }}>{a}</Text>
                </View>
              ))}
            </View>
            <View style={[S.halfCard, { borderColor: '#f43f5e28', flex: 1 }]}>
              <Text style={[S.tag, { color: '#f43f5e80', marginBottom: 10 }]}>✕  AVOID</Text>
              {d.avoid.map((a, i) => (
                <View key={i} style={{ flexDirection: 'row', gap: 7, marginBottom: 9 }}>
                  <Text style={{ color: '#f43f5e', fontWeight: '900', fontSize: 12, marginTop: 1 }}>✕</Text>
                  <Text style={{ fontSize: 11, color: '#FFFFFF65', lineHeight: 17, flex: 1 }}>{a}</Text>
                </View>
              ))}
            </View>
          </View>

          <View style={[S.card, { borderColor: '#f43f5e18' }]}>
            <Text style={[S.tag, { color: '#f43f5e80' }]}>⚠  SIGNS OF IMBALANCE</Text>
            {d.imbalance.map((it, i) => (
              <View key={i} style={{ marginTop: 10, borderWidth: 1, borderColor: '#f43f5e22', borderRadius: 15, padding: 13, backgroundColor: '#f43f5e07' }}>
                <Text style={{ fontSize: 13, fontWeight: '800', color: '#f43f5eCC', marginBottom: 5 }}>{it.symptom}</Text>
                <Text style={{ fontSize: 12, color: '#FFFFFF55', lineHeight: 19 }}>{it.science}</Text>
              </View>
            ))}
          </View>

          <View style={[S.card, { borderColor: d.color + '18' }]}>
            <Text style={[S.tag, { color: d.color + '80' }]}>◎  REBALANCING PRACTICES  ·  EVIDENCE-BASED</Text>
            {d.balance.map((b, i) => (
              <View key={i} style={{ marginTop: 10, borderWidth: 1, borderColor: d.color + '22', borderRadius: 15, padding: 13, backgroundColor: d.color + '07' }}>
                <Text style={{ fontSize: 13, fontWeight: '800', color: d.color + 'EE', marginBottom: 5 }}>{b.practice}</Text>
                <Text style={{ fontSize: 12, color: '#FFFFFF55', lineHeight: 19 }}>{b.science}</Text>
              </View>
            ))}
          </View>

          {/* ══ SHAD RASA  ════════════════════════════════════════════════════ */}
          <Divider label="SHAD RASA  ·  THE SIX TASTES OF AYURVEDA" color="#fbbf24" />
          <View style={[S.card, { borderColor: '#fbbf2418' }]}>
            <LinearGradient colors={['#fbbf2408', 'transparent']} style={StyleSheet.absoluteFillObject} />
            <Text style={[S.tag, { color: '#fbbf2490' }]}>🌿  RASA SCIENCE</Text>
            <Text style={[S.infoTxt, { marginTop: 8 }]}>Ayurveda identifies six fundamental tastes (Shad Rasa). Eating all six daily ensures complete nutritional and bio-energetic balance. Each taste maps to elemental forces, dosha effects, and specific receptor pathways confirmed by modern phytochemistry.</Text>
          </View>
          {SHAD_RASA.map((r, i) => (
            <TouchableOpacity key={i} onPress={() => setRasaOpen(rasaOpen === r.name ? null : r.name)} activeOpacity={0.8}>
              <View style={[S.expandCard, { borderColor: r.color + (rasaOpen === r.name ? '55' : '22') }]}>
                {rasaOpen === r.name && <LinearGradient colors={[r.color + '12', 'transparent']} style={StyleSheet.absoluteFillObject} />}
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>
                  <Text style={{ fontSize: 30 }}>{r.emoji}</Text>
                  <View style={{ flex: 1 }}>
                    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                      <Text style={{ fontSize: 16, fontWeight: '900', color: r.color }}>{r.name}</Text>
                      <Text style={{ fontSize: 11, color: '#FFFFFF50', fontWeight: '700' }}>{r.english}</Text>
                    </View>
                    <Text style={{ fontSize: 10, color: '#FFFFFF50', marginTop: 3, lineHeight: 15 }}>{r.elements}  ·  {r.effect}</Text>
                  </View>
                  <Text style={{ color: r.color, fontSize: 12, fontWeight: '900' }}>{rasaOpen === r.name ? '▲' : '▼'}</Text>
                </View>
                {rasaOpen === r.name && (
                  <View style={{ marginTop: 14, gap: 10 }}>
                    <View style={[S.infoBox, { borderColor: r.color + '35', backgroundColor: r.color + '0D' }]}>
                      <Text style={[S.infoLabel, { color: r.color + '90' }]}>DOSHA IMPACT</Text>
                      <Text style={{ fontSize: 13, color: r.color + 'EE', fontWeight: '800', lineHeight: 19 }}>{r.dosha}</Text>
                    </View>
                    <View style={[S.infoBox, { borderColor: '#FFFFFF14' }]}>
                      <Text style={S.infoLabel}>FOOD SOURCES</Text>
                      <Text style={{ fontSize: 12, color: '#FFFFFFCC', lineHeight: 19 }}>{r.examples}</Text>
                    </View>
                    <View style={[S.infoBox, { borderColor: '#FFFFFF14' }]}>
                      <Text style={S.infoLabel}>BIOCHEMISTRY</Text>
                      <Text style={{ fontSize: 12, color: '#FFFFFF68', lineHeight: 20 }}>{r.science}</Text>
                    </View>
                  </View>
                )}
              </View>
            </TouchableOpacity>
          ))}

          {/* ══ PRAKRITI ══════════════════════════════════════════════════════ */}
          <Divider label="PRAKRITI  ·  YOUR CONSTITUTIONAL TYPE" color="#34d399" />
          <View style={[S.card, { borderColor: '#34d39918' }]}>
            <LinearGradient colors={['#34d39908', 'transparent']} style={StyleSheet.absoluteFillObject} />
            <Text style={[S.tag, { color: '#34d39990' }]}>🧬  WHAT IS PRAKRITI?</Text>
            <Text style={[S.infoTxt, { marginTop: 8 }]}>Prakriti is your unique constitutional blueprint — the innate ratio of Vata, Pitta, and Kapha established at conception. It determines your physical characteristics, metabolic tendencies, psychological patterns, and disease susceptibilities. Understanding your Prakriti is the foundation of personalised Ayurvedic recommendations.</Text>
          </View>
          {PRAKRITI_TYPES.map((p, i) => (
            <TouchableOpacity key={i} onPress={() => setPrakOpen(prakOpen === p.type ? null : p.type)} activeOpacity={0.8}>
              <View style={[S.expandCard, { borderColor: p.color + (prakOpen === p.type ? '50' : '22') }]}>
                {prakOpen === p.type && <LinearGradient colors={[p.color + '10', 'transparent']} style={StyleSheet.absoluteFillObject} />}
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>
                  <Text style={{ fontSize: 28 }}>{p.emoji}</Text>
                  <View style={{ flex: 1 }}>
                    <Text style={{ fontSize: 15, fontWeight: '900', color: p.color }}>{p.type}</Text>
                    <Text style={{ fontSize: 10, color: '#FFFFFF50', marginTop: 3, lineHeight: 15 }}>{p.body}</Text>
                  </View>
                  <Text style={{ color: p.color, fontSize: 12, fontWeight: '900' }}>{prakOpen === p.type ? '▲' : '▼'}</Text>
                </View>
                {prakOpen === p.type && (
                  <View style={{ marginTop: 14, gap: 10 }}>
                    {([
                      { label: 'MIND & PERSONALITY', val: p.mind },
                      { label: 'STRENGTHS', val: p.strength },
                      { label: 'CHALLENGES', val: p.challenge },
                      { label: 'IDEAL DIET', val: p.diet },
                      { label: 'DAILY ROUTINE', val: p.routine },
                    ] as const).map((row, j) => (
                      <View key={j} style={[S.infoBox, { borderColor: p.color + '25', backgroundColor: p.color + '09' }]}>
                        <Text style={[S.infoLabel, { color: p.color + '90' }]}>{row.label}</Text>
                        <Text style={{ fontSize: 12, color: '#FFFFFFCC', lineHeight: 19 }}>{row.val}</Text>
                      </View>
                    ))}
                  </View>
                )}
              </View>
            </TouchableOpacity>
          ))}

          {/* ══ CLOSING ════════════════════════════════════════════════════ */}
          <View style={[S.card, { borderColor: '#a78bfa28', marginTop: 24 }]}>
            <LinearGradient colors={['#a78bfa0C', '#7c3aed06', 'transparent']} style={StyleSheet.absoluteFillObject} />
            <Text style={{ fontSize: 36, textAlign: 'center', marginBottom: 12 }}>🕉️</Text>
            <Text style={{ fontSize: 18, fontWeight: '900', color: '#a78bfa', textAlign: 'center', marginBottom: 14, letterSpacing: -0.3 }}>Ayurveda: The Eye of Life</Text>
            <Text style={[S.infoTxt, { fontSize: 13, lineHeight: 22, color: '#FFFFFF72' }]}>{'The 3-Dosha system is a 5,000-year-old circadian biology framework mapping the body\'s 24-hour hormonal oscillations to three elemental archetypes. The 2017 Nobel Prize in Physiology confirmed that every cell runs a molecular CLOCK gene — matching Vata/Pitta/Kapha periods with remarkable precision.\n\nThe Shad Rasa maps to modern phytochemistry. Prakriti maps to metabolic phenotypes. The ancients encoded what science is rediscovering — that the cosmos is not separate from your body.'}</Text>
            <View style={{ height: 1, backgroundColor: '#FFFFFF10', marginVertical: 16 }} />
            <Text style={{ fontSize: 11, color: '#FFFFFF50', lineHeight: 18 }}>🔬  Doshas shift with your local sunrise & sunset — hyper-personalised to your exact location. Solar chronobiology, not fixed clock time.</Text>
          </View>
          <View style={{ height: 50 }} />

        </ScrollView>
      </SafeAreaView>
    </ImageBackground>
  );
}

const S = StyleSheet.create({
  screen:    { flex: 1, backgroundColor: '#06061a' },
  hdr:       { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingTop: 16, paddingBottom: 12, gap: 12 },
  back:      { width: 40, height: 40, borderRadius: 20, backgroundColor: '#FFFFFF0A', borderWidth: 1, borderColor: '#FFFFFF18', alignItems: 'center', justifyContent: 'center' },
  backTxt:   { fontSize: 20, color: '#FFFFFFEE', fontWeight: '200' },
  hdrCap:    { fontSize: 8, fontWeight: '900', color: '#FFFFFF45', letterSpacing: 2.2, marginBottom: 3 },
  hdrTitle:  { fontSize: 22, fontWeight: '900', color: '#FFFFFFEE', letterSpacing: -0.5 },
  liveBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, borderWidth: 1, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5 },
  liveDot:   { width: 6, height: 6, borderRadius: 3 },
  liveTxt:   { fontSize: 8, fontWeight: '900', letterSpacing: 1.4 },
  scroll:    { paddingHorizontal: 16, paddingTop: 12 },
  hero:      { borderRadius: 24, borderWidth: 1, overflow: 'hidden', padding: 18, marginBottom: 10 },
  heroName:  { fontSize: 30, fontWeight: '900', letterSpacing: -0.5 },
  nowBadge:  { flexDirection: 'row', alignItems: 'center', gap: 5, borderWidth: 1, borderRadius: 20, paddingHorizontal: 9, paddingVertical: 4, alignSelf: 'flex-start' },
  nowDot:    { width: 6, height: 6, borderRadius: 3 },
  nowTxt:    { fontSize: 8, fontWeight: '900', letterSpacing: 1.2 },
  card:      { borderWidth: 1, borderRadius: 22, padding: 18, marginBottom: 12, overflow: 'hidden' },
  sciCard:   { borderWidth: 1, borderRadius: 18, padding: 16, marginBottom: 12, backgroundColor: '#FFFFFF05' },
  sciCardTitle: { fontSize: 13, fontWeight: '900', color: '#FFFFFFCC', marginBottom: 6 },
  sciCardBody:  { fontSize: 12, color: '#FFFFFF68', lineHeight: 20 },
  tag:       { fontSize: 9, fontWeight: '900', letterSpacing: 1.8, marginBottom: 4 },
  cardH:     { fontSize: 17, fontWeight: '900' },
  cardSub:   { fontSize: 13, color: '#FFFFFF65' },
  infoBox:   { borderWidth: 1, borderRadius: 14, padding: 13 },
  infoLabel: { fontSize: 8, fontWeight: '900', color: '#FFFFFF45', letterSpacing: 1.5, marginBottom: 5 },
  infoTxt:   { fontSize: 12, color: '#FFFFFF68', lineHeight: 20 },
  tabs:      { flexDirection: 'row', marginBottom: 12, borderRadius: 20, backgroundColor: '#FFFFFF06', borderWidth: 1, borderColor: '#FFFFFF0C', overflow: 'hidden' },
  tab:       { flex: 1, alignItems: 'center', paddingVertical: 12, gap: 3, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabTxt:    { fontSize: 13, fontWeight: '900' },
  tabDot:    { width: 5, height: 5, borderRadius: 3, position: 'absolute', top: 6, right: 10 },
  chip:      { borderWidth: 1, borderRadius: 20, paddingHorizontal: 11, paddingVertical: 5, alignSelf: 'flex-start' },
  halfCard:  { borderWidth: 1, borderRadius: 20, padding: 16 },
  expandCard:{ borderWidth: 1, borderRadius: 22, padding: 16, marginBottom: 12, overflow: 'hidden' },
});
