/**
 * OrbitPulseGame.tsx — "Mind Mario" Mental Health Platformer
 * ─────────────────────────────────────────────────────────────────
 * A premium Super Mario-inspired 2D platformer built for mental health
 * and calming benefit. Runs fully on the UI thread via Reanimated.
 *
 * Architecture:
 *  - Player is fixed at screen X = W * 0.25, world scrolls right-to-left
 *  - Screen-space Y: 0 = top, increases downward (standard)
 *  - Ground at GROUND_Y = H * 0.72 (screen coords, constant reference)
 *  - Camera only tracks vertical (Y) movement of player
 *  - All physics in screen-space for correctness
 */

import React, { useRef, useState, useEffect, useCallback } from 'react';
import {
  View, Text, Modal, StyleSheet, TouchableOpacity,
  Dimensions, Platform, BackHandler
} from 'react-native';
import Svg, {
  Rect, Circle, Path, G, Defs, Stop,
  LinearGradient as SvgLinearGradient,
  RadialGradient as SvgRadialGradient,
  Text as SvgText,
  Polygon, Ellipse
} from 'react-native-svg';
import { BlurView } from 'expo-blur';
import { LinearGradient } from 'expo-linear-gradient';
import * as Haptics from 'expo-haptics';
import { Audio } from 'expo-av';
import { useSoundPlayer } from '@/lib/soundPlayerContext';
import { ALL_SLEEP_SOUNDS } from '@/lib/sleepSoundsData';
import { Ionicons } from '@expo/vector-icons';
import { GestureHandlerRootView, GestureDetector, Gesture } from 'react-native-gesture-handler';
import Animated, {
  useSharedValue,
  useAnimatedProps,
  useAnimatedStyle,
  useFrameCallback,
  withTiming,
  withSequence,
  withRepeat,
  runOnJS,
  Easing,
  interpolate,
} from 'react-native-reanimated';
import type { SharedValue } from 'react-native-reanimated';

// ─── Screen Constants ────────────────────────────────────────────────────────
const { width: W, height: H } = Dimensions.get('window');

// ─── Game Constants ──────────────────────────────────────────────────────────
const PLAYER_SCREEN_X = W * 0.22;      // Player fixed horizontal screen position
const PLAYER_W = 32;
const PLAYER_H = 44;
const GROUND_Y = H * 0.72;            // Y position of the top surface of the ground (screen coords)
const GRAVITY = 1600;                  // px/s²
const JUMP_VY = -620;                  // Initial jump vertical velocity (negative = up)
const DOUBLE_JUMP_VY = -560;
const MAX_FALL_VY = 900;
const WORLD_SPEED_INIT = 200;          // px/s world scroll speed
const WORLD_SPEED_MAX = 480;
const WORLD_ACCEL = 4;                 // px/s² world acceleration
const COIN_SCORE = 100;
const OM_HIT_URL = 'https://audio.onesutralabs.com/om.mp3';
const TANPURA_SOUND_ID = 'cdn_new_8';

// ─── World Generation ────────────────────────────────────────────────────────
// Everything is generated by chunk index (pseudo-random deterministic)
const CHUNK_W = 600;

// Platforms: { x, y, w } in world coords (y = screen y of platform top surface)
const getPlatformsInChunk = (chunkIdx: number): Array<{ x: number; y: number; w: number; id: number }> => {
  'worklet';
  const platforms: Array<{ x: number; y: number; w: number; id: number }> = [];
  const seed1 = Math.abs(Math.sin(chunkIdx * 127.1 + 311.7)) * 43758.5453;
  const r1 = seed1 - Math.floor(seed1);
  const seed2 = Math.abs(Math.sin(chunkIdx * 269.5 + 183.3)) * 53758.5453;
  const r2 = seed2 - Math.floor(seed2);

  // Every other chunk has a floating platform
  if (chunkIdx > 1 && r1 > 0.3) {
    const px = chunkIdx * CHUNK_W + r1 * 300 + 100;
    const py = GROUND_Y - 90 - r2 * 100; // Float 90-190px above ground
    const pw = 90 + r2 * 100;
    platforms.push({ x: px, y: py, w: pw, id: chunkIdx * 10 + 1 });
  }
  // Occasionally a second, higher platform
  if (chunkIdx > 2 && r2 > 0.65) {
    const px = chunkIdx * CHUNK_W + r2 * 200 + 300;
    const py = GROUND_Y - 180 - r1 * 60;
    const pw = 70 + r1 * 60;
    platforms.push({ x: px, y: py, w: pw, id: chunkIdx * 10 + 2 });
  }
  return platforms;
};

// Coins: { x, y, id, label }
const AFFIRMATIONS = ['JOY', 'CALM', 'BREATHE', 'FLOW', 'PEACE', 'LOVE', 'HEAL', 'REST'];
const getCoinsInChunk = (chunkIdx: number): Array<{ x: number; y: number; id: number; label: string }> => {
  'worklet';
  if (chunkIdx < 1) return [];
  const coins: Array<{ x: number; y: number; id: number; label: string }> = [];
  const seed = Math.abs(Math.sin(chunkIdx * 75.3 + 457.1)) * 23758.5453;
  const r = seed - Math.floor(seed);
  const seed2 = Math.abs(Math.sin(chunkIdx * 132.7 + 89.2)) * 31234.5;
  const r2 = seed2 - Math.floor(seed2);

  // Arc of 3 coins floating above ground or platform
  const baseX = chunkIdx * CHUNK_W + 120 + r * 200;
  const baseY = GROUND_Y - 80 - r2 * 120;
  const labelIdx = Math.floor(r * AFFIRMATIONS.length) % AFFIRMATIONS.length;
  for (let i = 0; i < 3; i++) {
    coins.push({
      x: baseX + i * 50,
      y: baseY - Math.sin(i * Math.PI / 2) * 30,
      id: chunkIdx * 100 + i,
      label: i === 1 ? AFFIRMATIONS[labelIdx] : '',
    });
  }
  // Occasional single coin on platform
  if (r > 0.5) {
    const platforms = getPlatformsInChunk(chunkIdx);
    if (platforms.length > 0) {
      const plat = platforms[0];
      coins.push({ x: plat.x + plat.w / 2, y: plat.y - 45, id: chunkIdx * 100 + 10, label: '' });
    }
  }
  return coins;
};

// Obstacles: { x, y, w, h, id, type }
const getObstaclesInChunk = (chunkIdx: number): Array<{ x: number; y: number; w: number; h: number; id: number; type: string }> => {
  'worklet';
  if (chunkIdx < 3) return [];
  const seed = Math.abs(Math.sin(chunkIdx * 211.3 + 19.1)) * 63758.5453;
  const r = seed - Math.floor(seed);
  if (r < 0.4) return [];
  // Thorn/stress block sitting on the ground
  const ox = chunkIdx * CHUNK_W + 400 + r * 150;
  return [{
    x: ox, y: GROUND_Y - 36, w: 30, h: 36, id: chunkIdx * 1000,
    type: r > 0.7 ? 'cloud' : 'thorn',
  }];
};

// ─── Animated SVG Components ─────────────────────────────────────────────────
const AnimatedRect = Animated.createAnimatedComponent(Rect);
const AnimatedG = Animated.createAnimatedComponent(G);

// ─── Static Parallax Background ─────────────────────────────────────────────
const ParallaxBackground = React.memo(({ worldX }: { worldX: SharedValue<number> }) => {
  // Distant mountains layer (parallax ratio 0.1)
  const mtStyle = useAnimatedStyle(() => ({
    transform: [{ translateX: -(worldX.value * 0.1) % W }],
  }));
  // Mid trees layer (parallax ratio 0.3)
  const treeStyle = useAnimatedStyle(() => ({
    transform: [{ translateX: -(worldX.value * 0.3) % W }],
  }));
  // Near clouds layer (parallax ratio 0.2)
  const cloudStyle = useAnimatedStyle(() => ({
    transform: [{ translateX: -(worldX.value * 0.2) % (W * 2) }],
  }));

  return (
    <View style={StyleSheet.absoluteFillObject} pointerEvents="none">
      {/* Sky gradient */}
      <LinearGradient
        colors={['#1a0533', '#2d1155', '#4a2070', '#7c3aed', '#a855f7', '#c084fc', '#f0abfc']}
        style={StyleSheet.absoluteFillObject}
        start={{ x: 0, y: 0 }} end={{ x: 0, y: 1 }}
      />
      {/* Stars */}
      <Svg width={W} height={H * 0.6} style={{ position: 'absolute', top: 0, left: 0 }}>
        {Array.from({ length: 40 }).map((_, i) => {
          const sx = ((i * 137.5) % 1) * W;
          const sy = ((i * 73.3) % 1) * H * 0.55;
          const sr = i % 3 === 0 ? 2.5 : 1.5;
          return <Circle key={i} cx={sx} cy={sy} r={sr} fill="rgba(255,255,255,0.7)" />;
        })}
      </Svg>

      {/* Distant mountains (parallax 0.1) — tiled x2 for seamless scroll */}
      <Animated.View style={[{ position: 'absolute', bottom: H * 0.27, left: 0, width: W * 3, height: 160 }, mtStyle]} pointerEvents="none">
        <Svg width={W * 3} height={160}>
          {[0, 1, 2].map(tile => (
            <G key={tile} transform={`translate(${tile * W},0)`}>
              {/* Peak 1 */}
              <Path d={`M0,160 L${W*0.15},40 L${W*0.3},160 Z`} fill="rgba(60,20,100,0.55)" />
              <Path d={`M${W*0.2},160 L${W*0.38},20 L${W*0.56},160 Z`} fill="rgba(80,30,130,0.5)" />
              <Path d={`M${W*0.5},160 L${W*0.65},55 L${W*0.8},160 Z`} fill="rgba(60,20,100,0.55)" />
              <Path d={`M${W*0.7},160 L${W*0.88},30 L${W},160 Z`} fill="rgba(100,40,160,0.45)" />
              {/* Snow caps */}
              <Path d={`M${W*0.15},40 L${W*0.12},65 L${W*0.18},65 Z`} fill="rgba(255,255,255,0.3)" />
              <Path d={`M${W*0.38},20 L${W*0.34},50 L${W*0.42},50 Z`} fill="rgba(255,255,255,0.3)" />
              <Path d={`M${W*0.65},55 L${W*0.62},75 L${W*0.68},75 Z`} fill="rgba(255,255,255,0.25)" />
              <Path d={`M${W*0.88},30 L${W*0.85},58 L${W*0.91},58 Z`} fill="rgba(255,255,255,0.3)" />
            </G>
          ))}
        </Svg>
      </Animated.View>

      {/* Mid trees (parallax 0.3) */}
      <Animated.View style={[{ position: 'absolute', bottom: H * 0.27, left: 0, width: W * 4, height: 100 }, treeStyle]} pointerEvents="none">
        <Svg width={W * 4} height={100}>
          {Array.from({ length: 24 }).map((_, i) => {
            const tx = i * (W / 5) + ((i * 47) % 60);
            const th = 55 + (i % 3) * 20;
            const tw = 18 + (i % 4) * 8;
            const treeColor = i % 2 === 0 ? 'rgba(20,80,20,0.75)' : 'rgba(30,100,30,0.65)';
            return (
              <G key={i}>
                <Rect x={tx + tw/2 - 5} y={th - 15} width={10} height={20} fill="rgba(80,40,10,0.5)" />
                <Ellipse cx={tx + tw/2} cy={100 - th} rx={tw/2} ry={th * 0.45} fill={treeColor} />
              </G>
            );
          })}
        </Svg>
      </Animated.View>

      {/* Clouds (parallax 0.2) */}
      <Animated.View style={[{ position: 'absolute', top: H * 0.05, left: 0, width: W * 4, height: 120 }, cloudStyle]} pointerEvents="none">
        <Svg width={W * 4} height={120}>
          {[
            { x: W*0.1, y: 20, s: 1.0 }, { x: W*0.45, y: 50, s: 0.7 },
            { x: W*0.8, y: 15, s: 1.2 }, { x: W*1.2, y: 40, s: 0.8 },
            { x: W*1.6, y: 25, s: 1.1 }, { x: W*2.0, y: 55, s: 0.75 },
            { x: W*2.4, y: 18, s: 1.0 }, { x: W*2.8, y: 42, s: 0.9 },
            { x: W*3.2, y: 30, s: 1.15 }, { x: W*3.6, y: 20, s: 0.85 },
          ].map((c, i) => (
            <G key={i} transform={`translate(${c.x},${c.y}) scale(${c.s})`}>
              <Ellipse cx={40} cy={25} rx={40} ry={20} fill="rgba(255,255,255,0.12)" />
              <Ellipse cx={65} cy={20} rx={30} ry={18} fill="rgba(255,255,255,0.1)" />
              <Ellipse cx={20} cy={22} rx={22} ry={15} fill="rgba(255,255,255,0.1)" />
            </G>
          ))}
        </Svg>
      </Animated.View>

      {/* Ground gradient fill below GROUND_Y */}
      <LinearGradient
        colors={['#15803d', '#166534', '#14532d', '#0f2a18']}
        style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: H * 0.29 }}
        start={{ x: 0, y: 0 }} end={{ x: 0, y: 1 }}
      />
    </View>
  );
});

// ─── Ground Tiles (Mario-style) ──────────────────────────────────────────────
const GroundTiles = React.memo(({ worldX }: { worldX: SharedValue<number> }) => {
  const tileStyle = useAnimatedStyle(() => {
    const offset = worldX.value % 40; // tile width = 40
    return { transform: [{ translateX: -offset }] };
  });
  const tileCount = Math.ceil(W / 40) + 2;
  return (
    <Animated.View style={[{ position: 'absolute', top: GROUND_Y, left: -40, width: W + 80, height: H - GROUND_Y }, tileStyle]} pointerEvents="none">
      <Svg width={W + 80} height={H - GROUND_Y}>
        <Defs>
          <SvgLinearGradient id="grassGrad" x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0" stopColor="#22c55e" stopOpacity="1" />
            <Stop offset="0.08" stopColor="#16a34a" stopOpacity="1" />
            <Stop offset="0.09" stopColor="#854d0e" stopOpacity="1" />
            <Stop offset="1" stopColor="#1c0a00" stopOpacity="1" />
          </SvgLinearGradient>
        </Defs>
        {Array.from({ length: tileCount }).map((_, i) => (
          <G key={i}>
            {/* Tile fill */}
            <Rect x={i * 40} y={0} width={40} height={H - GROUND_Y} fill="url(#grassGrad)" />
            {/* Tile border */}
            <Rect x={i * 40} y={0} width={40} height={H - GROUND_Y} fill="none" stroke="rgba(0,0,0,0.3)" strokeWidth={1} />
            {/* Grass blades */}
            <Path d={`M${i*40+5},0 Q${i*40+7},-8 ${i*40+9},0`} stroke="#4ade80" strokeWidth={1.5} fill="none" />
            <Path d={`M${i*40+18},0 Q${i*40+20},-10 ${i*40+22},0`} stroke="#4ade80" strokeWidth={1.5} fill="none" />
            <Path d={`M${i*40+31},0 Q${i*40+33},-7 ${i*40+35},0`} stroke="#4ade80" strokeWidth={1.5} fill="none" />
            {/* Underground soil dots */}
            <Circle cx={i*40+10} cy={15} r={3} fill="rgba(180,120,60,0.3)" />
            <Circle cx={i*40+28} cy={25} r={2.5} fill="rgba(180,120,60,0.25)" />
          </G>
        ))}
      </Svg>
    </Animated.View>
  );
});

// ─── Platform renderer ───────────────────────────────────────────────────────
const WorldPlatforms = React.memo(({ worldX }: { worldX: SharedValue<number> }) => {
  const platProps = useAnimatedProps(() => {
    // We render up to 3 chunks around current position
    return { d: '' }; // placeholder, actual rendering below
  });

  // We use animated style on a wrapping view instead for correct rendering
  const containerStyle = useAnimatedStyle(() => ({
    transform: [{ translateX: -worldX.value }],
  }));

  // Static platform SVG spanning many chunks
  const chunks = Array.from({ length: 40 }, (_, i) => i);
  const allPlatforms = chunks.flatMap(ci => getPlatformsInChunk(ci));

  return (
    <Animated.View style={[{ position: 'absolute', top: 0, left: 0, width: 40 * CHUNK_W, height: H }, containerStyle]} pointerEvents="none">
      <Svg width={40 * CHUNK_W} height={H}>
        <Defs>
          <SvgLinearGradient id="brickGrad" x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0" stopColor="#c2410c" stopOpacity="1" />
            <Stop offset="1" stopColor="#7c2d12" stopOpacity="1" />
          </SvgLinearGradient>
          <SvgLinearGradient id="brickTop" x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0" stopColor="#f97316" stopOpacity="1" />
            <Stop offset="1" stopColor="#c2410c" stopOpacity="1" />
          </SvgLinearGradient>
        </Defs>
        {allPlatforms.map(p => {
          const brickW = 30;
          const brickCount = Math.ceil(p.w / brickW);
          return (
            <G key={p.id}>
              {/* Platform base */}
              <Rect x={p.x} y={p.y} width={p.w} height={22} fill="url(#brickGrad)" rx={3} />
              <Rect x={p.x} y={p.y} width={p.w} height={5} fill="url(#brickTop)" rx={2} />
              {/* Brick joints */}
              {Array.from({ length: brickCount }).map((_, bi) => (
                <G key={bi}>
                  <Rect x={p.x + bi * brickW} y={p.y + 5} width={brickW} height={17} fill="none" stroke="rgba(0,0,0,0.3)" strokeWidth={1} />
                  {/* Sheen */}
                  <Rect x={p.x + bi * brickW + 2} y={p.y + 7} width={brickW - 4} height={3} fill="rgba(255,255,255,0.12)" rx={1} />
                </G>
              ))}
              {/* Edge highlight */}
              <Rect x={p.x} y={p.y} width={p.w} height={22} fill="none" stroke="rgba(255,255,255,0.2)" strokeWidth={1} rx={3} />
            </G>
          );
        })}
      </Svg>
    </Animated.View>
  );
});

// ─── Coins renderer ──────────────────────────────────────────────────────────
const WorldCoins = React.memo(({
  worldX, consumed,
}: { worldX: SharedValue<number>; consumed: SharedValue<Record<number, boolean>> }) => {
  const containerStyle = useAnimatedStyle(() => ({
    transform: [{ translateX: -worldX.value }],
  }));

  const chunks = Array.from({ length: 40 }, (_, i) => i);
  const allCoins = chunks.flatMap(ci => getCoinsInChunk(ci));

  const [consumedState, setConsumedState] = useState<Record<number, boolean>>({});

  // Sync consumed state for rendering
  useEffect(() => {
    const id = setInterval(() => {
      setConsumedState({ ...consumed.value });
    }, 50);
    return () => clearInterval(id);
  }, []);

  return (
    <Animated.View style={[{ position: 'absolute', top: 0, left: 0, width: 40 * CHUNK_W, height: H }, containerStyle]} pointerEvents="none">
      <Svg width={40 * CHUNK_W} height={H}>
        <Defs>
          <SvgLinearGradient id="coinGold" x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0" stopColor="#fef08a" stopOpacity="1" />
            <Stop offset="0.5" stopColor="#fbbf24" stopOpacity="1" />
            <Stop offset="1" stopColor="#d97706" stopOpacity="1" />
          </SvgLinearGradient>
          <SvgRadialGradient id="coinSheen" cx="35%" cy="30%" r="50%">
            <Stop offset="0" stopColor="#fefce8" stopOpacity="0.9" />
            <Stop offset="1" stopColor="#fbbf24" stopOpacity="0" />
          </SvgRadialGradient>
        </Defs>
        {allCoins.map(coin => {
          if (consumedState[coin.id]) return null;
          return (
            <G key={coin.id}>
              {/* Outer glow ring */}
              <Circle cx={coin.x} cy={coin.y} r={17} fill="rgba(251,191,36,0.15)" />
              {/* Coin body */}
              <Circle cx={coin.x} cy={coin.y} r={12} fill="url(#coinGold)" />
              {/* Sheen */}
              <Circle cx={coin.x} cy={coin.y} r={12} fill="url(#coinSheen)" />
              {/* Inner ring */}
              <Circle cx={coin.x} cy={coin.y} r={8} fill="none" stroke="#d97706" strokeWidth={1.5} />
              {/* Star symbol */}
              <Path
                d={`M${coin.x},${coin.y-5} L${coin.x+1.5},${coin.y-1.5} L${coin.x+5},${coin.y-1.5} L${coin.x+2.5},${coin.y+1} L${coin.x+3.5},${coin.y+5} L${coin.x},${coin.y+2.5} L${coin.x-3.5},${coin.y+5} L${coin.x-2.5},${coin.y+1} L${coin.x-5},${coin.y-1.5} L${coin.x-1.5},${coin.y-1.5} Z`}
                fill="rgba(255,255,255,0.6)"
              />
              {/* Affirmation label */}
              {coin.label ? (
                <G>
                  <Rect x={coin.x - 30} y={coin.y - 40} width={60} height={18} rx={9} fill="rgba(124,58,237,0.9)" />
                  <Rect x={coin.x - 29} y={coin.y - 39} width={58} height={16} rx={8} fill="none" stroke="rgba(255,255,255,0.35)" strokeWidth={0.8} />
                  <SvgText
                    x={coin.x}
                    y={coin.y - 27}
                    textAnchor="middle"
                    fontSize={9}
                    fontWeight="bold"
                    fill="#fff"
                    letterSpacing={1.5}
                  >
                    {coin.label}
                  </SvgText>
                </G>
              ) : null}
            </G>
          );
        })}
      </Svg>
    </Animated.View>
  );
});

// ─── Obstacles renderer ──────────────────────────────────────────────────────
const WorldObstacles = React.memo(({ worldX }: { worldX: SharedValue<number> }) => {
  const containerStyle = useAnimatedStyle(() => ({
    transform: [{ translateX: -worldX.value }],
  }));

  const chunks = Array.from({ length: 40 }, (_, i) => i);
  const allObstacles = chunks.flatMap(ci => getObstaclesInChunk(ci));

  return (
    <Animated.View style={[{ position: 'absolute', top: 0, left: 0, width: 40 * CHUNK_W, height: H }, containerStyle]} pointerEvents="none">
      <Svg width={40 * CHUNK_W} height={H}>
        <Defs>
          <SvgLinearGradient id="thornGrad" x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0" stopColor="#6d28d9" stopOpacity="1" />
            <Stop offset="1" stopColor="#1e1b4b" stopOpacity="1" />
          </SvgLinearGradient>
        </Defs>
        {allObstacles.map(obs => {
          if (obs.type === 'thorn') {
            // Spiky thorn block
            const { x, y, w, h } = obs;
            return (
              <G key={obs.id}>
                {/* Base block */}
                <Rect x={x} y={y + 8} width={w} height={h - 8} fill="url(#thornGrad)" rx={3} />
                {/* Spikes */}
                {Array.from({ length: 3 }).map((_, si) => (
                  <Path
                    key={si}
                    d={`M${x + si * 10 + 5},${y + 8} L${x + si * 10},${y - 4} L${x + si * 10 + 10},${y - 4} Z`}
                    fill="#7c3aed"
                  />
                ))}
                {/* Glow */}
                <Rect x={x-2} y={y-6} width={w+4} height={h+8} fill="none" stroke="rgba(139,92,246,0.5)" strokeWidth={2} rx={3} />
              </G>
            );
          } else {
            // Dark stress cloud
            const { x, y } = obs;
            return (
              <G key={obs.id}>
                <Ellipse cx={x + 15} cy={y + 10} rx={30} ry={16} fill="rgba(30,20,60,0.85)" />
                <Ellipse cx={x + 30} cy={y + 5} rx={20} ry={14} fill="rgba(40,20,80,0.85)" />
                <Ellipse cx={x} cy={y + 12} rx={16} ry={12} fill="rgba(30,20,60,0.85)" />
                {/* Lightning bolt */}
                <Path d={`M${x+20},${y-5} L${x+13},${y+10} L${x+18},${y+10} L${x+11},${y+28} L${x+22},${y+12} L${x+17},${y+12} Z`} fill="#fde047" />
              </G>
            );
          }
        })}
      </Svg>
    </Animated.View>
  );
});

// ─── Player Character (Animated SVG Pixel Art) ───────────────────────────────
const PlayerCharacter = React.memo(({
  playerY, isGrounded, isJumping, isPressing, auraScale,
}: {
  playerY: SharedValue<number>;
  isGrounded: SharedValue<boolean>;
  isJumping: SharedValue<boolean>;
  isPressing: SharedValue<boolean>;
  auraScale: SharedValue<number>;
}) => {
  const runFrame = useSharedValue(0);

  useEffect(() => {
    runFrame.value = withRepeat(
      withTiming(1, { duration: 300, easing: Easing.linear }),
      -1, false
    );
  }, []);

  const containerStyle = useAnimatedStyle(() => {
    const screenY = playerY.value - PLAYER_H;
    const scaleX = isPressing.value ? 0.9 : 1.0;
    const scaleY = isJumping.value ? 1.15 : isPressing.value ? 0.85 : 1.0;
    return {
      transform: [
        { translateY: screenY },
        { scaleX },
        { scaleY },
      ],
    };
  });

  const auraStyle = useAnimatedStyle(() => ({
    transform: [{ scale: auraScale.value }],
    opacity: interpolate(auraScale.value, [1, 2], [0.3, 0.7]),
  }));

  // Leg animation props
  const legAProps = useAnimatedProps(() => {
    const legAngle = isGrounded.value ? Math.sin(runFrame.value * Math.PI * 2) * 12 : 0;
    return {
      transform: [{ rotate: `${legAngle}deg` }],
    } as any;
  });

  return (
    <View style={[{ position: 'absolute', left: PLAYER_SCREEN_X - PLAYER_W / 2, top: 0, width: PLAYER_W, height: PLAYER_H }]}>
      <Animated.View style={[StyleSheet.absoluteFillObject, containerStyle]}>
        {/* Aura glow */}
        <Animated.View style={[{
          position: 'absolute',
          left: -20, top: -15,
          width: PLAYER_W + 40, height: PLAYER_H + 30,
          borderRadius: 50,
          backgroundColor: '#c084fc',
        }, auraStyle]} />

        <Svg width={PLAYER_W} height={PLAYER_H}>
          {/* Shadow */}
          <Ellipse cx={PLAYER_W/2} cy={PLAYER_H - 2} rx={12} ry={4} fill="rgba(0,0,0,0.3)" />

          {/* Body */}
          <Rect x={8} y={16} width={16} height={20} fill="#7c3aed" rx={3} />
          {/* Body shine */}
          <Rect x={10} y={18} width={6} height={8} fill="rgba(255,255,255,0.2)" rx={2} />

          {/* Head */}
          <Rect x={6} y={4} width={20} height={16} fill="#fbbf24" rx={5} />
          {/* Hat brim */}
          <Rect x={4} y={4} width={24} height={5} fill="#7c3aed" rx={2} />
          {/* Hat top */}
          <Rect x={8} y={-3} width={16} height={10} fill="#7c3aed" rx={2} />
          {/* Hat star */}
          <Circle cx={PLAYER_W/2} cy={1} r={4} fill="#fde047" />
          <Path d={`M${PLAYER_W/2},${1-3} L${PLAYER_W/2+1},${1-1} L${PLAYER_W/2+3},${1-1} L${PLAYER_W/2+1.5},${1+1} L${PLAYER_W/2+2},${1+3} L${PLAYER_W/2},${1+2} L${PLAYER_W/2-2},${1+3} L${PLAYER_W/2-1.5},${1+1} L${PLAYER_W/2-3},${1-1} L${PLAYER_W/2-1},${1-1} Z`} fill="rgba(255,255,255,0.8)" />

          {/* Eyes */}
          <Circle cx={12} cy={10} r={2.5} fill="white" />
          <Circle cx={20} cy={10} r={2.5} fill="white" />
          <Circle cx={12.7} cy={10.5} r={1.2} fill="#1e1b4b" />
          <Circle cx={20.7} cy={10.5} r={1.2} fill="#1e1b4b" />

          {/* Mustache */}
          <Path d={`M10,14 Q13,16 16,14 Q19,16 22,14`} stroke="#7c2d12" strokeWidth={1.5} fill="none" />

          {/* Arms */}
          <Rect x={2} y={18} width={7} height={4} fill="#fbbf24" rx={2} />
          <Rect x={23} y={18} width={7} height={4} fill="#fbbf24" rx={2} />

          {/* Legs (animated) */}
          <Rect x={9} y={34} width={6} height={8} fill="#1e40af" rx={2} />
          <Rect x={17} y={34} width={6} height={8} fill="#1e40af" rx={2} />
          {/* Shoes */}
          <Rect x={7} y={40} width={9} height={5} fill="#7c2d12" rx={2} />
          <Rect x={16} y={40} width={9} height={5} fill="#7c2d12" rx={2} />
        </Svg>
      </Animated.View>
    </View>
  );
});

// ─── Affirmation Popup ───────────────────────────────────────────────────────
function AffiPop({ label, onDone }: { label: string; onDone: () => void }) {
  const opacity = useSharedValue(1);
  const ty = useSharedValue(0);
  useEffect(() => {
    opacity.value = withSequence(
      withTiming(1, { duration: 100 }),
      withTiming(0, { duration: 800, easing: Easing.out(Easing.ease) })
    );
    ty.value = withTiming(-60, { duration: 900, easing: Easing.out(Easing.ease) });
    const t = setTimeout(onDone, 950);
    return () => clearTimeout(t);
  }, []);
  const style = useAnimatedStyle(() => ({
    opacity: opacity.value,
    transform: [{ translateY: ty.value }],
  }));
  return (
    <Animated.View style={[{
      position: 'absolute',
      left: PLAYER_SCREEN_X - 50,
      top: H * 0.4,
      width: 100, alignItems: 'center',
      zIndex: 200,
    }, style]} pointerEvents="none">
      <LinearGradient colors={['#c084fc', '#7c3aed']} style={{ paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20 }}>
        <Text style={{ color: '#fff', fontWeight: '900', fontSize: 13, letterSpacing: 1.5 }}>{label}</Text>
      </LinearGradient>
    </Animated.View>
  );
}

// ─── Score Popup ─────────────────────────────────────────────────────────────
function ScorePop({ score, onDone }: { score: number; onDone: () => void }) {
  const opacity = useSharedValue(0);
  const ty = useSharedValue(0);
  useEffect(() => {
    opacity.value = withSequence(
      withTiming(1, { duration: 80 }),
      withTiming(0, { duration: 700 })
    );
    ty.value = withTiming(-50, { duration: 800, easing: Easing.out(Easing.ease) });
    const t = setTimeout(onDone, 820);
    return () => clearTimeout(t);
  }, []);
  const style = useAnimatedStyle(() => ({ opacity: opacity.value, transform: [{ translateY: ty.value }] }));
  return (
    <Animated.View style={[{ position: 'absolute', left: PLAYER_SCREEN_X + 20, top: H * 0.5, zIndex: 201 }, style]} pointerEvents="none">
      <Text style={{ color: '#fde047', fontWeight: '900', fontSize: 20, textShadowColor: '#000', textShadowRadius: 4, textShadowOffset: { width: 0, height: 1 } }}>+{score}</Text>
    </Animated.View>
  );
}

// ─── MAIN COMPONENT ──────────────────────────────────────────────────────────
export default function OrbitPulseGame({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const { playSound, stopSound, setGlobalVolume } = useSoundPlayer();

  // ── React State ──
  const [isPlayingReact, setIsPlayingReact] = useState(false);
  const [gameOver, setGameOver] = useState(false);
  const [score, setScore] = useState(0);
  const [distance, setDistance] = useState(0);
  const [health, setHealth] = useState(3);
  const [showTutorial, setShowTutorial] = useState(true);
  const [showQuitConfirm, setShowQuitConfirm] = useState(false);
  const [combo, setCombo] = useState(0);
  const [popups, setPopups] = useState<Array<{ id: number; label: string; pts: number }>>([]);
  const popupIdRef = useRef(0);

  const scoreRef = useRef(0);
  const comboRef = useRef(0);
  const comboTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const omSoundRef = useRef<Audio.Sound | null>(null);
  const extraTanpuraRef = useRef<Audio.Sound | null>(null);

  // ── Reanimated Shared Values ──
  const isPlaying = useSharedValue(false);
  const worldX = useSharedValue(0);         // How far the world has scrolled (world coord)
  const playerY = useSharedValue(GROUND_Y); // Player's bottom Y in screen coords
  const playerVY = useSharedValue(0);
  const worldSpeed = useSharedValue(WORLD_SPEED_INIT);
  const isGrounded = useSharedValue(true);
  const isJumping = useSharedValue(false);
  const isPressing = useSharedValue(false);
  const jumpCount = useSharedValue(0);
  const consumedCoins = useSharedValue<Record<number, boolean>>({});
  const hitObstacles = useSharedValue<Record<number, boolean>>({});
  const auraScale = useSharedValue(1.0);
  const screenFlash = useSharedValue(0);
  const screenShake = useSharedValue(0);

  useEffect(() => {
    const backAction = () => {
      if (isPlaying.value || showTutorial) {
        setShowQuitConfirm(true);
        isPlaying.value = false;
        setIsPlayingReact(false);
        return true;
      }
      return false;
    };
    const backHandler = BackHandler.addEventListener('hardwareBackPress', backAction);
    return () => backHandler.remove();
  }, [showTutorial]);

  // ── Audio ──
  useEffect(() => {
    if (!visible) return;
    (async () => {
      try {
        await Audio.setAudioModeAsync({ playsInSilentModeIOS: true, allowsRecordingIOS: false });
        const { sound } = await Audio.Sound.createAsync({ uri: OM_HIT_URL }, { shouldPlay: false, volume: 1.0 });
        omSoundRef.current = sound;
        const extraSrc = require('../assets/sounds/tanpura-mystic.m4a');
        const { sound: extra } = await Audio.Sound.createAsync(extraSrc, { shouldPlay: true, isLooping: true, volume: 0.35 });
        extraTanpuraRef.current = extra;
      } catch (_) {}
    })();
    return () => {
      omSoundRef.current?.unloadAsync();
      extraTanpuraRef.current?.unloadAsync();
    };
  }, [visible]);

  useEffect(() => {
    if (!visible) return;
    const tanpura = ALL_SLEEP_SOUNDS.find(s => s.id === TANPURA_SOUND_ID);
    if (tanpura) {
      setGlobalVolume(0.55);
      playSound(tanpura, 3600, undefined, 0.55, true);
    }
    return () => { stopSound(); setGlobalVolume(1); };
  }, [visible]);

  // ── JS Callbacks ──
  const addPopup = useCallback((label: string, pts: number) => {
    const id = ++popupIdRef.current;
    setPopups(prev => [...prev, { id, label, pts }]);
  }, []);

  const removePopup = useCallback((id: number) => {
    setPopups(prev => prev.filter(p => p.id !== id));
  }, []);

  const onCoinCollected = useCallback((label: string) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    omSoundRef.current?.setPositionAsync(0).catch(() => {});
    omSoundRef.current?.playAsync().catch(() => {});

    comboRef.current += 1;
    setCombo(comboRef.current);
    if (comboTimerRef.current) clearTimeout(comboTimerRef.current);
    comboTimerRef.current = setTimeout(() => {
      comboRef.current = 0;
      setCombo(0);
    }, 2000);

    const pts = COIN_SCORE * (comboRef.current >= 3 ? 2 : 1);
    scoreRef.current += pts;
    setScore(scoreRef.current);
    addPopup(label || '✦', pts);
  }, [addPopup]);

  const onDistanceUpdate = useCallback((d: number) => {
    setDistance(Math.floor(d / 10));
    scoreRef.current += 0.5;
    setScore(Math.floor(scoreRef.current));
  }, []);

  const onObstacleHit = useCallback(() => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
    screenFlash.value = withSequence(
      withTiming(0.6, { duration: 60 }),
      withTiming(0, { duration: 500 })
    );
    screenShake.value = withSequence(
      withTiming(16, { duration: 50 }),
      withTiming(-16, { duration: 50 }),
      withTiming(10, { duration: 40 }),
      withTiming(-10, { duration: 40 }),
      withTiming(0, { duration: 40 })
    );
    setHealth(h => {
      const nh = h - 1;
      if (nh <= 0) {
        isPlaying.value = false;
        setIsPlayingReact(false);
        setGameOver(true);
      }
      return nh;
    });
  }, []);

  const onJumpTrigger = useCallback(() => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
  }, []);

  // ── Game Loop (Runs on UI Thread) ──
  useFrameCallback((frameInfo) => {
    if (!isPlaying.value) return;

    const dt = Math.min((frameInfo.timeSincePreviousFrame ?? 16) / 1000, 0.05);

    // Accelerate world
    worldSpeed.value = Math.min(worldSpeed.value + WORLD_ACCEL * dt, WORLD_SPEED_MAX);
    worldX.value += worldSpeed.value * dt;

    // Apply gravity to player
    playerVY.value += GRAVITY * dt;
    playerVY.value = Math.min(playerVY.value, MAX_FALL_VY);
    playerY.value += playerVY.value * dt;

    // ── Platform collision ──
    const currentChunkIdx = Math.floor(worldX.value / CHUNK_W);
    let onPlatform = false;

    for (let ci = currentChunkIdx - 1; ci <= currentChunkIdx + 2; ci++) {
      const platforms = getPlatformsInChunk(ci);
      for (const plat of platforms) {
        // Platform top surface in screen coords = plat.y
        // Player feet = playerY.value
        // Player body spans [playerY.value - PLAYER_H, playerY.value]
        // Player screen X = PLAYER_SCREEN_X (fixed)
        const playerLeft = PLAYER_SCREEN_X - PLAYER_W / 2;
        const playerRight = PLAYER_SCREEN_X + PLAYER_W / 2;
        const platScreenLeft = plat.x - worldX.value;
        const platScreenRight = plat.x + plat.w - worldX.value;
        const platTop = plat.y; // screen Y of platform top

        const overlapX = playerRight > platScreenLeft && playerLeft < platScreenRight;
        const prevFeet = playerY.value - playerVY.value * dt;

        if (overlapX && prevFeet <= platTop + 5 && playerY.value >= platTop - 2 && playerVY.value >= 0) {
          playerY.value = platTop;
          playerVY.value = 0;
          isGrounded.value = true;
          isJumping.value = false;
          jumpCount.value = 0;
          onPlatform = true;
        }
      }
    }

    // ── Ground collision ──
    if (!onPlatform) {
      if (playerY.value >= GROUND_Y) {
        playerY.value = GROUND_Y;
        playerVY.value = 0;
        isGrounded.value = true;
        isJumping.value = false;
        jumpCount.value = 0;
      } else {
        isGrounded.value = false;
      }
    }

    // ── Coin collision ──
    for (let ci = currentChunkIdx - 1; ci <= currentChunkIdx + 2; ci++) {
      const coins = getCoinsInChunk(ci);
      for (const coin of coins) {
        if (consumedCoins.value[coin.id]) continue;
        const coinScreenX = coin.x - worldX.value;
        const dx = Math.abs(PLAYER_SCREEN_X - coinScreenX);
        const dy = Math.abs((playerY.value - PLAYER_H / 2) - coin.y);
        if (dx < PLAYER_W * 0.8 && dy < PLAYER_H * 0.8) {
          const map = Object.assign({}, consumedCoins.value);
          map[coin.id] = true;
          consumedCoins.value = map;
          auraScale.value = withTiming(Math.min(auraScale.value + 0.2, 2.2), { duration: 250 });
          runOnJS(onCoinCollected)(coin.label);
        }
      }
    }

    // ── Obstacle collision ──
    for (let ci = currentChunkIdx - 1; ci <= currentChunkIdx + 2; ci++) {
      const obstacles = getObstaclesInChunk(ci);
      for (const obs of obstacles) {
        if (hitObstacles.value[obs.id]) continue;
        const obsScreenX = obs.x - worldX.value;
        const playerLeft = PLAYER_SCREEN_X - PLAYER_W / 2 + 6;
        const playerRight = PLAYER_SCREEN_X + PLAYER_W / 2 - 6;
        const obsLeft = obsScreenX;
        const obsRight = obsScreenX + obs.w;
        const obsTop = obs.y;
        const obsBottom = obs.y + obs.h;
        const playerTop = playerY.value - PLAYER_H;
        const playerBottom = playerY.value;

        const xOverlap = playerRight > obsLeft && playerLeft < obsRight;
        const yOverlap = playerBottom > obsTop && playerTop < obsBottom;
        if (xOverlap && yOverlap) {
          const map = Object.assign({}, hitObstacles.value);
          map[obs.id] = true;
          hitObstacles.value = map;
          auraScale.value = withTiming(Math.max(auraScale.value - 0.3, 0.6), { duration: 300 });
          runOnJS(onObstacleHit)();
        }
      }
    }

    // Aura scale decay
    if (auraScale.value > 1) {
      auraScale.value = Math.max(1, auraScale.value - 0.3 * dt);
    }

    // Distance update (every ~0.5s equivalent)
    runOnJS(onDistanceUpdate)(worldX.value);
  });

  // ── Input Handling ──
  const tapGesture = Gesture.Tap()
    .onEnd(() => {
      if (gameOver || showQuitConfirm) return;
      if (showTutorial) {
        runOnJS(setShowTutorial)(false);
        runOnJS(setIsPlayingReact)(true);
        isPlaying.value = true;
        return;
      }
      if (!isPlaying.value) return;

      // Jump logic
      if (isGrounded.value || jumpCount.value < 1) {
        const jv = jumpCount.value === 0 ? JUMP_VY : DOUBLE_JUMP_VY;
        playerVY.value = jv;
        isGrounded.value = false;
        isJumping.value = true;
        jumpCount.value = jumpCount.value + 1;
        runOnJS(onJumpTrigger)();
      }
    });

  const longPressGesture = Gesture.LongPress()
    .minDuration(150)
    .onBegin(() => { isPressing.value = true; })
    .onFinalize(() => { isPressing.value = false; });

  const combinedGesture = Gesture.Simultaneous(tapGesture, longPressGesture);

  // ── Restart ──
  const restartGame = useCallback(() => {
    worldX.value = 0;
    playerY.value = GROUND_Y;
    playerVY.value = 0;
    worldSpeed.value = WORLD_SPEED_INIT;
    isGrounded.value = true;
    isJumping.value = false;
    isPressing.value = false;
    jumpCount.value = 0;
    consumedCoins.value = {};
    hitObstacles.value = {};
    auraScale.value = 1;
    screenFlash.value = 0;
    screenShake.value = 0;
    scoreRef.current = 0;
    comboRef.current = 0;
    setScore(0);
    setDistance(0);
    setHealth(3);
    setCombo(0);
    setGameOver(false);
    setPopups([]);
    setShowTutorial(false);
    setIsPlayingReact(true);
    isPlaying.value = true;
  }, []);

  const handleClosePress = useCallback(() => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    isPlaying.value = false;
    setIsPlayingReact(false);
    setShowQuitConfirm(true);
  }, []);

  // ── Animated Styles ──
  const flashStyle = useAnimatedStyle(() => ({ opacity: screenFlash.value }));
  const shakeStyle = useAnimatedStyle(() => ({ transform: [{ translateX: screenShake.value }] }));

  // ── Render ──
  return (
    <Modal visible={visible} animationType="fade" statusBarTranslucent transparent onRequestClose={handleClosePress}>
      <GestureHandlerRootView style={{ flex: 1 }}>
        <GestureDetector gesture={combinedGesture}>
          <View style={s.root}>

            {/* ── Background ── */}
            <ParallaxBackground worldX={worldX} />

            {/* ── Shake wrapper ── */}
            <Animated.View style={[StyleSheet.absoluteFillObject, shakeStyle]} pointerEvents="none">

              {/* ── World: Platforms ── */}
              <WorldPlatforms worldX={worldX} />

              {/* ── World: Obstacles ── */}
              <WorldObstacles worldX={worldX} />

              {/* ── World: Coins ── */}
              <WorldCoins worldX={worldX} consumed={consumedCoins} />

              {/* ── Ground Tiles ── */}
              <GroundTiles worldX={worldX} />

              {/* ── Player ── */}
              <PlayerCharacter
                playerY={playerY}
                isGrounded={isGrounded}
                isJumping={isJumping}
                isPressing={isPressing}
                auraScale={auraScale}
              />

            </Animated.View>

            {/* ── Screen Flash ── */}
            <Animated.View style={[StyleSheet.absoluteFillObject, { backgroundColor: '#c084fc', zIndex: 300 }, flashStyle]} pointerEvents="none" />

            {/* ── Popups ── */}
            {popups.map(p => (
              <React.Fragment key={p.id}>
                {p.label && p.label !== '✦' && (
                  <AffiPop label={p.label} onDone={() => removePopup(p.id)} />
                )}
                <ScorePop score={p.pts} onDone={() => removePopup(p.id)} />
              </React.Fragment>
            ))}

            {/* ── HUD ── */}
            <View style={s.hud} pointerEvents="box-none">
              {/* Close button */}
              <TouchableOpacity onPress={handleClosePress} style={s.closeBtn} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
                <View style={{ backgroundColor: 'rgba(0,0,0,0.4)', borderRadius: 22, padding: 8, borderWidth: 1, borderColor: 'rgba(192,132,252,0.4)' }}>
                  <Ionicons name="close" size={20} color="#e9d5ff" />
                </View>
              </TouchableOpacity>

              {/* Score center */}
              <View style={{ alignItems: 'center', flex: 1 }}>
                <Text style={s.hudLabel}>FLOW POINTS</Text>
                <Text style={s.hudScore}>{score.toLocaleString()}</Text>
                <Text style={s.hudDistance}>{distance}m · {combo >= 3 ? '🔥 COMBO x' + combo : combo > 0 ? '✦ x' + combo : ''}</Text>
              </View>

              {/* Health */}
              <View style={{ alignItems: 'flex-end', minWidth: 70 }}>
                <View style={{ flexDirection: 'row', gap: 4 }}>
                  {Array.from({ length: 3 }).map((_, i) => (
                    <View key={i} style={{
                      width: 16, height: 16, borderRadius: 8,
                      backgroundColor: i < health ? '#f472b6' : 'rgba(255,255,255,0.15)',
                      borderWidth: 1.5,
                      borderColor: i < health ? '#ec4899' : 'rgba(255,255,255,0.1)',
                    }} />
                  ))}
                </View>
                <Text style={{ color: 'rgba(255,255,255,0.45)', fontSize: 10, marginTop: 4 }}>BREATH</Text>
              </View>
            </View>

            {/* ── Tutorial Overlay ── */}
            {showTutorial && (
              <View style={s.overlay} pointerEvents="none">
                <BlurView intensity={25} tint="dark" style={StyleSheet.absoluteFillObject} />
                <View style={s.card}>
                  <LinearGradient colors={['#4c1d95', '#1e1b4b']} style={[StyleSheet.absoluteFillObject, { borderRadius: 28 }]} />
                  <View style={{ borderWidth: 1, borderColor: 'rgba(192,132,252,0.4)', borderRadius: 28, ...StyleSheet.absoluteFillObject }} />

                  {/* Title */}
                  <View style={{ alignItems: 'center', marginBottom: 20 }}>
                    <Text style={{ fontSize: 11, color: '#c084fc', fontWeight: '800', letterSpacing: 3, marginBottom: 8 }}>MIND MARIO</Text>
                    <Text style={{ fontSize: 26, fontWeight: '900', color: '#fff', letterSpacing: 1 }}>AURA FLOW</Text>
                    <Text style={{ fontSize: 13, color: 'rgba(255,255,255,0.6)', marginTop: 6, textAlign: 'center' }}>A calming journey for mind & soul</Text>
                  </View>

                  {/* Instructions */}
                  <View style={{ gap: 14 }}>
                    {[
                      { icon: '👆', title: 'TAP', desc: 'to Jump' },
                      { icon: '👆👆', title: 'DOUBLE TAP', desc: 'Double Jump in mid-air' },
                      { icon: '✦', title: 'COLLECT', desc: 'Joy Seeds for calm energy' },
                      { icon: '⚡', title: 'AVOID', desc: 'Stress clouds & thorns' },
                    ].map((item, i) => (
                      <View key={i} style={{ flexDirection: 'row', alignItems: 'center', gap: 14 }}>
                        <View style={{ width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(192,132,252,0.2)', alignItems: 'center', justifyContent: 'center' }}>
                          <Text style={{ fontSize: 18 }}>{item.icon}</Text>
                        </View>
                        <View style={{ flex: 1 }}>
                          <Text style={{ color: '#c084fc', fontWeight: '900', fontSize: 13, letterSpacing: 1 }}>{item.title}</Text>
                          <Text style={{ color: 'rgba(255,255,255,0.65)', fontSize: 13 }}>{item.desc}</Text>
                        </View>
                      </View>
                    ))}
                  </View>

                  {/* Start button */}
                  <LinearGradient colors={['#7c3aed', '#4c1d95']} style={{ marginTop: 28, borderRadius: 99, overflow: 'hidden' }}>
                    <View style={{ paddingVertical: 16, alignItems: 'center' }}>
                      <Text style={{ color: '#fff', fontWeight: '900', fontSize: 16, letterSpacing: 2 }}>TAP TO BEGIN ✦</Text>
                    </View>
                  </LinearGradient>
                </View>
              </View>
            )}

            {/* ── Game Over ── */}
            {gameOver && (
              <View style={[s.overlay, { zIndex: 500 }]}>
                <BlurView intensity={40} tint="dark" style={StyleSheet.absoluteFillObject} />
                <View style={[s.card, { paddingVertical: 36 }]}>
                  <LinearGradient colors={['#1e1b4b', '#0f0c29']} style={[StyleSheet.absoluteFillObject, { borderRadius: 28 }]} />
                  <View style={{ borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)', borderRadius: 28, ...StyleSheet.absoluteFillObject }} />

                  <Text style={{ fontSize: 13, color: '#f472b6', fontWeight: '900', letterSpacing: 3, textAlign: 'center', marginBottom: 8 }}>SESSION ENDED</Text>
                  <Text style={{ fontSize: 32, fontWeight: '900', color: '#fff', textAlign: 'center', marginBottom: 6 }}>Take a breath.</Text>
                  <Text style={{ fontSize: 16, color: 'rgba(255,255,255,0.6)', textAlign: 'center', marginBottom: 28 }}>You did beautifully. Try again.</Text>

                  <View style={{ backgroundColor: 'rgba(192,132,252,0.1)', borderRadius: 16, padding: 16, marginBottom: 24, width: '100%' }}>
                    <Text style={{ color: 'rgba(255,255,255,0.6)', fontSize: 12, textAlign: 'center', marginBottom: 4 }}>FLOW SCORE</Text>
                    <Text style={{ color: '#fff', fontSize: 36, fontWeight: '900', textAlign: 'center' }}>{score.toLocaleString()}</Text>
                    <Text style={{ color: 'rgba(255,255,255,0.5)', fontSize: 13, textAlign: 'center', marginTop: 4 }}>{distance}m traveled</Text>
                  </View>

                  <TouchableOpacity onPress={restartGame} style={{ width: '100%', marginBottom: 12 }}>
                    <LinearGradient colors={['#7c3aed', '#4c1d95']} style={{ borderRadius: 99, paddingVertical: 16, alignItems: 'center' }}>
                      <Text style={{ color: '#fff', fontWeight: '900', fontSize: 16, letterSpacing: 1.5 }}>FLOW AGAIN ✦</Text>
                    </LinearGradient>
                  </TouchableOpacity>
                  <TouchableOpacity onPress={onClose} style={{ width: '100%', paddingVertical: 14, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)', borderRadius: 99 }}>
                    <Text style={{ color: 'rgba(255,255,255,0.5)', fontWeight: '700', fontSize: 14 }}>Return to Peace</Text>
                  </TouchableOpacity>
                </View>
              </View>
            )}

            {/* ── Quit Confirm ── */}
            {showQuitConfirm && (
              <View style={[s.overlay, { zIndex: 600 }]}>
                <BlurView intensity={50} tint="dark" style={StyleSheet.absoluteFillObject} />
                <View style={[s.card, { paddingVertical: 36 }]}>
                  <LinearGradient colors={['#1e1b4b', '#0f0c29']} style={[StyleSheet.absoluteFillObject, { borderRadius: 28 }]} />
                  <View style={{ borderWidth: 1, borderColor: 'rgba(192,132,252,0.35)', borderRadius: 28, ...StyleSheet.absoluteFillObject }} />

                  <Ionicons name="moon" size={44} color="#c084fc" style={{ marginBottom: 16, alignSelf: 'center' }} />
                  <Text style={{ fontSize: 22, fontWeight: '900', color: '#fff', textAlign: 'center', marginBottom: 10 }}>Leaving the Flow?</Text>
                  <Text style={{ color: 'rgba(255,255,255,0.6)', fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: 28 }}>Your peace journey is still ongoing. Would you like to keep flowing or return to calm?</Text>

                  <TouchableOpacity style={{ width: '100%', marginBottom: 12 }} onPress={() => {
                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                    setShowQuitConfirm(false);
                    setIsPlayingReact(true);
                    isPlaying.value = true;
                  }}>
                    <LinearGradient colors={['#7c3aed', '#4c1d95']} style={{ borderRadius: 99, paddingVertical: 16, alignItems: 'center' }}>
                      <Text style={{ color: '#fff', fontWeight: '900', fontSize: 15, letterSpacing: 1 }}>KEEP FLOWING ✦</Text>
                    </LinearGradient>
                  </TouchableOpacity>
                  <TouchableOpacity style={{ width: '100%', paddingVertical: 14, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)', borderRadius: 99 }} onPress={() => {
                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
                    onClose();
                  }}>
                    <Text style={{ color: 'rgba(255,255,255,0.5)', fontWeight: '700', fontSize: 14 }}>Return to Peace</Text>
                  </TouchableOpacity>
                </View>
              </View>
            )}

          </View>
        </GestureDetector>
      </GestureHandlerRootView>
    </Modal>
  );
}

// ─── Styles ──────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0f0c29',
    overflow: 'hidden',
  },
  hud: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 40,
    left: 16, right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 400,
  },
  hudLabel: {
    fontSize: 10,
    color: '#c084fc',
    fontWeight: '800',
    letterSpacing: 2.5,
    marginBottom: 2,
  },
  hudScore: {
    fontSize: 34,
    fontWeight: '900',
    color: '#fff',
    textShadowColor: '#7c3aed',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  hudDistance: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.55)',
    fontWeight: '600',
    marginTop: 2,
    letterSpacing: 0.5,
  },
  closeBtn: {
    zIndex: 10,
  },
  overlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 400,
  },
  card: {
    width: '88%',
    padding: 28,
    borderRadius: 28,
    overflow: 'hidden',
  },
});
