import React, { useState, useEffect, useRef } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet, StatusBar,
  Modal, ImageBackground, Image, ScrollView, Dimensions, Animated, AppState, Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import * as Location from 'expo-location';
import * as Haptics from 'expo-haptics';
import * as Notifications from 'expo-notifications';
import * as TaskManager from 'expo-task-manager';
import { Pedometer } from 'expo-sensors';
import Svg, { Circle as SvgCircle } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useSoundPlayer, type PlayableSoundMeta } from '@/lib/soundPlayerContext';
import { ALL_SLEEP_SOUNDS, SOUND_IMAGES } from '@/lib/sleepSoundsData';
import { getLocalSoundImageUri } from '@/lib/soundImagePreload';
import { getBgSourceSync } from '@/lib/bgImages';
import { useBgContext } from '@/lib/bgContext';
import {
  WALK_BG_TASK, WalkMode, WalkState, DEFAULT_WALK_STATE,
  getWalkState, saveWalkState, clearWalkState, haversineKmWalk,
} from '@/lib/walkStore';

const { width: SCREEN_W } = Dimensions.get('window');

// ── Ring geometry ─────────────────────────────────────────────────────────────
const RING_SIZE   = Math.min(SCREEN_W - 100, 210);
const RING_STROKE = 9;
const R_RING      = (RING_SIZE - RING_STROKE * 2) / 2;
const C_RING      = 2 * Math.PI * R_RING;

// ── Walk physics ──────────────────────────────────────────────────────────────
const SHATAPAVALLI_STEPS = 100;
const STRIDE_KM: Record<WalkMode, number>    = { barefoot: 0.00065, regular: 0.00076 };
const CAL_PER_STEP: Record<WalkMode, number> = { barefoot: 0.045,   regular: 0.04   };

// ── Step targets ──────────────────────────────────────────────────────────────
const STEP_TARGETS: Array<{ label: string; steps: number | null }> = [
  { label: 'Free',   steps: null  },
  { label: '2,500',  steps: 2500  },
  { label: '5,000',  steps: 5000  },
  { label: '8,000',  steps: 8000  },
  { label: '10K',    steps: 10000 },
];

// ── Grounding / barefoot education ────────────────────────────────────────────
const GROUNDING_BENEFITS = [
  {
    id: 'what',
    emoji: '🌍',
    title: 'What is Earthing?',
    short: 'Direct skin contact with Earth\'s electric field',
    detail: 'The Earth carries a mild negative electric charge — a vast reservoir of free electrons generated by lightning storms, solar wind, and geothermal activity. When bare skin touches natural ground — grass, soil, sand, stone — electrons flow freely into your body. This is called Earthing or Grounding. It is not mysticism; it is electrochemistry. Every cell in your body benefits. Shoes with rubber or synthetic soles are electrical insulators — they completely sever this ancient connection that humans maintained for millions of years.',
  },
  {
    id: 'inflammation',
    emoji: '🔥',
    title: 'Reduces Inflammation',
    short: 'Free electrons neutralise free radicals instantly',
    detail: 'Chronic inflammation — the root of heart disease, diabetes, arthritis, and most modern illness — is driven by positively-charged free radicals that damage cells. Earth\'s free electrons are nature\'s most abundant antioxidant. They neutralise these radicals on contact. Published research in the Journal of Inflammation (2010) demonstrated measurable reduction in white blood cell activity and inflammatory markers after grounding sessions as short as 30 minutes. Barefoot walking on natural ground is anti-inflammatory medicine that costs nothing.',
  },
  {
    id: 'gut',
    emoji: '🌱',
    title: 'Heals Gut & Microbiome',
    short: 'Resets vagal tone, reduces leaky gut, enriches microbiome',
    detail: 'The vagus nerve — the great wandering nerve that connects brain to gut — is directly calmed by grounding. Lower cortisol improves gut motility and reduces intestinal permeability (leaky gut), one of the silent drivers of autoimmune conditions. Walking barefoot on soil also exposes your feet to diverse soil microbes from genus Mycobacterium and Lactobacillus which enter through small skin contacts. These enrich your gut microbiome — the foundation of immunity, mood regulation, and digestion. Ayurveda has always known this: walking on clean earth is Agni medicine.',
  },
  {
    id: 'cortisol',
    emoji: '🌙',
    title: 'Lowers Stress & Cortisol',
    short: 'Synchronises your nervous system to Earth\'s 7.83 Hz pulse',
    detail: 'The Earth resonates at 7.83 Hz — the Schumann Resonance — remarkably close to alpha brain waves (8–12 Hz) which are the signature of calm, creative, meditative states. When you ground, your nervous system entrains to this frequency, normalising the cortisol curve throughout the day. Studies show improved sleep depth, reduced anxiety, and better hormonal balance within 2 weeks of regular barefoot practice. This is why walking in nature feels qualitatively different from walking on concrete in shoes — your nervous system is literally syncing with the planet.',
  },
  {
    id: 'blood',
    emoji: '🩸',
    title: 'Improves Circulation',
    short: 'Increases zeta potential — blood cells repel and flow freely',
    detail: 'Grounding increases the surface charge (zeta potential) of red blood cells. Higher charge causes them to repel each other like same-pole magnets, reducing dangerous clumping and blood viscosity. A landmark 2013 study showed that just 2 hours of grounding significantly reduced blood viscosity — one of the primary modifiable risk factors for heart attack and stroke. Barefoot walking is, quite literally, a cardiovascular intervention.',
  },
  {
    id: 'sleep',
    emoji: '💤',
    title: 'Deepens Sleep',
    short: 'Resets melatonin rhythm through Earth\'s electric field',
    detail: 'Modern life insulates us entirely from Earth\'s electric field — rubber soles, synthetic flooring, elevated beds. This is an evolutionary anomaly. For millions of years, humans slept on the ground, and their bodies were continuously grounded. This sustained contact regulated melatonin secretion and cortisol timing. Grounding research shows people fall asleep faster, wake less frequently, and feel genuinely restored. Even 20 minutes of barefoot walking in the evening significantly shifts melatonin onset earlier, improving sleep depth.',
  },
  {
    id: 'design',
    emoji: '🦶',
    title: 'Your Body\'s Natural Design',
    short: 'The human foot is a masterpiece — shoes flatten its intelligence',
    detail: 'The human foot contains 26 bones, 33 joints, and over 100 muscles, tendons, and ligaments — a complex sensory organ that evolved over 4 million years of barefoot movement. The foot\'s arch acts as a spring; its numerous proprioceptors (sensory receptors) constantly communicate with the brain, spine, and postural muscles. Modern cushioned shoes silence this entire system. Research shows that minimal or barefoot walking improves balance, strengthens intrinsic foot muscles, corrects posture, and reduces knee and hip injury risk. Your feet know how to walk — trust them on natural surfaces.',
  },
  {
    id: 'when',
    emoji: '👟',
    title: 'When to Use Shoes',
    short: 'Shoes protect, but not on clean natural ground',
    detail: 'Shoes serve a vital protective role — on concrete, hot asphalt, sharp gravel, glass, polluted urban surfaces, or extreme temperatures. Use them without hesitation in these contexts. But when you are on clean grass, moist soil, beach sand, flat natural stone, or clean forest ground — taking off your shoes is not a quirk. It is returning to your biological baseline. Ayurveda\'s concept of Prithvi (Earth element) connection is not metaphor — it is physiology. Walk barefoot for at least 20 minutes daily on natural ground, and you will feel the difference within a week.',
  },
  {
    id: 'shatapavalli',
    emoji: '🚶',
    title: 'Why Exactly 100 Steps?',
    short: 'Shatapavalli — the precise Ayurvedic post-meal prescription',
    detail: 'Shatapavalli literally means "one hundred steps" (shata = 100, pavalli = steps). Ayurveda prescribes exactly 100 steps — no more, no less — after a full meal. This precise number gently activates peristalsis (gut movement), stimulates Agni (digestive fire), and encourages blood flow to the digestive organs without diverting it away from them. Walking more than 100 steps after a heavy meal is actively harmful — it competes with digestion for blood supply, weakens Agni, causes bloating, and disrupts absorption. The wisdom is in the precision: just enough movement to catalyse digestion, not enough to interfere with it.',
  },
];

// ── Nada walk sounds ──────────────────────────────────────────────────────────
const WALK_SOUND_IDS = [
  'morning_birds', 'spring_birds', 'forest_birds', 'forest_breeze', 'gentle_wind',
  'jungle_rain', 'sea_waves', 'flowing_water', 'tabla_beat', 'tabla_shuffle',
  'bansuri_melody', 'bamboo_flute', 'andean_flute', 'forest_flute', 'sitar',
  'indian_beats', 'om_shanti',
];

const WALK_SOUNDS: PlayableSoundMeta[] = [
  ...ALL_SLEEP_SOUNDS.filter(s => WALK_SOUND_IDS.includes(s.id)),
  { id: 'mantra_gayatri',    label: 'Gayatri',             emoji: '🌞', color: '#fbbf24', top: '#1A1000', bot: '#0A0800', cat: 'Mantra', desc: 'Universal prayer of light',     src: { uri: 'https://ik.imagekit.io/rcsesr4xf/gayatri-mantra-ghanpaath.mp3' } },
  { id: 'mantra_shivtandav', label: 'Shiv Tandav',         emoji: '🔱', color: '#60a5fa', top: '#0A1020', bot: '#05080F', cat: 'Mantra', desc: 'The cosmic dance of Shiva',     src: { uri: 'https://ik.imagekit.io/rcsesr4xf/Shiva-Tandav.mp3' } },
  { id: 'mantra_lalitha',    label: 'Lalitha Sahasranama', emoji: '🌺', color: '#f472b6', top: '#1A0818', bot: '#0A040C', cat: 'Mantra', desc: 'Thousand names of the Goddess', src: { uri: 'https://ik.imagekit.io/rcsesr4xf/Lalitha-Sahasranamam.mp3' } },
  { id: 'stotra_shiv',       label: 'Shiv Sankalpa',       emoji: '🕉️', color: '#93c5fd', top: '#140A1A', bot: '#0A050F', cat: 'Mantra', desc: 'Sacred Vedic intention',        src: require('../../assets/sounds/shiv-sankalpa-suktam.m4a') },
];

// ── Pure helpers ──────────────────────────────────────────────────────────────
function stepsToKm(steps: number, mode: WalkMode) { return parseFloat((steps * STRIDE_KM[mode]).toFixed(3)); }
function stepsToCals(steps: number, mode: WalkMode) { return Math.round(steps * CAL_PER_STEP[mode]); }

function fmtElapsed(ms: number): string {
  const s = Math.floor(ms / 1000);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  if (h > 0) return `${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;
  return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;
}

function fmtDist(km: number): string {
  if (km >= 1) return km.toFixed(2) + ' km';
  return Math.round(km * 1000) + ' m';
}

function bgKeyToWalkLabel(bgKey: string, shata: boolean): string {
  if (shata) return '100-STEP WALK';
  if (bgKey === 'night' || bgKey === 'brahma') return 'GOOD NIGHT';
  if (bgKey === 'predawn') return 'EARLY MORNING WALK';
  if (bgKey === 'sunrise' || bgKey === 'morning') return 'MORNING WALK';
  if (bgKey === 'midday') return 'MID-DAY REST';
  if (bgKey === 'afternoon') return 'AFTERNOON WALK';
  return 'EVENING WALK';
}

function bgKeyToNC(bgKey: string): string {
  if (bgKey === 'night' || bgKey === 'brahma' || bgKey === 'predawn') return '#60a5fa';
  if (bgKey === 'sunrise' || bgKey === 'morning') return '#34d399';
  if (bgKey === 'midday' || bgKey === 'afternoon') return '#fbbf24';
  return '#f472b6';
}

function bgKeyToIdleSub(bgKey: string): string {
  if (bgKey === 'night' || bgKey === 'brahma') return 'Sleep is sacred · Rest deeply';
  if (bgKey === 'predawn') return 'Rise early · Ground your spirit';
  if (bgKey === 'sunrise' || bgKey === 'morning') return 'Best time to walk · Boost your day';
  if (bgKey === 'midday') return 'Sun is high · Rest and digest';
  if (bgKey === 'afternoon') return 'Great time for a stroll · Stay active';
  return 'Wind down · Clear your mind';
}

function bgKeyToWalkType(bgKey: string): 'morning' | 'evening' {
  return ['night','brahma','predawn','sunrise','morning','midday'].includes(bgKey) ? 'morning' : 'evening';
}

export default function WalkTab() {
  const insets = useSafeAreaInsets();
  const { playingId, isPaused: soundPaused, playSound, stopSound, togglePause } = useSoundPlayer();

  // ── State ──────────────────────────────────────────────────────────────────
  const { bgUri: ctxBgUri, bgKey } = useBgContext();
  const [walkState,       setWalkState]       = useState<WalkState>({ ...DEFAULT_WALK_STATE });
  const [elapsedMs,       setElapsedMs]       = useState(0);
  const [targetSteps,     setTargetSteps]     = useState<number | null>(null);
  const [walkMode,        setWalkMode]        = useState<WalkMode>('regular');
  const [shatapavalli,    setShatapavalli]    = useState(false);
  const [showSounds,      setShowSounds]      = useState(false);
  const [bgPermGranted,   setBgPermGranted]   = useState(false);
  const [pedometerAvail,  setPedometerAvail]  = useState(false);
  const [celebrateDone,   setCelebrateDone]   = useState(false);
  const [expandedBenefit, setExpandedBenefit] = useState<string | null>(null);
  const [groundingOpen,   setGroundingOpen]   = useState(false);

  // ── Refs ───────────────────────────────────────────────────────────────────
  const pulseAnim       = useRef(new Animated.Value(1)).current;
  const celebAnim       = useRef(new Animated.Value(0)).current;
  const pollRef         = useRef<ReturnType<typeof setInterval> | null>(null);
  const locationSubRef  = useRef<Location.LocationSubscription | null>(null);
  const pedometerSubRef = useRef<{ remove: () => void } | null>(null);
  const stepBaseRef     = useRef(0);
  const appStateRef     = useRef(AppState.currentState);

  // ── Check pedometer availability ──────────────────────────────────────────
  useEffect(() => {
    Pedometer.isAvailableAsync().catch(() => false).then(avail => setPedometerAvail(!!avail));
  }, []);

  // ── Pulse aura loop ────────────────────────────────────────────────────────
  useEffect(() => {
    Animated.loop(
      Animated.sequence([
        Animated.timing(pulseAnim, { toValue: 1.055, duration: 2400, useNativeDriver: true }),
        Animated.timing(pulseAnim, { toValue: 1,     duration: 2400, useNativeDriver: true }),
      ])
    ).start();
  }, []);

  // ── Restore active walk on mount (handles app-kill + reopen) ──────────────
  useEffect(() => {
    (async () => {
      const state = await getWalkState();
      if (state.active) {
        setWalkState(state);
        setTargetSteps(state.targetSteps);
        setWalkMode(state.walkMode);
        setShatapavalli(state.shatapavalli);
        startPolling();
        if (!state.paused) {
          startForegroundLocation(state);
          startPedometer(state.stepCount);
        }
      }
      const bgStatus = await Location.getBackgroundPermissionsAsync();
      setBgPermGranted(bgStatus.status === 'granted');
    })();
    return () => { stopPolling(); stopPedometer(); };
  }, []);

  // ── AppState: resume foreground sub when app comes back to front ───────────
  useEffect(() => {
    const sub = AppState.addEventListener('change', async (next) => {
      if (next === 'active' && appStateRef.current !== 'active') {
        const state = await getWalkState();
        setWalkState({ ...state });
        if (state.active && !state.paused) {
          startForegroundLocation(state);
          startPedometer(state.stepCount);
        }
      }
      if (next === 'background') {
        locationSubRef.current?.remove();
        locationSubRef.current = null;
        stopPedometer();
      }
      appStateRef.current = next;
    });
    return () => sub.remove();
  }, []);

  // ── Pedometer subscription (the fix for step tracking) ───────────────────
  function startPedometer(baseSteps: number) {
    stopPedometer();
    stepBaseRef.current = baseSteps;
    if (!pedometerAvail) return;
    pedometerSubRef.current = Pedometer.watchStepCount(async (result) => {
      const totalSteps = stepBaseRef.current + result.steps;
      const cur = await getWalkState();
      if (!cur.active || cur.paused) return;
      cur.stepCount  = totalSteps;
      cur.distanceKm = stepsToKm(totalSteps, cur.walkMode);
      if (!cur.notifiedTarget && cur.targetSteps && totalSteps >= cur.targetSteps) {
        cur.notifiedTarget = true;
        fireTargetNotif(cur.type, cur.targetSteps);
      }
      if (cur.shatapavalli && totalSteps >= SHATAPAVALLI_STEPS && !cur.notifiedTarget) {
        cur.notifiedTarget = true;
        await saveWalkState(cur);
        setWalkState({ ...cur });
        fireShatapavallNotif();
        setCelebrateDone(true);
        Animated.sequence([
          Animated.timing(celebAnim, { toValue: 1, duration: 600, useNativeDriver: true }),
          Animated.delay(2200),
          Animated.timing(celebAnim, { toValue: 0, duration: 400, useNativeDriver: true }),
        ]).start();
        stopWalk();
        return;
      }
      await saveWalkState(cur);
      setWalkState({ ...cur });
    });
  }

  function stopPedometer() {
    pedometerSubRef.current?.remove();
    pedometerSubRef.current = null;
  }

  // ── Polling (1 s tick) ─────────────────────────────────────────────────────
  function startPolling() {
    stopPolling();
    pollRef.current = setInterval(async () => {
      const s = await getWalkState();
      setWalkState({ ...s });
      const now = Date.now();
      if (s.active && !s.paused) {
        setElapsedMs(now - s.startMs - s.pausedMs);
      } else if (s.active && s.paused && s.pausedAt) {
        setElapsedMs(s.pausedAt - s.startMs - s.pausedMs);
      }
    }, 1000);
  }

  function stopPolling() {
    if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
  }

  // ── Foreground location subscription ──────────────────────────────────────
  async function startForegroundLocation(state: WalkState) {
    locationSubRef.current?.remove();
    locationSubRef.current = await Location.watchPositionAsync(
      { accuracy: Location.Accuracy.BestForNavigation, timeInterval: 5000, distanceInterval: 5 },
      async (loc) => {
        const cur = await getWalkState();
        if (!cur.active || cur.paused) return;
        const { latitude: lat, longitude: lng } = loc.coords;
        if (cur.lastLat !== null && cur.lastLng !== null) {
          const d = haversineKmWalk(cur.lastLat, cur.lastLng, lat, lng);
          if (d >= 0.003 && d <= 0.3) {
            cur.distanceKm = parseFloat((cur.distanceKm + d).toFixed(4));
          }
        }
        cur.lastLat = lat;
        cur.lastLng = lng;
        await saveWalkState(cur);
        setWalkState({ ...cur });
      }
    );
  }

  // ── Notifications ────────────────────────────────────────────────────────────
  async function fireTargetNotif(type: 'morning' | 'evening', steps: number) {
    try {
      await Notifications.scheduleNotificationAsync({
        content: {
          title: type === 'morning' ? '🌅 Morning Walk Complete!' : '🌆 Evening Walk Complete!',
          body: `${steps.toLocaleString()} steps achieved. Your prana flows freely. 🙏`,
          sound: true,
        },
        trigger: null,
      });
    } catch { /* */ }
  }

  async function fireShatapavallNotif() {
    try {
      await Notifications.scheduleNotificationAsync({
        content: {
          title: '🚶 Shatapavalli Complete!',
          body: 'Exactly 100 steps done. Agni is awakened. Walk no more — rest and digest. 🙏',
          sound: true,
        },
        trigger: null,
      });
    } catch { /* */ }
  }

  // ── Start ──────────────────────────────────────────────────────────────────
  async function startWalk(shata = false) {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    const { status } = await Location.requestForegroundPermissionsAsync();
    if (status !== 'granted') {
      Alert.alert('Location Required', 'Please allow location access to track your walk.');
      return;
    }
    if (!bgPermGranted) {
      const { status: bg } = await Location.requestBackgroundPermissionsAsync();
      setBgPermGranted(bg === 'granted');
    }
    const now  = Date.now();
    const type = bgKeyToWalkType(bgKey);
    const tSteps = shata ? SHATAPAVALLI_STEPS : targetSteps;
    const newState: WalkState = {
      active: true, paused: false, type,
      walkMode, shatapavalli: shata,
      startMs: now, pausedMs: 0, pausedAt: null,
      stepCount: 0, distanceKm: 0,
      targetKm: null, targetSteps: tSteps,
      lastLat: null, lastLng: null, notifiedTarget: false,
    };
    await saveWalkState(newState);
    setWalkState(newState);
    setElapsedMs(0);
    setCelebrateDone(false);

    if (bgPermGranted) {
      try {
        const running = await TaskManager.isTaskRegisteredAsync(WALK_BG_TASK);
        if (!running) {
          await Location.startLocationUpdatesAsync(WALK_BG_TASK, {
            accuracy: Location.Accuracy.Balanced,
            timeInterval: 15000,
            distanceInterval: 15,
            foregroundService: {
              notificationTitle: shata ? '🚶 Shatapavalli Active' : type === 'morning' ? '🚶 Morning Walk Active' : '🌆 Evening Walk Active',
              notificationBody:  shata ? 'Walking 100 steps after your meal…' : 'Tracking your walk in the background…',
              notificationColor: shata ? '#a3e635' : type === 'morning' ? '#34d399' : '#f472b6',
            },
          });
        }
      } catch { /* */ }
    }
    await startForegroundLocation(newState);
    startPedometer(0);
    startPolling();
  }

  // ── Pause ──────────────────────────────────────────────────────────────────
  async function pauseWalk() {
    Haptics.selectionAsync();
    locationSubRef.current?.remove();
    locationSubRef.current = null;
    stopPedometer();
    const cur = await getWalkState();
    const now = Date.now();
    const updated = { ...cur, paused: true, pausedAt: now };
    await saveWalkState(updated);
    setWalkState(updated);
    setElapsedMs(now - cur.startMs - cur.pausedMs);
  }

  // ── Resume ─────────────────────────────────────────────────────────────────
  async function resumeWalk() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    const cur = await getWalkState();
    if (!cur.pausedAt) return;
    const added = Date.now() - cur.pausedAt;
    const updated = { ...cur, paused: false, pausedMs: cur.pausedMs + added, pausedAt: null };
    await saveWalkState(updated);
    setWalkState(updated);
    await startForegroundLocation(updated);
    startPedometer(updated.stepCount);
  }

  // ── Stop ───────────────────────────────────────────────────────────────────
  async function stopWalk() {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    locationSubRef.current?.remove();
    locationSubRef.current = null;
    stopPolling();
    stopPedometer();
    try {
      const running = await TaskManager.isTaskRegisteredAsync(WALK_BG_TASK);
      if (running) await Location.stopLocationUpdatesAsync(WALK_BG_TASK);
    } catch { /* */ }
    const cur = await getWalkState();
    const now = Date.now();
    const finalMs = cur.pausedAt
      ? cur.pausedAt - cur.startMs - cur.pausedMs
      : now - cur.startMs - cur.pausedMs;
    setElapsedMs(finalMs);
    await clearWalkState();
    setWalkState({ ...DEFAULT_WALK_STATE });
    setCelebrateDone(false);
  }

  // ── Derived values ─────────────────────────────────────────────────────────
  const activeMode  = walkState.active ? walkState.walkMode : walkMode;
  const steps       = walkState.stepCount;
  const dist        = stepsToKm(steps, activeMode);
  const cals        = stepsToCals(steps, activeMode);
  const isShata     = walkState.active ? walkState.shatapavalli : shatapavalli;
  const NC          = isShata ? '#a3e635' : bgKeyToNC(bgKey);
  const tgt         = isShata ? SHATAPAVALLI_STEPS : (walkState.active ? walkState.targetSteps : targetSteps);
  const prog        = walkState.active
    ? tgt
      ? Math.min(1, steps / tgt)
      : Math.min(1, elapsedMs / (45 * 60 * 1000))
    : 0;
  const walkLabel   = bgKeyToWalkLabel(bgKey, isShata);
  const isRestTime  = (bgKey === 'night' || bgKey === 'brahma') && !walkState.active;
  const isNoonRest  = bgKey === 'midday' && !walkState.active;
  const playingSound = WALK_SOUNDS.find(x => x.id === playingId);

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <ImageBackground source={{ uri: ctxBgUri ?? getBgSourceSync('night') }} style={st.bg} resizeMode="cover">
      <StatusBar barStyle="light-content" translucent backgroundColor="transparent" />

      {/* Dark gradient — stronger at bottom for readability */}
      <LinearGradient
        colors={['rgba(0,0,0,0.20)', 'rgba(0,0,0,0.36)', 'rgba(0,0,0,0.68)']}
        locations={[0, 0.4, 1]}
        style={StyleSheet.absoluteFillObject}
        pointerEvents="none"
      />
      {/* Glass shimmer from top-left */}
      <LinearGradient
        colors={['rgba(255,255,255,0.13)', 'rgba(255,255,255,0.04)', 'transparent']}
        start={{ x: 0, y: 0 }} end={{ x: 0.65, y: 0.65 }}
        style={StyleSheet.absoluteFillObject}
        pointerEvents="none"
      />

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={{ paddingTop: insets.top + 12, paddingBottom: insets.bottom + 16, paddingHorizontal: 18 }}
        showsVerticalScrollIndicator={false}
        bounces={false}
      >

        {/* ══ 1. HEADER ════════════════════════════════════════════════════ */}
        <View style={st.headerRow}>
          <View>
            <Text style={[st.headerLabel, { color: NC }]}>{walkLabel}</Text>
            {walkState.active && (
              <View style={st.liveRow}>
                <Animated.View style={[st.liveDot, { backgroundColor: NC, transform: [{ scale: pulseAnim }] }]} />
                <Text style={[st.liveTxt, { color: NC }]}>LIVE · {fmtElapsed(elapsedMs)}</Text>
              </View>
            )}
          </View>
          <TouchableOpacity onPress={() => setShowSounds(true)} activeOpacity={0.82} style={[st.soundBtn, { borderColor: playingId ? NC + '70' : 'rgba(255,255,255,0.22)' }]}>
            <Text style={{ fontSize: 13 }}>🎧</Text>
            {playingSound && <Text style={[st.soundBtnLbl, { color: NC }]} numberOfLines={1}>{playingSound.label}</Text>}
          </TouchableOpacity>
        </View>

        {/* ══ 2. MODE SELECTOR (pre-walk only) ═════════════════════════════ */}
        {!walkState.active && !isRestTime && !isNoonRest && (
          <View style={st.modeRow}>
            {(['barefoot', 'regular'] as WalkMode[]).map(m => {
              const sel = walkMode === m;
              return (
                <TouchableOpacity
                  key={m}
                  onPress={() => { Haptics.selectionAsync(); setWalkMode(m); }}
                  activeOpacity={0.8}
                  style={[st.modePill, sel && { backgroundColor: NC + '22', borderColor: NC }]}
                >
                  <Text style={st.modeEmoji}>{m === 'barefoot' ? '🦶' : '👟'}</Text>
                  <View>
                    <Text style={[st.modeName, { color: sel ? NC : 'rgba(255,255,255,0.75)' }]}>
                      {m === 'barefoot' ? 'Barefoot' : 'Regular'}
                    </Text>
                    <Text style={st.modeSub}>{m === 'barefoot' ? 'Ground yourself' : 'Standard walk'}</Text>
                  </View>
                  {sel && (
                    <View style={[st.modeCheck, { backgroundColor: NC }]}>
                      <Text style={{ fontSize: 9, color: '#000' }}>✓</Text>
                    </View>
                  )}
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {/* ══ 3. HERO STEP RING ═══════════════════════════════════════════ */}
        <View style={st.heroWrap}>
          <View style={{ width: RING_SIZE, height: RING_SIZE, alignSelf: 'center' }}>
            {/* Aura layers */}
            <Animated.View style={[st.aura, { width: RING_SIZE + 56, height: RING_SIZE + 56, borderRadius: (RING_SIZE + 56) / 2, backgroundColor: NC + '06', transform: [{ scale: pulseAnim }], top: -28, left: -28 }]} />
            <Animated.View style={[st.aura, { width: RING_SIZE + 28, height: RING_SIZE + 28, borderRadius: (RING_SIZE + 28) / 2, backgroundColor: NC + '14', transform: [{ scale: pulseAnim }], top: -14, left: -14 }]} />

            {/* SVG ring */}
            <Svg width={RING_SIZE} height={RING_SIZE} viewBox={`0 0 ${RING_SIZE} ${RING_SIZE}`}>
              <SvgCircle cx={RING_SIZE / 2} cy={RING_SIZE / 2} r={R_RING} fill="none" stroke="rgba(255,255,255,0.09)" strokeWidth={RING_STROKE} />
              <SvgCircle cx={RING_SIZE / 2} cy={RING_SIZE / 2} r={R_RING} fill="none" stroke={NC}
                strokeWidth={RING_STROKE + 14} strokeLinecap="round"
                strokeDasharray={String(C_RING)} strokeDashoffset={String(C_RING * (1 - prog))}
                transform={`rotate(-90,${RING_SIZE / 2},${RING_SIZE / 2})`} opacity={0.12} />
              <SvgCircle cx={RING_SIZE / 2} cy={RING_SIZE / 2} r={R_RING} fill="none" stroke={NC}
                strokeWidth={RING_STROKE + 6} strokeLinecap="round"
                strokeDasharray={String(C_RING)} strokeDashoffset={String(C_RING * (1 - prog))}
                transform={`rotate(-90,${RING_SIZE / 2},${RING_SIZE / 2})`} opacity={0.26} />
              <SvgCircle cx={RING_SIZE / 2} cy={RING_SIZE / 2} r={R_RING} fill="none" stroke={NC}
                strokeWidth={RING_STROKE} strokeLinecap="round"
                strokeDasharray={String(C_RING)} strokeDashoffset={String(C_RING * (1 - prog))}
                transform={`rotate(-90,${RING_SIZE / 2},${RING_SIZE / 2})`} opacity={0.97} />
              <SvgCircle cx={RING_SIZE / 2} cy={RING_SIZE / 2} r={R_RING} fill="none" stroke="#FFFFFF"
                strokeWidth={2} strokeLinecap="round"
                strokeDasharray={String(C_RING)} strokeDashoffset={String(C_RING * (1 - prog))}
                transform={`rotate(-90,${RING_SIZE / 2},${RING_SIZE / 2})`} opacity={0.32} />
            </Svg>

            {/* Ring center */}
            <View style={st.ringCenter}>
              <View style={st.ringCard}>
                <LinearGradient colors={[NC + '22', NC + '08', 'transparent']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}
                  style={StyleSheet.absoluteFillObject} pointerEvents="none" />
                {!walkState.active ? (
                  <>
                    <Text style={st.heroIdleTitle}>{isRestTime ? 'Good Night' : isNoonRest ? 'Rest Time' : isShata ? 'Walk 100 Steps' : walkLabel.split(' ').map((w:string) => w.charAt(0)+w.slice(1).toLowerCase()).join(' ')}</Text>
                    <Text style={st.heroIdleSub}>
                      {isRestTime ? 'Sleep is sacred · Rest deeply' : isNoonRest ? 'Midday sun is high · Rest & digest' : isShata ? 'Walk 100 steps right after eating' : bgKeyToIdleSub(bgKey)}
                    </Text>
                    {tgt !== null && (
                      <View style={[st.targetBadge, { borderColor: NC + '40', backgroundColor: NC + '15' }]}>
                        <Text style={[st.targetBadgeTxt, { color: NC }]}>{tgt.toLocaleString()} steps</Text>
                      </View>
                    )}
                  </>
                ) : (
                  <>
                    <Text style={[st.heroSteps, { color: NC }]}>{steps.toLocaleString()}</Text>
                    <Text style={st.heroStepsUnit}>steps</Text>
                    {walkState.paused && <Text style={[st.pausedLabel, { color: NC + '90' }]}>PAUSED</Text>}
                  </>
                )}
              </View>
            </View>
          </View>
        </View>

        {/* ══ 4. TARGET PICKER ══════════════════════════════════════════════ */}
        {!walkState.active && !isRestTime && !isNoonRest && (
          <View style={st.targetRow}>
            {STEP_TARGETS.map(opt => {
              const sel = opt.steps === targetSteps;
              return (
                <TouchableOpacity
                  key={opt.label}
                  onPress={() => { if (walkState.active) return; Haptics.selectionAsync(); setTargetSteps(opt.steps); }}
                  style={[st.targetPill, sel ? { backgroundColor: NC + '20', borderColor: NC + '65' } : { backgroundColor: 'rgba(255,255,255,0.07)', borderColor: 'rgba(255,255,255,0.14)' }]}
                  activeOpacity={0.75}
                >
                  <Text style={[st.targetTxt, { color: sel ? NC : 'rgba(255,255,255,0.50)' }]}>{opt.label}</Text>
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {/* ══ 5. SHATAPAVALLI TOGGLE ════════════════════════════════════════ */}
        {!walkState.active && !isRestTime && !isNoonRest && (
          <TouchableOpacity
            onPress={() => { Haptics.selectionAsync(); setShatapavalli(v => !v); }}
            activeOpacity={0.8}
            style={[st.shataChip, shatapavalli && { backgroundColor: 'rgba(163,230,53,0.14)', borderColor: 'rgba(163,230,53,0.45)' }]}
          >
            <Text style={{ fontSize: 16 }}>🍽️</Text>
            <View style={{ flex: 1 }}>
              <Text style={[st.shataChipLbl, shatapavalli && { color: '#a3e635' }]}>After-meal Shatapavalli</Text>
              <Text style={st.shataChipSub}>Walk 100 steps right after eating</Text>
            </View>
            <View style={[st.shataChipToggle, shatapavalli && { backgroundColor: '#a3e635', borderColor: '#a3e635' }]}>
              {shatapavalli && <Text style={{ fontSize: 8, color: '#000', fontWeight: '900' }}>✓</Text>}
            </View>
          </TouchableOpacity>
        )}

        {/* ══ 5.5 LIVE STATS PANEL ═══════════════════════════════════════ */}
        {walkState.active && (
          <View style={[st.statsPanel, { borderColor: NC + '30' }]}>
            <View style={st.statCell}>
              <Text style={[st.statCellVal, { color: NC }]}>{fmtElapsed(elapsedMs)}</Text>
              <Text style={st.statCellLbl}>TIME</Text>
            </View>
            <View style={[st.statSep, { backgroundColor: NC + '25' }]} />
            <View style={st.statCell}>
              <Text style={[st.statCellVal, { color: NC }]}>{steps.toLocaleString()}</Text>
              <Text style={st.statCellLbl}>STEPS</Text>
            </View>
            <View style={[st.statSep, { backgroundColor: NC + '25' }]} />
            <View style={st.statCell}>
              <Text style={[st.statCellVal, { color: NC }]}>{fmtDist(dist)}</Text>
              <Text style={st.statCellLbl}>DIST</Text>
            </View>
            <View style={[st.statSep, { backgroundColor: NC + '25' }]} />
            <View style={st.statCell}>
              <Text style={[st.statCellVal, { color: NC }]}>{cals}</Text>
              <Text style={st.statCellLbl}>KCAL</Text>
            </View>
          </View>
        )}

        {/* ══ 6. ACTION BUTTONS ═══════════════════════════════════════════ */}
        {isRestTime ? (
          <View style={st.restPanel}>
            <Text style={st.restIcon}>🌙</Text>
            <Text style={st.restTitle}>Good Night</Text>
            <Text style={st.restSub}>{'It\'s sleep time. Walks work best in the\nmorning or evening. Rest well tonight.'}</Text>
          </View>
        ) : isNoonRest ? (
          <View style={st.restPanel}>
            <Text style={st.restIcon}>☀️</Text>
            <Text style={st.restTitle}>Rest & Digest</Text>
            <Text style={st.restSub}>{'Midday is rest time. Come back for your\nafternoon or evening walk.'}</Text>
          </View>
        ) : (
          <View style={st.actionRow}>
            {!walkState.active ? (
              <TouchableOpacity style={[st.startBtn, { backgroundColor: NC }]} onPress={() => startWalk(false)} activeOpacity={0.85}>
                <Text style={[st.startTxt, { color: '#0A1408' }]}>START WALK</Text>
              </TouchableOpacity>
            ) : walkState.paused ? (
              <>
                <TouchableOpacity style={[st.halfBtn, { borderColor: NC + '55' }]} onPress={resumeWalk} activeOpacity={0.8}>
                  <Text style={[st.halfTxt, { color: NC }]}>▶ RESUME</Text>
                </TouchableOpacity>
                <TouchableOpacity style={st.endBtn} onPress={stopWalk} activeOpacity={0.8}>
                  <Text style={st.endTxt}>■ END</Text>
                </TouchableOpacity>
              </>
            ) : (
              <>
                <TouchableOpacity style={[st.halfBtn, { borderColor: NC + '55' }]} onPress={pauseWalk} activeOpacity={0.8}>
                  <Text style={[st.halfTxt, { color: NC }]}>⏸ PAUSE</Text>
                </TouchableOpacity>
                <TouchableOpacity style={st.endBtn} onPress={stopWalk} activeOpacity={0.8}>
                  <Text style={st.endTxt}>■ END</Text>
                </TouchableOpacity>
              </>
            )}
          </View>
        )}

        {/* ══ 7. GROUNDING BENEFITS ACCORDION ═════════════════════════════ */}
        {!walkState.active && !isRestTime && !isNoonRest && (
          <View style={{ marginTop: 16 }}>
            <TouchableOpacity activeOpacity={0.85} onPress={() => setGroundingOpen(v => !v)} style={st.groundHeader}>
              <View style={{ flex: 1 }}>
                <Text style={st.groundTitle}>Grounding Effect — The Science</Text>
                <Text style={st.groundSub}>Touch the earth with bare feet. Your body was designed for this.</Text>
              </View>
              <Text style={[st.groundChevron, { color: NC, fontSize: 12 }]}>{groundingOpen ? '▲' : '▼'}</Text>
            </TouchableOpacity>
            {groundingOpen && GROUNDING_BENEFITS.map(item => {
              const open = expandedBenefit === item.id;
              return (
                <TouchableOpacity key={item.id} activeOpacity={0.9} onPress={() => setExpandedBenefit(open ? null : item.id)} style={st.groundItem}>
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
                    <Text style={{ fontSize: 18 }}>{item.emoji}</Text>
                    <View style={{ flex: 1 }}>
                      <Text style={st.groundItemTitle}>{item.title}</Text>
                      <Text style={st.groundItemShort}>{item.short}</Text>
                    </View>
                    <Text style={[st.groundChevron, { color: open ? NC : 'rgba(255,255,255,0.30)' }]}>{open ? '▲' : '▼'}</Text>
                  </View>
                  {open && (
                    <Text style={st.groundItemDetail}>{item.detail}</Text>
                  )}
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {/* ══ 8. FOOTER MICRO-INFO ════════════════════════════════════════ */}
        {!bgPermGranted && walkState.active && (
          <Text style={st.bgWarn}>Enable "Always" location for background tracking</Text>
        )}

      </ScrollView>

      {/* ══ SHATAPAVALLI CELEBRATION OVERLAY ════════════════════════════ */}
      {celebrateDone && (
        <Animated.View pointerEvents="none" style={[StyleSheet.absoluteFillObject, st.celebOverlay, { opacity: celebAnim }]}>
          <Text style={st.celebEmoji}>🚶</Text>
          <Text style={st.celebTitle}>Shatapavalli Complete!</Text>
          <Text style={st.celebSub}>{'Exactly 100 steps. Agni is awakened.\nRest now — let your body digest. 🙏'}</Text>
        </Animated.View>
      )}

      {/* ══ NADA SOUND PICKER MODAL ══════════════════════════════════════ */}
      <Modal visible={showSounds} transparent animationType="slide" onRequestClose={() => setShowSounds(false)}>
        <TouchableOpacity style={st.modalBg} activeOpacity={1} onPress={() => setShowSounds(false)} />
        <View style={[st.soundSheet, { paddingBottom: insets.bottom + 20 }]}>
          <LinearGradient colors={['rgba(255,255,255,0.11)', 'rgba(255,255,255,0.03)']} style={StyleSheet.absoluteFillObject} />
          <View style={st.sheetHandle} />
          <Text style={st.sheetTitle}>🎧 Headphone Sanctuary</Text>
          <Text style={st.sheetSub}>Plug in your headphones and let sacred Nada guide every step.{'\n'}Your walk becomes a moving meditation.</Text>

          {playingId && (
            <TouchableOpacity style={st.stopSndBtn} onPress={() => { stopSound(); setShowSounds(false); }}>
              <Text style={st.stopSndTxt}>◼ Stop Sound</Text>
            </TouchableOpacity>
          )}

          <ScrollView style={{ maxHeight: 420 }} showsVerticalScrollIndicator={false} contentContainerStyle={st.soundGrid}>
            {WALK_SOUNDS.map(snd => {
              const isOn = playingId === snd.id && !soundPaused;
              const isPsd = playingId === snd.id && soundPaused;
              const rawUri = SOUND_IMAGES[snd.id] ?? (snd as any).imageUri;
              const imgUri = rawUri ? getLocalSoundImageUri(rawUri) : undefined;
              return (
                <TouchableOpacity
                  key={snd.id}
                  onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); if (playingId === snd.id) togglePause(); else playSound(snd, 3600); setShowSounds(false); }}
                  style={[st.sndChip, (isOn || isPsd) && { borderColor: snd.color + '80', borderWidth: 1.5 }]}
                  activeOpacity={0.82}
                >
                  {imgUri ? (
                    <Image source={{ uri: imgUri }} style={StyleSheet.absoluteFillObject} resizeMode="cover" />
                  ) : (
                    <LinearGradient colors={[snd.color + '50', snd.top, snd.bot]} style={StyleSheet.absoluteFillObject} />
                  )}
                  <LinearGradient colors={['transparent', 'rgba(0,0,0,0.55)', 'rgba(0,0,0,0.82)']} locations={[0, 0.45, 1]}
                    style={[StyleSheet.absoluteFillObject, { borderRadius: 14 }]} />
                  {(isOn || isPsd) && (
                    <View style={[st.sndBadge, { backgroundColor: snd.color + 'DD' }]}>
                      <Text style={st.sndBadgeTxt}>{isOn ? '◉ PLAYING' : '⏸ PAUSED'}</Text>
                    </View>
                  )}
                  <View style={st.sndCardBottom}>
                    <Text style={{ fontSize: 17, lineHeight: 22 }}>{snd.emoji}</Text>
                    <View style={{ flex: 1 }}>
                      <Text style={[st.sndLabel, isOn && { color: snd.color }]} numberOfLines={1}>{snd.label}</Text>
                      <Text style={st.sndDesc} numberOfLines={1}>{snd.desc}</Text>
                    </View>
                  </View>
                </TouchableOpacity>
              );
            })}
          </ScrollView>

          <Text style={st.sheetQuote}>"Every step is a mantra. Every breath, a prayer.{'\n'}Walk as though your feet are kissing the earth."</Text>
        </View>
      </Modal>
    </ImageBackground>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────
const st = StyleSheet.create({
  bg: { flex: 1, backgroundColor: '#0A1A10' },

  // Header
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  headerLabel: { fontSize: 11, fontWeight: '900', letterSpacing: 1.8 },
  liveRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 4 },
  liveDot: { width: 5, height: 5, borderRadius: 3 },
  liveTxt: { fontSize: 10, fontWeight: '700', letterSpacing: 0.5 },
  soundBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 99, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 5, maxWidth: 130 },
  soundBtnLbl: { fontSize: 9, fontWeight: '700' },

  // Mode selector
  modeRow: { flexDirection: 'row', gap: 8, marginBottom: 18 },
  modePill: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', backgroundColor: 'rgba(0,0,0,0.22)', paddingHorizontal: 12, paddingVertical: 10 },
  modeEmoji: { fontSize: 20 },
  modeName: { fontSize: 13, fontWeight: '800', letterSpacing: 0.2 },
  modeSub: { fontSize: 9.5, color: 'rgba(255,255,255,0.40)', marginTop: 1 },
  modeCheck: { width: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },

  // Hero ring
  heroWrap: { marginVertical: 14 },
  aura: { position: 'absolute' },
  ringCenter: { position: 'absolute', top: 0, left: 0, width: RING_SIZE, height: RING_SIZE, alignItems: 'center', justifyContent: 'center' },
  ringCard: { width: RING_SIZE - 72, borderRadius: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', backgroundColor: 'rgba(0,0,0,0.26)', overflow: 'hidden', paddingHorizontal: 16, paddingVertical: 14, alignItems: 'center' },

  // Ring — idle
  heroIdleTitle: { fontSize: 16, fontWeight: '900', textAlign: 'center', color: '#FFFFFF', marginBottom: 4, letterSpacing: 0.2, textShadowColor: 'rgba(0,0,0,0.85)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 6 },
  heroIdleSub: { fontSize: 10, color: 'rgba(255,255,255,0.55)', textAlign: 'center', lineHeight: 15, textShadowColor: 'rgba(0,0,0,0.80)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  targetBadge: { marginTop: 10, borderRadius: 99, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 4 },
  targetBadgeTxt: { fontSize: 10, fontWeight: '800' },

  // Ring — active
  heroSteps: { fontSize: 44, fontWeight: '200', letterSpacing: -2, lineHeight: 50, color: '#FFFFFF', textShadowColor: 'rgba(0,0,0,0.85)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 8 },
  heroStepsUnit: { fontSize: 11, color: 'rgba(255,255,255,0.55)', marginTop: -2, marginBottom: 6 },
  divider: { width: 40, height: 1, backgroundColor: 'rgba(255,255,255,0.18)', marginVertical: 4 },
  statValue: { fontSize: 12, fontWeight: '700', color: '#FFFFFF', textAlign: 'center' },
  statLabel: { fontSize: 8, color: 'rgba(255,255,255,0.40)', marginTop: 1, textAlign: 'center', fontWeight: '600' },
  pausedLabel: { fontSize: 8, fontWeight: '900', letterSpacing: 2, marginTop: 8 },

  // Target picker
  targetRow: { flexDirection: 'row', gap: 6, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 14 },
  targetPill: { borderRadius: 99, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 7 },
  targetTxt: { fontSize: 11, fontWeight: '700' },

  // Shatapavalli chip
  shataChip: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', backgroundColor: 'rgba(255,255,255,0.05)', paddingHorizontal: 14, paddingVertical: 11, marginBottom: 14 },
  shataChipLbl: { fontSize: 12, fontWeight: '800', color: 'rgba(255,255,255,0.65)', letterSpacing: 0.2 },
  shataChipSub: { fontSize: 9.5, color: 'rgba(255,255,255,0.32)', marginTop: 1.5 },
  shataChipToggle: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.28)', backgroundColor: 'rgba(255,255,255,0.06)', alignItems: 'center', justifyContent: 'center' },
  // Grounding section header
  groundHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 4, marginBottom: 10 },
  // Live stats panel
  statsPanel: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.28)', borderRadius: 20, borderWidth: 1, paddingVertical: 20, marginBottom: 14 },
  statCell: { flex: 1, alignItems: 'center' },
  statCellVal: { fontSize: 24, fontWeight: '200', letterSpacing: -0.5, lineHeight: 28 },
  statCellLbl: { fontSize: 8, fontWeight: '800', color: 'rgba(255,255,255,0.38)', letterSpacing: 1.4, marginTop: 4 },
  statSep: { width: 1, height: 38 },

  // Rest / sleep / noon panels
  restPanel: { alignItems: 'center', paddingVertical: 30, marginBottom: 8 },
  restIcon: { fontSize: 46, marginBottom: 12 },
  restTitle: { fontSize: 24, fontWeight: '800', color: '#FFFFFF', marginBottom: 8, letterSpacing: 0.2 },
  restSub: { fontSize: 13, color: 'rgba(255,255,255,0.42)', textAlign: 'center', lineHeight: 20 },
  // Action buttons
  actionRow: { flexDirection: 'row', gap: 10, marginBottom: 8 },
  startBtn: { flex: 1, borderRadius: 99, paddingVertical: 18, alignItems: 'center' },
  startTxt: { fontSize: 14, fontWeight: '900', letterSpacing: 1.5 },
  halfBtn: { flex: 1, borderRadius: 99, borderWidth: 1.5, paddingVertical: 16, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.06)' },
  halfTxt: { fontSize: 13, fontWeight: '900', letterSpacing: 1 },
  endBtn: { flex: 1, borderRadius: 99, borderWidth: 1.5, borderColor: 'rgba(239,68,68,0.42)', paddingVertical: 16, alignItems: 'center', backgroundColor: 'rgba(239,68,68,0.08)' },
  endTxt: { fontSize: 13, fontWeight: '900', color: '#f87171', letterSpacing: 1 },

  // Grounding benefits
  groundTitle: { fontSize: 13, fontWeight: '900', color: '#FFFFFF', marginBottom: 3, letterSpacing: 0.3 },
  groundSub: { fontSize: 10, color: 'rgba(255,255,255,0.40)', marginBottom: 10, letterSpacing: 0.2 },
  groundItem: { borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', backgroundColor: 'rgba(0,0,0,0.18)', paddingHorizontal: 14, paddingVertical: 12, marginBottom: 8 },
  groundItemTitle: { fontSize: 12, fontWeight: '800', color: '#FFFFFF', letterSpacing: 0.1 },
  groundItemShort: { fontSize: 9.5, color: 'rgba(255,255,255,0.40)', marginTop: 2 },
  groundChevron: { fontSize: 10, fontWeight: '900' },
  groundItemDetail: { fontSize: 10.5, color: 'rgba(255,255,255,0.60)', marginTop: 10, lineHeight: 16 },

  // Footer
  footerInfo: { fontSize: 10, textAlign: 'center', fontWeight: '600', marginTop: 6 },
  bgWarn: { fontSize: 9, color: 'rgba(251,191,36,0.65)', textAlign: 'center', marginTop: 4 },

  // Celebration
  celebOverlay: { alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.72)' },
  celebEmoji: { fontSize: 52, marginBottom: 12 },
  celebTitle: { fontSize: 20, fontWeight: '900', color: '#FFFFFF', textAlign: 'center', marginBottom: 6 },
  celebSub: { fontSize: 13, color: 'rgba(255,255,255,0.65)', textAlign: 'center' },

  // Sound picker modal
  modalBg: { flex: 1, backgroundColor: 'rgba(0,0,0,0.52)' },
  soundSheet: { backgroundColor: 'rgba(10,16,28,0.97)', borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 20, paddingTop: 12, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(255,255,255,0.09)' },
  sheetHandle: { width: 36, height: 4, backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 2, alignSelf: 'center', marginBottom: 18 },
  sheetTitle: { fontSize: 18, fontWeight: '900', color: '#FFFFFF', marginBottom: 6 },
  sheetSub: { fontSize: 12, color: 'rgba(255,255,255,0.42)', lineHeight: 18, marginBottom: 16 },
  stopSndBtn: { borderRadius: 99, borderWidth: 1, borderColor: 'rgba(239,68,68,0.38)', backgroundColor: 'rgba(239,68,68,0.10)', paddingVertical: 10, alignItems: 'center', marginBottom: 14 },
  stopSndTxt: { fontSize: 12, fontWeight: '800', color: '#f87171' },
  soundGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingBottom: 8 },
  sndChip: { width: (SCREEN_W - 52) / 2, height: 120, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.10)', overflow: 'hidden', justifyContent: 'flex-end' },
  sndCardBottom: { flexDirection: 'row', alignItems: 'flex-end', gap: 7, paddingHorizontal: 10, paddingBottom: 9 },
  sndLabel: { fontSize: 10, fontWeight: '900', color: '#FFFFFF', lineHeight: 14 },
  sndDesc: { fontSize: 8, color: 'rgba(255,255,255,0.50)', lineHeight: 11 },
  sndBadge: { position: 'absolute', top: 8, right: 8, borderRadius: 99, paddingHorizontal: 7, paddingVertical: 3 },
  sndBadgeTxt: { fontSize: 7, fontWeight: '900', color: '#000000DD', letterSpacing: 0.4 },
  sheetQuote: { fontSize: 10, color: 'rgba(255,255,255,0.28)', textAlign: 'center', fontStyle: 'italic', lineHeight: 16, marginBottom: 6 },
});
